draft two perpendicular flap case
precice/tutorials pull request #110
Opened 2020-10-22 13:35 UTC by carme-hp

2020-10-22 14:37 UTC, carme-hp commented
Motivation for this tutorial case is to test multi-coupling. Instead of one single flap, now we have two flaps, which means that the case involves three participants: Fluid, Solid1 and Solid2. For the first one we use OpenFOAM solver pimpleFoam and for the second we use the deal.II Adapter. 

The geometry of the flaps is defined directly in the deal.II Adapter solver. Because the flaps are located at different positions we need different executables for the solid participants. To obtain them we need to compile https://github.com/precice/dealii-adapter/blob/c332050b5770bf99459b8be596fd6e41f3401a26/linear_elasticity/linear_elasticity.cc#L208-L220 changing the parameters regarding the position of the flap. 

- For **Solid1**:

        point_bottom =
   	    dim == 3 ? Point<dim>(-1.05, 0, 0) : Point<dim>(-1.05, 0);  
        point_tip = dim == 3 ? Point<dim>(-0.95, 1, 0.3) : Point<dim>(-0.95, 1); //flap1 

- For **Solid2**: 

        point_bottom =
          dim == 3 ? Point<dim>(0.95, 0, 0) : Point<dim>(0.95, 0);  
        point_tip = dim == 3 ? Point<dim>(1.05, 1, 0.3) : Point<dim>(1.05, 1); // flap2

The executables are named linear_elasticity1 and linear_elasticity2 respectively. 

In the precice-config.xml we define the communication between the solid participants and the Fluid participant. Here we can select the mapping (see https://github.com/precice/precice/wiki/Mapping-Configuration ).

**Current status**

- [ ] mapping:nearest-neighbor

- [ ]  mapping:rbf-thin-plate-splines

- [ ] linear case

- [ ] non-linear case

The current priority is to find out why the solver crashes, which happens at t=0.55. If we use the rbf-thin-plate-splines mapping instead, it crashes immediately.

2020-10-22 16:17 UTC, MakisH requested changes
In a good shape already! There are a few points that need fixing or implementation, this review may help.

And we need to make the case work, of course.

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Allrun
> +    PIDParticipant2=$!
We need to extend this for `Solid2`

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Allrun
> +echo "Waiting for the participants to exit..., PIDs: ${PIDParticipant1}, ${PIDParticipant2}"
Also here

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Allrun
> +        kill ${PIDParticipant2}
and here

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Allrun
> +if [ $? -ne 0 ] || [ "$(grep -c -E "error:" ${Participant1}.log)" -ne 0 ] || [ "$(grep -c -E "error:" ${Participant2}.log)" -ne 0 ]; then
and here

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Allrun
> +    kill ${PIDParticipant2}
```suggestion
    kill ${PIDParticipant2}
    kill ${PIDParticipant3}
```

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/README.md
> +# Tutorial for an FSI simulation of an elastic flap perpendicular to a channel flow
Don't forget to adapt the `README.md`

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Solid1/linear_elasticity.prm
> +  set Scenario            = PF
It would be better to add a separate scenario (e.g. `PF2` or `TwoPF`) and integrate this in the deal.II adapter.

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Solid1/nonlinear_elasticity.prm
> +    set Scenario            = PF
Same here as in linear: Add a separate scenario name in the adapter.

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Solid1/nonlinear_elasticity.prm
> +    set Write data name     = Displacement
```suggestion
    # Name of the participant in the precice-config.xml file
    set Participant name    = Solid2

    # Name of the coupling mesh in the precice-config.xml file
    set Mesh name           = Solid_mesh2

    # Name of the read data in the precice-config.xml file
    set Read data name      = Stress2

    # Name of the write data in the precice-config.xml file
    set Write data name     = Displacement2
```

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Solid1/linear_elasticity.prm
> +  set Scenario            = PF
And the same for non linear, as well as both cases of Solid2.

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/plotDisplacement.sh
> +plot "precice-Solid-watchpoint-flap_tip.log" using 1:4 title 'Top displacemement' with lines
This will probably need to become:
```suggestion
plot "precice-Solid1-watchpoint-flap_tip.log" using 1:4 title 'Top displacemement' with lines
```

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/precice-config.xml
> +    </mesh>
I think it would be better to name these meshes `Solid1_mesh` and `Solid2_mesh`. The names then follow the pattern `participant_mesh`.

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/plotDisplacement.sh
> +plot "precice-Solid-watchpoint-flap_tip.log" using 1:4 title 'Top displacemement' with lines
And also extend it for Solid2, with a different line style/color.

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/runFluid
> +# Run this script in one terminal and the execute the runSolid in another terminal.
```suggestion
# Run this script in one terminal and the execute the runSolid1 and runSolid2 in separate terminals.
```

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/runSolid1
> +# in another terminal.
```suggestion
# Run this script in one terminal and the execute the Fluid and Solid2 participants
# in separate terminals.
```

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/runSolid2
> +# in another terminal.
```suggestion
# Run this script in one terminal and the execute the Fluid and Solid1 participants
# in separate terminals.
```

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/.gitignore
> +Fluid
Somehow the Fluid case is missing from this branch. Is it due to the `.gitignore`?

2020-10-22 16:17 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/.gitignore
> +~
We also need to ignore the deal.II binaries (e.g. `linear_elasticity1`) and remove them from the repository.

2020-10-22 20:04 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Allclean
> -rm -rfv precice-run
We do need to keep this line. I see that a comment would be helpful here. These two lines are for the address files used by preCICE, after and before some version (I don't recall which one at the moment).

Please restore `rm -rfv precice-run`.

2020-10-22 20:05 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Allrun
> +    ./runSolid -linear > ${Participant3}.log  2>&1 &
These two `runSolid` should be `runSolid1` and `runSolid2`.

2020-10-22 20:07 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/precice-config.xml
> +    </mesh>
I see now that we should also rename the Fluid meshes to also follow the same pattern (sorry that I did not include them before).

2020-10-22 20:08 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/README.md
> +This tutorial is NOT YET described in the [preCICE wiki](https://github.com/precice/precice/wiki/Tutorial-for-FSI-with-deal.II-and-OpenFOAM). Have also a look into our [Notes on OpenFOAM](https://git
Let's keep this comment as "unresolved" until we also add a (new) wiki page for the tutorial.

2020-10-23 07:11 UTC, MakisH requested changes
Very good! A few more small points.

2020-10-23 07:11 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Fluid/0/U
> +FoamFile
Since we have the `0.orig/` folder, we don't need the `0/` folder: `0/` should be created from `0.orig/` when running `runFluid` or `Allrun`. You can delete it and add it to the `.gitignore`.

The "why we need this" is an OpenFOAM common practice question and I am not sure if we need it in this case. But this is concistent with the rest of the tutorials at the moment.

2020-10-23 07:11 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Fluid/constant/polyMesh/boundary
> +/*--------------------------------*- C++ -*----------------------------------*\
We should also not need the `constant/polyMesh/`, it should be created by `blockMesh` when running the `runFluid` or `Allrun` scripts.

2020-10-23 07:11 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Fluid/system/displacementProbe
> +);
Does this point correspond to one of the two flaps?

I would say we can just remove this file, since we have the watchpoints. But for consistency, we could also extend it to probe both flaps.

2020-10-23 07:11 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Fluid/system/preciceDict
> +    mesh              Fluid-Mesh-Centers1;
Probably `Fluid1-Mesh-Centers` now (same below).

2020-10-23 08:21 UTC, carme-hp commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Fluid/system/displacementProbe
> +);
pls check if current version would work to probe both flaps

2020-10-23 09:25 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/Fluid/system/displacementProbe
> +);
Actually let's just remove this file. It is only meant for debugging purposes.

2020-10-28 19:53 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +# Two Perpendicular Flap
Let's focus on the multi-coupling feature here:
```suggestion
# Multi-coupling: Two Perpendicular Flaps
```

2020-10-28 19:53 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +The setup is NOT YET shown schematically here:
todo

2020-10-28 19:53 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +SECTION TO BE UPDATE
todo

2020-10-28 19:53 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +SECTION TO BE UPDATE
todo

2020-10-28 19:56 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +
Let's add a section explaining why we are using `coupling-scheme:multi` and what are the important elements in the configuration.

2020-10-28 19:56 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +# Two Perpendicular Flap
Todo: Remember to move this file before merging.

2020-11-26 17:30 UTC, MakisH requested changes
Almost ready! (you can also change the status of the PR from "draft" to "ready")

I added a few (very picky) language and Markdown-related suggestions in the README, which already looks very good. :+1:

2020-11-26 17:30 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +This is a case with three participants: the fluid and each flap. In preCICE there are two options to couple more than two participants. A brief description of the options can be found in the wiki ( h
Two style suggestions:
- you can directly add links in the text, and it is always nice if the main message is the link (instead of e.g. writing see (link)). This makes it more easily discoverable in the page.
- avoiding forms such us "this is known as" makes the text more concise: you give the main message in fewer words. This usually increases clarity.

```suggestion
This is a case with three participants: the fluid and each flap. In preCICE, there are [two options to couple more than two participants](https://github.com/precice/precice/wiki/Multi-Coupling-Configuration). The first option a composition of bicoupling schemes, in which we must specify the exchange of data in a participant to participant manner. However, such explicit couplings schemes are not suited for fluid-structure interations [1]. Thus, in this case, we use the second option, fully-implicit multi-coupling. 
```

2020-11-26 17:30 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +This option is selected in the file 'precice-config.xml':
Think as if you are talking to your fellow CSE colleague / friend. Feel free to use more natural language, such as:
```suggestion
We can set this in our 'precice-config.xml':
```

2020-11-26 17:30 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +The participant that has the control, is the one that it is connected to all other participants. This is why we have choosen the fluid participant for this task.
No comma between subject and verb:
```suggestion
The participant that has the control is the one that it is connected to all other participants. This is why we have chosen the fluid participant for this task.
```

(also related above: add a comma before location. For example: `In preCICE, we can do this as`)

(super minor comments, overall the language is very good :smile: )

2020-11-26 17:30 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +# Multi-Coupling: Two Perpendicular Flaps
We have it mixed up, but we decided recently to switch to sentence-case for titles:

```suggestion
# Multi-coupling: Two perpendicular flaps
```

(with the uppercase after `:` to be arguable)

2020-11-26 17:30 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +Most of the coupling details are specified in the file 'precide-config.xml'.Here we estipulate the order in which we read/write data from one participant to another or how we map from the fluid to th
```suggestion
Most of the coupling details are specified in the file `precide-config.xml`. In this file, we specify the order in which we read/write data from one participant to another or how we map from the fluid to the solid's mesh. In particular, we have chosen the nearest-neighbor mapping scheme. 
```

2020-11-26 17:30 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +For the simulation of the solid participants we use the deal.ii adapter. Ind eal.ii, the geometry of the domain (where the flap located is located) is specified directly on the solver. So if we want
- Officially, deal.II is written with uppercase `II`. Similarly, always make sure to write `preCICE`, `OpenFOAM`, `CalculiX`, `FEniCS`, ...
- We use backticks for inline-code, not single quotation marks.

```suggestion
For the simulation of the solid participants we use the deal.II adapter. In deal.II, the geometry of the domain (where the is located) is specified directly on the solver. So, if we want Solid1 to be the left flap, we must specify it in the `Solid1/linear_elasticity.prm` file as follows:
```

2020-11-26 17:30 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +'set Scenario            = PFleft'
We use three backticks for code blocks:
```
set Scenario ...
```

(I think suggesting this automatically would break GitHub, sorry)

2020-11-26 17:30 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +For the linear case and in 'Solid1/nonlinear_elasticity.prm' for the nonlinear case.
```suggestion
Similarly, in `Solid1/nonlinear_elasticity.prm` for the nonlinear case. 
```

2020-11-26 17:30 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +   To start the `Fluid` participant run
```suggestion
   To start the `Fluid` participant, run:
```

2020-11-26 17:30 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/wiki.md
> +   In case we want to run the nonlinear case, simply replace the flag 'linear' by flag 'nonlinear'.
```suggestion
   In case we want to run the nonlinear case, simply replace the flag`-linear` by `-nonlinear`. 
```

2020-11-26 21:57 UTC, MakisH commented
I ran the case for 15s and the results look very reasonable: both flaps oscillate back-and-forth, with different frequencies.

Video (unlisted for now): https://youtu.be/ClZNJC3qR6M

2020-12-14 14:42 UTC, MakisH requested changes
This looks quite clean and nice now!

Dependent on https://github.com/precice/dealii-adapter/pull/39, this runs nicely in serial for the linear case. However, in parallel (with `(2 1 1)` decomposition) I get this error: https://github.com/precice/precice/issues/919 @carme-hp does it run in parallel for you with the default `(2 2 1)` and with `(2 1 1)`? I think it should be working with both.

The nonlinear case also runs nicely in serial.

2020-12-14 16:31 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/precice-config.xml
> +<?xml version="1.0"?>
Please also format this file using the (new) [XML formatter](https://github.com/precice/precice/tree/develop/tools/formatting)

2020-12-18 10:24 UTC, MakisH commented on FSI/two_flap_perp_2D/OpenFOAM-deal.II/README.md
> +This tutorial is NOT YET described in the [preCICE wiki](https://github.com/precice/precice/wiki/Tutorial-for-FSI-with-deal.II-and-OpenFOAM). Have also a look into our [Notes on OpenFOAM](https://git
Looking a bit ahead, let's replace the content of this file with the one in `wiki.md`.

Also have a look at the file https://github.com/precice/tutorials/blob/restructure/turek-hron-fsi3/README.md and see if it is following the same pattern already.

2020-12-18 13:52 UTC, MakisH approved these changes
Everything looks good! Let's merge now and we will revisit this case in the context of the tutorials restructuring. For now it looks consistent with the rest.

2020-12-19 10:06 UTC, merged