Apply new conventions on Turek Hron FSI3 case
precice/tutorials pull request #130
Opened 2020-12-14 15:00 UTC by uekerman

This PR applies all main changes from @MakisH and my restructuring discussion on the FSI3 case. This case should serve as a role model to copy from when porting other cases. 

**Summary**:

* I deleted the alternatives `OpenFOAM-CalculiX` and `OpenFOAM-FEniCS` and only kept `OpenFOAM-dealii`. The purpose of the FSI3 case is to have one proper verification case, not to show flexibility of preCICE. So, it's enough to have only one version. OpenFOAM-FEniCS never made really sense here as the structure model in FEniCS is only linear. OpenFOAM-CCX is complicated to port as the CCX adapter currently doesn't support stresses as coupling data. We wanted to keep one tutorial with stresses, however.
* The case is flattened. 
* Both solvers are called from the subdirectories, i.e. `exchange-directory=".."`. Run and clean scripts adjusted (I kept the clean script for the moment).
* Basic information is given in the README.
* Consistent names: `Stress` and `Displacement`. 

@MakisH Please have a detailed look at the README.
@DavidSCN Please try to run the case and please add a displacement plot of the actual case (with this exact mesh). You can directly push to my branch.

2020-12-14 15:38 UTC, MakisH requested changes
This adds the binary file `nonlinear_elasticity`. We need it in the `.gitingore`.

I also added a few more comments.

Overall, I like it, it only needs a bit of polishing.

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/fluid-openfoam/system/blockMeshDict_refined
> +scale 1;
I just now noticed this. @DavidSCN does this run also with openfoam.org? In the rest of the tutorials we use `convertToMeters`, which is older and (hopefully) still supported. Is the `scale` also available in more versions?

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/fluid-openfoam/system/decomposeParDict
> +        n (5 5 1);
I know this is about the restructuring, but I now saw this: we probably need a more modest number here. @DavidSCN

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +![FSI3 setup](images/tutorials-turek-hron-fsi3-setup.png)
These are the results from the previous cylinderFlap case. I guess we need a scheme with just the setup, or an image of the actual results.

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +hier auch wo mann sie herbekommt
TODO (but do we want this here?)

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +{% include important.html content="For the parabolic inflow profile, this tutorial requires groovyBC. groovyBC is part of swak4Foam, which can be cloned from [this repository](https://github.com/Unof
Bernhard Gscheider (the maintainer of swak4Foam) recommends to not use "the Git repository that is going around". I am not sure why and I cannot find the official repository at the moment (which should be a Mercurial repository on BitBucket). I guess the most official resource for now is https://openfoamwiki.net/index.php/Contrib/swak4Foam (he also maintains the OpenFOAMWiki, but apparently has not updated this page for a while, I pinged him).

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +* deal.II. For more information, have a look at the [deal.II adapter documentation](adapter-dealii-overview.html). This tutorial requires the nonlinear solid solver. Please copy the nonlinear solver
```suggestion
* deal.II. For more information, have a look at the [deal.II adapter documentation](adapter-dealii-overview.html). This tutorial requires the nonlinear solid solver. Please copy the nonlinear solver executable to this folder or make it discoverable at runtime and update the `solid-dealii/run.sh` script.
```

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +Moreover, the name of your solver might differ, depending on your OpenFOAM version. Have a look in the `fluid-openfoam/system/controlDict` file and set the appropriate solver name.
```suggestion
For older OpenFOAM versions, the solver name will differ. If you are using OpenFOAM v1712 / 5.x or older have a look in the `fluid-openfoam/system/controlDict` file and set the appropriate solver name.
```

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +There is an [open issue](https://github.com/precice/openfoam-adapter/issues/26) that leads to additional "empty" result directories when running with some OpenFOAM versions, leading to inconveniences
```suggestion
There is an [known issue](https://github.com/precice/openfoam-adapter/issues/26) that leads to additional "empty" result directories when running with some OpenFOAM versions, leading to inconveniences during post-processing. Please run the script `removeObsoleteSolvers.sh` to delete the additional files before importing your results in ParaView.
```

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +You may adjust the end time in the precice-config_*.xml, or interupt the execution earlier if you want.
```suggestion
You may adjust the end time in the `precice-config_*.xml`, or interupt the execution earlier if you want.
```

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +There is an [open issue](https://github.com/precice/openfoam-adapter/issues/26) that leads to additional "empty" result directories when running with some OpenFOAM versions, leading to inconveniences
Let's also move this to the post-processing part.

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +In the first few timesteps, many coupling iterations are required for convergence. Don't loose hope, things get better quickly.
```suggestion
In the first few timesteps, many coupling iterations are required for convergence. Don't lose hope, things get better quickly. 
```

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +Moreover, we defined a watchpoint at the flap tip and can observe the perpendicular displacement with the script `plotDisplacement.sh`.
Let's split this in three paragraphs, as things get complicated:

```suggestion
You can visualize the results of the coupled simulation using e.g. ParaView. Fluid results are in the OpenFOAM format and you may load the `Fluid.foam` file. Solid results are in VTK format.

If you want to visualize both domains with ParaView, keep in mind that the deal.II solver writes results every few timesteps, while the OpenFOAM solver writes in reference to simulated time. For this reason, make sure that you use compatible write intervals. You may also need to convert the OpenFOAM results to VTK (with the command `foamToVTK`). 

Moreover, as we defined a watchpoint at the flap tip (see `precice-config.xml`), we can plot it with gnuplot using the script `plotDisplacement.sh`.  The resulting graph shows the vertical (y) displacement of the tip of the flap.
```

(I hope that `y` is correct here)

2020-12-14 15:38 UTC, MakisH commented on turek-hron-fsi3/README.md
> +TODO: update picture according to actual used mesh.
TODO

2020-12-14 21:26 UTC, DavidSCN commented on turek-hron-fsi3/README.md
> +TODO: update picture according to actual used mesh.
I recently noticed that the foamToVTK only helps for `.org` versions. For `.com` the problem remains.

2020-12-14 21:28 UTC, DavidSCN commented on turek-hron-fsi3/README.md
> +{% include important.html content="For the parabolic inflow profile, this tutorial requires groovyBC. groovyBC is part of swak4Foam, which can be cloned from [this repository](https://github.com/Unof
2010 :sweat_smile: 
Anyway this might be interesting. Our whole FSI validation is based on the unofficial git mirror. I hope there are not that big differences for GroovyBC

2020-12-14 21:28 UTC, DavidSCN commented on turek-hron-fsi3/README.md
> +![FSI3 setup](images/tutorials-turek-hron-fsi3-setup.png)
I can probably provide some more recent.

2020-12-14 21:50 UTC, DavidSCN commented
> Please try to run the case and please add a displacement plot of the actual case (with this exact mesh). You can directly push to my branch.

I guess you mean the most refined mesh on the Fluid side? Or rather the exact given mesh?

2020-12-15 07:39 UTC, DavidSCN commented on turek-hron-fsi3/fluid-openfoam/system/blockMeshDict_refined
> +scale 1;
The keyword `scale` is indeed not included in the most recent .org versions. I removed `convertToMeters` because .com raises an information in the beginning 'this keyword is deemed to be .. month old", not sure about the exact number but it was very long and it seems outdated for me.

2020-12-15 07:41 UTC, DavidSCN commented on turek-hron-fsi3/fluid-openfoam/system/decomposeParDict
> +        n (5 5 1);
I would not choose a more moderate number here since the most refined mesh requires quite some resources. This way, we make the computational cost more clear to the user.

2020-12-15 07:49 UTC, MakisH commented on turek-hron-fsi3/README.md
> +{% include important.html content="For the parabolic inflow profile, this tutorial requires groovyBC. groovyBC is part of swak4Foam, which can be cloned from [this repository](https://github.com/Unof
More information: https://twitter.com/swakPyFoam/status/1338566289913163777
Let's use both links and clarify that we used the Git repository, but it is unofficial.

2020-12-15 07:51 UTC, MakisH commented on turek-hron-fsi3/fluid-openfoam/system/blockMeshDict_refined
> +scale 1;
Can we actually remove it completely? The default should be 1 anyway.

2020-12-15 07:53 UTC, MakisH commented on turek-hron-fsi3/fluid-openfoam/system/decomposeParDict
> +        n (5 5 1);
ok, then @uekerman can you maybe add a note in the README.md that the parallel case runs on 25 processes by default, due to the high mesh size?

2020-12-15 07:54 UTC, DavidSCN commented on turek-hron-fsi3/precice-config.xml
> -      <extrapolation-order value="2" />
I just noticed that the number of coupling iterations is a little bit too high according to my expectation. I can of xourse provide the `iterations` file after the run has finished. Are you sure you would like to remove the extrapolation. I once had a comparison and the extrapolation helped to lower the iterations.

2020-12-15 07:59 UTC, DavidSCN commented on turek-hron-fsi3/fluid-openfoam/system/blockMeshDict_refined
> +scale 1;
For .com it works without any keyword, just tested it.

2020-12-15 08:02 UTC, DavidSCN commented
Another deal.II specific point: since we start the solver now from sub-directories, the log, result and parameter files are all in one directory. We should probably use a specific directory for the solution files.

2020-12-15 09:09 UTC, uekerman commented
> > Please try to run the case and please add a displacement plot of the actual case (with this exact mesh). You can directly push to my branch.
> 
> I guess you mean the most refined mesh on the Fluid side? Or rather the exact given mesh?

The results we show here should coincide with the mesh that we provide. 
Which mesh do we currently provide? Compared to the results in the OpenFOAM adapter paper. The mesh should be fine enough to give good results (compute time is not an issue for this case).

2020-12-15 09:16 UTC, DavidSCN commented
> > > Please try to run the case and please add a displacement plot of the actual case (with this exact mesh). You can directly push to my branch.
> > 
> > 
> > I guess you mean the most refined mesh on the Fluid side? Or rather the exact given mesh?
> 
> The results we show here should coincide with the mesh that we provide.
> Which mesh do we currently provide? Compared to the results in the OpenFOAM adapter paper. The mesh should be fine enough to give good results (compute time is not an issue for this case).

We provide all meshes (refinement level one to three). The default mesh (20k cells) is the most coarse one, the most refined (45k cells) is called blockMesh_double_refined. If we just show a plot of the y displacement from 0 up to 15 sec, differences will probably only be noticeable in terms of the absolute time.

2020-12-15 09:24 UTC, uekerman commented on turek-hron-fsi3/README.md
> +![FSI3 setup](images/tutorials-turek-hron-fsi3-setup.png)
That would be good. If we show physical results they should coincide 100% with the case. Alternative would be to only show a setup image. Please directly push to the source branch.

2020-12-15 09:25 UTC, uekerman commented on turek-hron-fsi3/README.md
> +hier auch wo mann sie herbekommt
That was just an Easter egg :smile:

2020-12-15 09:28 UTC, uekerman commented
> We provide all meshes (refinement level one to three). 

Ah ok. I'll add a note in the README.

> The default mesh (20k cells) is the most coarse one, the most refined (45k cells) is called blockMesh_double_refined. If we just show a plot of the y displacement from 0 up to 15 sec, differences will probably only be noticeable in terms of the absolute time.

Yes, let's keep the 20k as default and let's then add all picture generated from that one.

2020-12-15 09:35 UTC, DavidSCN commented
Perfect, 
maybe also add a note for the mapping for the most refined case, where it is probably better to replace the global rbf by sth like:
```xml
        <mapping:rbf-compact-tps-c2 direction="read" from="Fluid-Mesh-Centers" to="Solid-Mesh" support-radius="0.011" constraint="consistent" />
```

2020-12-15 09:35 UTC, uekerman commented on turek-hron-fsi3/README.md
> +{% include important.html content="For the parabolic inflow profile, this tutorial requires groovyBC. groovyBC is part of swak4Foam, which can be cloned from [this repository](https://github.com/Unof
I added both links. We should add that we used the Git repo in the paper, not here. Anyway, I guess not too much can go wrong with a parabolic inflow profile.

2020-12-15 09:38 UTC, uekerman commented on turek-hron-fsi3/README.md
> +There is an [open issue](https://github.com/precice/openfoam-adapter/issues/26) that leads to additional "empty" result directories when running with some OpenFOAM versions, leading to inconveniences
done

2020-12-15 09:40 UTC, uekerman commented on turek-hron-fsi3/README.md
> +You may adjust the end time in the precice-config_*.xml, or interupt the execution earlier if you want.
I also removed the `_*`.

2020-12-15 09:51 UTC, uekerman commented on turek-hron-fsi3/README.md
> +TODO: update picture according to actual used mesh.
Which problem are you referring to exactly? The non-synchronized files? Could you make a text suggestion? (or directly push to the source branch).

2020-12-15 09:53 UTC, uekerman commented on turek-hron-fsi3/precice-config.xml
> -      <extrapolation-order value="2" />
OK, let's keep it for the FSI3 (but let's not use it for the perpendicular flap). I am just always worried that users copy the file. Extrapolation definitely has robustness issues.

2020-12-15 12:45 UTC, DavidSCN commented on turek-hron-fsi3/README.md
> +TODO: update picture according to actual used mesh.
Yes, the time sync. Since OpenFOAM shows the exact motion of the structure, all in all it is not such a big problem. I have not yet a proper solution for this problem, it might be helpful if you could upload a synchronized nutils result file in https://github.com/precice/dealii-adapter/issues/33

2020-12-16 07:57 UTC, MakisH commented on turek-hron-fsi3/fluid-openfoam/system/blockMeshDict_refined
> +scale 1;
Do you have any .org version installed at the moment? If it also works there without a keyword, let's remove it.

2020-12-17 12:44 UTC, uekerman commented on turek-hron-fsi3/README.md
> +TODO: update picture according to actual used mesh.
OK, but I would exclude the time synch problem from this PR. I will add files in the dealii issue. TODO here is done.

2020-12-17 14:07 UTC, MakisH approved these changes
Some minor things to improve. Other than that, looks very good!

2020-12-17 14:07 UTC, MakisH commented on turek-hron-fsi3/README.md
> +In `fluid-openfoam/system/`, we provide three different fluid meshes:
How is the user supposed to select a different mesh?

2020-12-17 14:07 UTC, MakisH commented on turek-hron-fsi3/README.md
> +
```suggestion

Before running the simulation again, you may want to cleanup any result files using the script `Allclean`.
```

2020-12-17 15:15 UTC, DavidSCN commented on turek-hron-fsi3/fluid-openfoam/system/blockMeshDict_refined
> +scale 1;
Checked it now with OF7 and OF8: both versions work with `scale` and without any keyword.

2020-12-17 15:53 UTC, uekerman commented on turek-hron-fsi3/fluid-openfoam/system/blockMeshDict_refined
> +scale 1;
I removed it

2020-12-17 15:54 UTC, merged