Restructure quickstart
precice/tutorials pull request #145
Opened 2021-01-08 12:19 UTC by DavidSCN

Open TODOs:
- [ ] update README
- [ ] update image (essentially an older TODO)

2021-01-08 12:21 UTC, DavidSCN commented on quickstart/solid-cpp/run.sh
> +fi
Discussion:
Should we also include the `cmake` and `make` here or should we refer to the README as it is currently done here.

2021-01-08 12:55 UTC, uekerman commented on quickstart/solid-cpp/run.sh
> +fi
In my opinion, it's good as it is.

2021-01-28 08:57 UTC, DavidSCN commented
Ready for review, but still in draft in order to avoid an accidental merge.

2021-03-03 10:40 UTC, uekerman commented
Please remember to not merge this before everything else is merged. Otherwise we change the content here: https://www.precice.org/quickstart.html
The webpage points to the `restructure` branch.

2021-03-10 09:34 UTC, MakisH requested changes
A few minor comments, mostly very picky changes in the formulations and a rather important bug prevention in the scripts.

I ran the case and I observed that:
- :heavy_check_mark: The case is running
- :x: The `removeObsoleteFolders.sh` needs to remove the `cd Fluid` and the `cd ..`.
- :heavy_check_mark: The `plotDisplacement.sh` works
- :heavy_check_mark: ParaView works.
- :grey_question: I still see a kind-of "explosion"  in the second half of the simulation (higher-frequency oscillation). Maybe we could add a note that this is expected and why.
- :x: `clean.sh` needs a few fixes (see review)

Looks very nice already! :rocket:

2021-03-10 09:34 UTC, MakisH commented on quickstart/README.md
> +This tutorial deals with a fluid-structure-interaction problem. The fluid part of the simulation is computed using OpenFOAM and the rigid body motion is a rigid body model written in c++ with only a
```suggestion
This tutorial deals with a fluid-structure interaction problem. The fluid part of the simulation is computed using OpenFOAM and the rigid body motion is a rigid body model (implemented in C++) with only a single degree of freedom, namely the deflection angle of the flap in the channel. The rigid body is fixed in the origin at (0,0) and the force exerted by the fluid on the rigid body structure causes an oscillatory rotation of the body. The simulation runs for 2.5 seconds. In order to gain more control over the rigid body oscillation, a rotational spring is applied at the rigid body origin. After 1.5 seconds we increase the spring constant by a factor of 8 to stabilize the coupled problem. Feel free to modify these parameters (directly in `rigid_body_solver.cpp`) and increase the simulation time (in `precice-config.xml`).
```

2021-03-10 09:34 UTC, MakisH commented on quickstart/README.md
> +Before starting the coupled simulation, the `rigid_body` solver needs to be compiled using `cmake`. You can run the following commands from this directory to build the `rigid_body` solver
```suggestion
Before starting the coupled simulation, the `rigid_body` solver needs to be built using CMake. You can run the following commands from this directory to build the `rigid_body_solver.cpp`
```

2021-03-10 09:34 UTC, MakisH commented on quickstart/README.md
> +cd Solid && cmake . && make
```suggestion
cd solid-cpp && cmake . && make
```

2021-03-10 09:34 UTC, MakisH commented on quickstart/README.md
> +You may run the two simulations in two different terminals and watch their output on the screen by using the `run.sh` scripts (or `run.sh -parallel` for OpenFOAM) located in each participant director
```suggestion
You may run the two simulations in two different terminals and watch their output on the screen using the `run.sh` scripts (or `run.sh -parallel`, option only available for OpenFOAM) located in each participant directory. You can cleanup the simulation using `clean.sh`.
```

2021-03-10 09:34 UTC, MakisH commented on quickstart/README.md
> +You can visualize the simulation results of the `Fluid` participant using paraView (use paraFoam to trigger the OpenFOAM native reader or load the (empty) file `Fluid.foam` into paraView). The rigid
```suggestion
You can visualize the simulation results of the `Fluid` participant using ParaView (use `paraFoam` to trigger the OpenFOAM native reader or load the (empty) file `Fluid.foam` into ParaView). The rigid body doesn't generate any readable output files, but the motion can be observed in the OpenFOAM data. In addition, one could visualize the coupling meshes including the exchanged coupling data. preCICE generates the relevant files during the simulation and stores them in the directory `coupling-meshes`. In order to visualize the results, load the VTK files in ParaView and apply a `Glyph` filter. Depending on the specific ParaView version, you might additionally need to disable the `ScaleArray` option by selecting `No scale array`, since the exchanged data might be inappropriate for a scaling operation. You can further add a `Warp By Vector` filter with `Displacements` to deform the coupling data.
```

2021-03-10 09:34 UTC, MakisH commented on quickstart/README.md
> +
It would be nice to have a screenshot of ParaView with the options and the visualization here.

2021-03-10 09:34 UTC, MakisH commented on quickstart/README.md
>  {% include important.html content="We are currently working on a really nice getting started page. Till then, we hope these tips already help." %}
```suggestion
```
This is the really nice getting started page ;-) We can always improve it further, but this disclaimer can be removed already.

2021-03-10 09:34 UTC, MakisH commented on quickstart/clean.sh
>      echo "Cleaning Solid case"
```suggestion
    echo "Cleaning the solid-cpp case"
```

2021-03-10 09:34 UTC, MakisH commented on quickstart/clean.sh
>      cleanCase
Let's add a similar message as with the clean case here. Reason: the `cleanCase` script may not be available (e.g. the user forgot to load the OpenFOAM environment).

```suggestion
    echo "Cleaning the fluid-openfoam case"
    cleanCase
```

2021-03-10 09:34 UTC, MakisH commented on quickstart/clean.sh
> +    # Output files for preCICE versions before 1.2:
We don't really need the "before 1.2" files anymore. Removing these would make the scripts shorter/cleaner.

2021-03-10 09:34 UTC, MakisH commented on quickstart/precice-config.xml
Just to confirm: this case uses the separation between face nodes and face centers. Is there a particular reason for not using the new 2D mode with the face centers everywhere?

2021-03-10 15:22 UTC, DavidSCN commented on quickstart/README.md
>      ```
Maybe we should use placeholder, e.g. x.y.z for the version in order to avoid this problem in the future,

2021-03-10 15:24 UTC, DavidSCN commented on quickstart/README.md
> +6. [Couple OpenFOAM with a c++ rigid body solver](https://github.com/precice/tutorials/quickstart).
... you mean the whole preCICE project, including adapters, tutorials and the documentation? :ok_hand:

2021-03-10 15:38 UTC, MakisH commented on quickstart/README.md
> +6. [Couple OpenFOAM with a c++ rigid body solver](https://github.com/precice/tutorials/quickstart).
This is what we have with the VM. Here I am mainly commenting on "we need versioning in the tutorials". But that's for another time.

2021-03-10 15:53 UTC, DavidSCN commented on quickstart/README.md
> +```
I would still vote for a repository global `gitignore` as already discussed [here](https://github.com/precice/tutorials/pull/154#issuecomment-792590007), but if all of you are happy with case specific one, we need to add one in every directory,

2021-03-10 16:08 UTC, DavidSCN commented on quickstart/README.md
> +This tutorial deals with a fluid-structure interaction problem. The fluid part of the simulation is computed using OpenFOAM and the rigid body motion is a rigid body model (implemented in C++) with o
> A few minor comments, mostly very picky changes in the formulations and a rather important bug prevention in the scripts.
> 
> I ran the case and I observed that:
> 
>     * heavy_check_mark The case is running
> 
>     * x The `removeObsoleteFolders.sh` needs to remove the `cd Fluid` and the `cd ..`.
> 
>     * heavy_check_mark The `plotDisplacement.sh` works
> 
>     * heavy_check_mark ParaView works.
> 
>     * grey_question I still see a kind-of "explosion"  in the second half of the simulation (higher-frequency oscillation). Maybe we could add a note that this is expected and why.
> 
>     * x `clean.sh` needs a few fixes (see review)
> 
> 
> Looks very nice already! rocket

The `clean.sh` and `removeFolders` should be fine now. In case the following figure is "exploding" for you: that's intended. It should also be clear when reading through the introduction here.
![](https://user-images.githubusercontent.com/33414590/110659722-1ec89600-81c3-11eb-94a1-ef9cad784c54.png)

2021-03-10 16:10 UTC, MakisH commented on quickstart/README.md
> +```
Then you can leave it as it is and I will work on it later. Related issue: https://github.com/precice/tutorials/issues/87

2021-03-10 18:15 UTC, MakisH requested changes
A few more minor changes in the README.md (sorry, I only saw them now)

2021-03-10 18:15 UTC, MakisH commented on quickstart/README.md
>  ## What's next?
I just noticed that this section also needs some updates:
- Move the tutorials link from the wiki to the website
- Use the new YouTube channel link: https://www.youtube.com/c/preCICECoupling/
- Replace the "register to our workshop" link to a more general call to come to a workshop: https://www.precice.org/community.html

2021-03-10 18:15 UTC, MakisH commented on quickstart/README.md
> +### Building the `rigid_body` participant
Technically, this is something independent of the coupling, so we should refer to this as "solver" or "code". I also think we could avoid the inline code (`rigid_body`), since this is not the exact name,


```suggestion
### Building the rigid body solver
```

2021-03-10 18:15 UTC, MakisH commented on quickstart/README.md
> +Before starting the coupled simulation, the `rigid_body` solver needs to be built using CMake. You can run the following commands from this directory to build the `rigid_body_solver.cpp`
Same here: 
```suggestion
Before starting the coupled simulation, the rigid body solver needs to be built using CMake. You can run the following commands from this directory to build the `rigid_body_solver.cpp`
```

2021-03-10 18:15 UTC, MakisH commented on quickstart/README.md
> +You can visualize the simulation results of the `Fluid` participant using ParaView (use `paraFoam` to trigger the OpenFOAM native reader or load the (empty) file `Fluid.foam` into ParaView). The rigi
Good catch renaming the variables in the `precice-config.xml`. We also need to update them here then:
```suggestion
You can visualize the simulation results of the `Fluid` participant using ParaView (use `paraFoam` to trigger the OpenFOAM native reader or load the (empty) file `Fluid.foam` into ParaView). The rigid body doesn't generate any readable output files, but the motion can be observed in the OpenFOAM data. In addition, one could visualize the coupling meshes including the exchanged coupling data. preCICE generates the relevant files during the simulation and stores them in the directory `coupling-meshes`. In order to visualize the results, load the VTK files in ParaView and apply a `Glyph` filter. Depending on the specific ParaView version, you might additionally need to disable the `ScaleArray` option by selecting `No scale array`, since the exchanged data might be inappropriate for a scaling operation. You can further add a `Warp By Vector` filter with `Displacement` to deform the coupling data.
```

(anywhere else?)

2021-03-11 07:06 UTC, DavidSCN commented on quickstart/README.md
> +There is an [open issue](https://github.com/precice/openfoam-adapter/issues/26) that leads to additional "empty" result directories when running with some OpenFOAM versions, leading to inconveniences
I agree, it will just confuse newcomer.

2021-03-11 07:24 UTC, DavidSCN commented on quickstart/README.md
>  ## What's next?
Good catch (though you marked the wrong lines here).
I added now 'Meet our community and added the community link.

2021-03-11 07:57 UTC, DavidSCN commented on quickstart/README.md
> +
Done

2021-03-11 07:57 UTC, DavidSCN commented
I added now a result figure. Feel free to comment on it. Other than that, the PR should be ready.

2021-03-11 09:04 UTC, MakisH approved these changes

2021-03-11 09:05 UTC, MakisH commented
> Please remember to not merge this before everything else is merged. Otherwise we change the content here: https://www.precice.org/quickstart.html
> The webpage points to the `restructure` branch.

Just a reminder

2021-03-11 09:22 UTC, MakisH commented on quickstart/README.md
>  ## What's next?
I marked the first line that GitHub allowed me to mark (the `## What's next`) :confused:

2021-03-11 09:38 UTC, DavidSCN commented on quickstart/README.md
>  ## What's next?
Yes, I realized it too late since the line has not been changed. For the record: you can mark multiple lines as well by holding the 'plus' button.

2021-03-11 10:04 UTC, MakisH commented on quickstart/README.md
>  ## What's next?
The problem I faced is actually that the GitHub review tool does not let you mark a line that is not in a diff chunk affected by the PR. The `What's next?` was directly below the above changes, so it allowed me to mark this, but not the next lines.

2021-04-12 07:39 UTC, DavidSCN commented
@MakisH merging `develop` was a bit of a challenge. but you can cross-review the cleaning/running now as discussed.

2021-04-12 08:45 UTC, MakisH commented
I looked at the commit with the cleaning/running and the latest state and it looks good :+1:.

2021-04-12 13:34 UTC, merged