Restructure flap_perp FSI case
precice/tutorials pull request #146
Opened 2021-01-11 14:21 UTC by DavidSCN

Closes #135 
I have not yet adjusted the physical parameters and not yet tested any relevant cases. Here is an overview of what I expect to work and open TODOs:

- [ ]  `fluid-nutils` There are currently two different meshes in use for reading and writing. We can only use one mesh here (I would prefer this option at least). I suggest we leave out the cell centers and go with the Gauss-points. Also,  the pythin binding path is somehow wrong @uekerman 
- [x] `fluid-openfoam` 
- [ ] `fluid-su2` Biggest TODOs left. We need to support absolute Displacement data and a more flexible configuration. Related to precice/su2-adapter#17, WIP
- [ ] `solid-calculix` I copied the meshes from #143 thanks to @IshaanDesai, still waiting for precice/calculix-adapter#49 to be merged
- [ ] `solid-dealii` we need to support force data reading, as described in precice/dealii-adapter#41, WIP. Open to discuss, do we also want to support DisplacementDeltas? The information is already there and it would ensure compatibility to other adapter
- [x] `solid-fenics` 

Apart from that, what is our `clean.sh`script supposed to clean? I just want to mention that cleaning all cases might be undesired and deletes a lot. Maybe we should require some cleaning target specification.

2021-01-13 07:50 UTC, uekerman commented on perpendicular-flap/fluid-nutils/nsale.py
> +sys.path.insert(0, precice_python_adapter_root)
You can remove these lines. This code still used an older version of the Python bindings.
```suggestion
```

2021-01-13 07:50 UTC, uekerman commented on perpendicular-flap/fluid-nutils/nsale.py
> +import os, sys
```suggestion
```

2021-01-13 07:52 UTC, uekerman commented
> There are currently two different meshes in use for reading and writing. We can only use one mesh here (I would prefer this option at least). I suggest we leave out the cell centers and go with the Gauss-points. 

Good point. Didn't have this on my radar. Yes, let's go with the GPs then.

> Also, the pythin binding path is somehow wrong 

See comments above

2021-01-13 07:57 UTC, uekerman commented
> solid-dealii: Do we also want to support DisplacementDeltas? The information is already there and it would ensure compatibility to other adapter

In my opinion this is not strictly necessary. We don't need it here. I would definitely keep it out for the moment. We could still do this later.

> Apart from that, what is our clean.shscript supposed to clean? I just want to mention that cleaning all cases might be undesired and deletes a lot. Maybe we should require some cleaning target specification.

Let's clean everything for the moment. We anyway wanted to revisited the cleaning in #133. Let's discuss this then / there.

2021-01-19 11:54 UTC, DavidSCN commented
Nutils output:
```
  File "nsale.py", line 8, in <module>
    @function.replace
AttributeError: module 'nutils.function' has no attribute 'replace'
```
I think I have an obvious issue I am not aware of?

2021-01-20 15:15 UTC, MakisH requested changes
I like how this looks a lot red! :smile: A lot of hard work!

See a few comments below. I have not yet tried to run the cases. The target branch is correct.

2021-01-20 15:15 UTC, MakisH commented on perpendicular-flap/fluid-openfoam/system/preciceDict
> -  Interface2
Nice side-effect of the new 2D mode!

2021-01-20 15:15 UTC, MakisH commented on perpendicular-flap/README.md
> +
As a user, I would really like here a table that shows which config options of each solver compare to these parameters, as they know where to start experimenting from. It would also be very helpful for us to verify what we are doing and to maintain these files in the future.

@uekerman what do you think?

2021-01-20 15:15 UTC, MakisH commented on perpendicular-flap/precice-config.xml
> +    <data:vector name="Displacements" />
According to our [new naming conventions](https://www.precice.org/community-contribute-to-precice.html#contributing-tutorials), these should be in singular: `Force` and `Displacement`.

2021-01-20 15:15 UTC, MakisH commented on perpendicular-flap/solid-calculix/config.yml
> +participants:
Nice side-effect from starting the solvers from their case folders: `config.yml` (the adapter's config) does not need to be in the parent folder anymore!

2021-01-20 15:15 UTC, MakisH commented on perpendicular-flap/solid-dealii/linear_elasticity.prm
> +  set mu              = 1538461.539
Are these (very precise) values in accordance to the other Structure solvers? I guess we need to communicate these parameter changes to the users, to save them from surprises.

2021-01-20 15:18 UTC, uekerman commented on perpendicular-flap/README.md
> +
Could be nice, yes. I am not sure if this results in meaningful entries for every solver, but we could give it a shot?

2021-01-20 15:19 UTC, uekerman commented on perpendicular-flap/README.md
> +
We could at least always mention the file where to find the option for each solver.

2021-01-20 15:23 UTC, DavidSCN commented on perpendicular-flap/solid-dealii/linear_elasticity.prm
> +  set mu              = 1538461.539
They are. The other solver use E and nu ass parameter instead of the Lame constants but they are equivalent in terms of the information.
What do you propose?

2021-01-20 15:43 UTC, MakisH commented on perpendicular-flap/solid-dealii/linear_elasticity.prm
> +  set mu              = 1538461.539
If you are happy, I am happy! :smile: I just wanted to confirm.

2021-01-20 15:44 UTC, MakisH commented on perpendicular-flap/solid-dealii/linear_elasticity.prm
> +  set mu              = 1538461.539
For the "communicate these parameter changes to the users", I mean to remember to mention it when we announce the restructuring.

2021-01-20 16:05 UTC, DavidSCN commented on perpendicular-flap/README.md
> +As we defined a watchpoint at the flap tip (see `precice-config.xml`), we can plot it with gnuplot.  The resulting graph shows either the displacement or the force at the flap tip.
We don't have a plotDisplacement script here since the location of the watchpoint data depends on the selected case. We could add one using a command line argument or refer to the fsi3 script as an exemplary case.

2021-01-20 16:07 UTC, DavidSCN commented on perpendicular-flap/clean.sh
> +clean_case(){
If you have already a solution in mind, feel free to modify this script or add whatever you have in mind. However, we have a separate script in the turek cases as well so it would be ok to go with this solution at the moment and wait for #133 in the long run.

2021-01-20 16:08 UTC, DavidSCN commented on perpendicular-flap/fluid-openfoam/constant/transportProperties
> +nu              nu [ 0 2 -1 0 0 0 0 ] 1;
Will do that

2021-01-20 16:09 UTC, DavidSCN commented on perpendicular-flap/fluid-openfoam/system/preciceDict
> -  Interface2
Indeed it simplifies some things.

2021-01-20 16:11 UTC, DavidSCN commented on perpendicular-flap/fluid-openfoam/system/blockMeshDict
> +    ($x0 $z0   $w )         // 0
It was differently before in different cases. I will add a comment on how it is in the current setting.

2021-01-20 16:14 UTC, DavidSCN commented on perpendicular-flap/README.md
> +
Will certainly lead to duplication in the docs. I would prefer to add this information in the (linked) adapter docs,

2021-01-20 16:14 UTC, DavidSCN commented on perpendicular-flap/precice-config.xml
> +    <data:vector name="Displacements" />
..will do that :sob:

2021-01-20 16:15 UTC, DavidSCN commented on perpendicular-flap/solid-calculix/config.yml
> +participants:
I wasn't even aware of this advantage.

2021-01-20 16:16 UTC, DavidSCN commented on perpendicular-flap/solid-dealii/linear_elasticity.prm
> +  set mu              = 1538461.539
Alright. I added the comment in the description above.
I should probably remove some digits... the precision is not required.

2021-01-21 22:30 UTC, MakisH commented on perpendicular-flap/README.md
> +
Then let's add some information about the usually interesting variables in each adapter's documentation. This will mainly be useful for us: I never remember what to change in which file in case of CalculiX, for example.

I could then resolve this conversation by comparing the different parameters for each case using the documentation.

2021-01-21 22:34 UTC, MakisH commented on perpendicular-flap/README.md
> +As we defined a watchpoint at the flap tip (see `precice-config.xml`), we can plot it with gnuplot.  The resulting graph shows either the displacement or the force at the flap tip.
The "vision" would be to have a general tool that can plot watchpoints in the `tools/` folder.

Until then, let's provide a similar script here. Gnuplot is not very intuitive and it would be relatively easy for us to make the user's life much easier in getting first results.

2021-01-21 22:35 UTC, MakisH commented on perpendicular-flap/clean.sh
> +clean_case(){
Yes, that's what I mean: let's keep this one for now.

2021-01-25 09:34 UTC, IshaanDesai commented
I compared the results of SU2-FEniCS and SU2-CalculiX runs for the perpendicular flap and the comparison looks like:
![linedatacompare](https://user-images.githubusercontent.com/44898158/105687092-566fcd00-5ef8-11eb-807f-59a21dfa77f1.png)

The results are clearly different. The corresponding case setups can be found here: https://github.com/precice/tutorials/tree/formatSU2-CCX-tutorial/FSI/flap_perp_2D
I am purposely resolving this issue on the branch: https://github.com/precice/tutorials/tree/formatSU2-CCX-tutorial to avoid pushing an inconsistent scenario within the restructuring.

2021-01-25 19:38 UTC, BenjaminRodenberg commented
I'm attaching a picture of current setup + physical parameters. I hope that this agrees with what you are doing here. If not: please shout out loud :speaker: :hear_no_evil: 

![image](https://user-images.githubusercontent.com/5740604/105756311-b98b4f00-5f4c-11eb-939d-1ea3fdef499a.png)

I think the `z = 1` is still an open topic (see #108). What "thickness" do you use here?

2021-01-25 20:32 UTC, BenjaminRodenberg reviewed
Comments mostly related to #108

2021-01-25 20:32 UTC, BenjaminRodenberg commented on perpendicular-flap/README.md
> +The simulated flow domain is 6 units long (x) and 4 units tall (y). The flap is located at the center of the bottom (x=0) and is 1 unit tall (y) and 0.1 units long (x). We set the fluid density $\{rh
```suggestion
The simulated flow domain is 6 units long (x) and 4 units tall (y). The flap is located at the center of the bottom (x=0) and is 1 unit long (y) and 0.1 units thick (x). We set the fluid density $\{rho}_F= 1.0kg/m^{3}$, the kinematic viscosity $\{nu}_f= 1.0m^{2}/s$, the solid density $\{rho}_s= 3.0·10^{3}kg/m^{3}$, the Young’s modulus to $E= 4.0·10^{6} kg/ms^{2}$and the Poisson ratio $\{nu}_s = 0.3$. On the left boundary a constant inflow profile in x-direction of 10m/s is prescribed. The right boundary is an outflow and the top and bottom of the channel as well asthe surface of the flap are no-slip walls.
```

Having a beam that is 0.1 "long" while being 1.0 "tall" sounds strange to me. I think adding annotations for the dimensions would help a lot. You can then provide a table with the numbers or refer to the labels in the test  (L = 6, H = 4, l = 1, t = 0.1, ...). I can provide a picture, if you need one.

2021-01-25 20:41 UTC, IshaanDesai commented on perpendicular-flap/fluid-su2/euler_config_coupled.cfg
>  MARKER_INLET= ( inlet, 288.6, 101400.0, 1.0, 0.0, 0.0 )
Here the inlet velocity for SU2 is 1.0 but in the README it says 10 m/s. What is the intended value? [This study](https://github.com/precice/tutorials/issues/150#issuecomment-767090870) shows that for SU2, the inlet velocity of 1.0 m/s is favourable.

2021-01-25 20:44 UTC, IshaanDesai commented on perpendicular-flap/solid-calculix/flap.inp
> + 4000000, 0.3
[This study] indicates that for SU2 - CalculiX combination, the Elasticity modulus of value 1E+6 also gives favourable results and is more suitable for combination with FEniCS

2021-01-25 20:44 UTC, IshaanDesai commented on perpendicular-flap/solid-calculix/flap.inp
>  *DYNAMIC
```suggestion
*DYNAMIC, ALPHA=0.0
```

2021-01-25 20:46 UTC, IshaanDesai commented on perpendicular-flap/solid-fenics/perp-flap.py
> +u_ref = Function(V)
```suggestion
```

2021-01-25 20:46 UTC, IshaanDesai commented on perpendicular-flap/solid-fenics/perp-flap.py
> +        u_ref = u_n.copy()
```suggestion
```

2021-01-25 20:48 UTC, IshaanDesai commented on perpendicular-flap/solid-fenics/perp-flap.py
> +    precice.write_data(u_delta)
```suggestion
    precice.write_data(u_np1)
```

2021-01-25 20:49 UTC, IshaanDesai reviewed
Some suggestions regarding physical parameters and changes to the FEniCS script to calculate `Displacements` instead of `DisplacementDeltas`

2021-01-26 08:27 UTC, DavidSCN commented on perpendicular-flap/README.md
> +
I think this would be a bigger task. Do you want to open an issue on this?

2021-01-26 08:30 UTC, DavidSCN commented on perpendicular-flap/fluid-openfoam/system/blockMeshDict
> +w 0;
I understand, let me clean this up.

2021-01-26 08:42 UTC, DavidSCN commented
> I'm attaching a picture of current setup + physical parameters. I hope that this agrees with what you are doing here. If not: please shout out loud speaker hear_no_evil
> 
> ![image](https://user-images.githubusercontent.com/5740604/105756311-b98b4f00-5f4c-11eb-939d-1ea3fdef499a.png)
> 
> I think the `z = 1` is still an open topic (see #108). What "thickness" do you use here?

@BenjaminRodenberg I like the figure very much. The current README uses the preCICE wiki overview of this case, which is certainly less informative. Regarding the 'z' topic: for OpenFOAM, we must use z=1, otherwise you're doing things wrong (in conmbination with force data). IIRC, it doesn't really matter for CalculiX, but we still use z=1. Since this is a tutorial, we should definitely use z=1 in order to prevent errors (in case of a different setup) and to show some best practice.

2021-01-26 08:43 UTC, DavidSCN commented on perpendicular-flap/README.md
> +The simulated flow domain is 6 units long (x) and 4 units tall (y). The flap is located at the center of the bottom (x=0) and is 1 unit tall (y) and 0.1 units long (x). We set the fluid density $\{rh
Resolved below (since they are on the same line).

2021-01-26 08:44 UTC, DavidSCN commented on perpendicular-flap/solid-calculix/flap.inp
> + 4000000, 0.3
See the comment in #150

2021-01-26 08:46 UTC, DavidSCN commented on perpendicular-flap/solid-calculix/flap.inp
>  *DYNAMIC
Why should we change the temporal discretization here?

2021-01-26 08:48 UTC, DavidSCN commented on perpendicular-flap/fluid-openfoam/system/blockMeshDict
> +    ($x3  $z2 1)         // 23
See https://github.com/precice/tutorials/pull/146#issuecomment-767392389

2021-01-26 09:11 UTC, MakisH commented
Just so that somebody asks this: shouldn't we wait for the paper to be published before using the new figures here?

2021-01-26 09:18 UTC, DavidSCN commented on perpendicular-flap/solid-dealii/linear_elasticity.prm
> +  set mu              = 1538461.539
Done

2021-01-26 09:36 UTC, DavidSCN commented on perpendicular-flap/README.md
> +As we defined a watchpoint at the flap tip (see `precice-config.xml`), we can plot it with gnuplot.  The resulting graph shows either the displacement or the force at the flap tip.
Done

2021-01-26 09:37 UTC, DavidSCN commented on perpendicular-flap/precice-config.xml
> +    <data:vector name="Displacements" />
Done.

2021-01-26 09:49 UTC, DavidSCN commented on perpendicular-flap/fluid-openfoam/system/blockMeshDict
> +    ($x3  $z2 1)         // 23
Done

2021-01-26 09:50 UTC, DavidSCN commented on perpendicular-flap/fluid-openfoam/system/blockMeshDict
> +w 0;
Done, I selected now `z0` and `z1` for consistency reason. Feel free to reopen a discussion if you still have concerns.

2021-01-26 09:50 UTC, IshaanDesai commented on perpendicular-flap/solid-calculix/flap.inp
>  *DYNAMIC
Setting `ALPHA=0` makes the temporal discretization scheme in CCX consistent with the Newark-beta-method used in the FEniCS structural solver. I must concede though that this change does not change the results of the simulations.

2021-01-26 09:53 UTC, IshaanDesai commented on perpendicular-flap/solid-calculix/flap.inp
> + 4000000, 0.3
Okay, if other values are more preferred then I can test the FEniCS case accordingly

2021-01-26 09:55 UTC, DavidSCN commented on perpendicular-flap/solid-calculix/flap.inp
> + 4000000, 0.3
Appreciated :+1:

2021-01-26 09:58 UTC, DavidSCN commented on perpendicular-flap/solid-calculix/flap.inp
>  *DYNAMIC
I think we should select a parameter which works best for CalculiX, we don't really require a consistent time discretization. Others might take this case as a starting point. If you still think we should change it, I will commit your suggestion.

2021-01-26 10:18 UTC, IshaanDesai commented on perpendicular-flap/solid-calculix/flap.inp
>  *DYNAMIC
> we don't really require a consistent time discretization.

This is true.. Lets drop this change then.

2021-01-26 14:29 UTC, BenjaminRodenberg commented on perpendicular-flap/fluid-openfoam/system/blockMeshDict
> +w 0;
Looks good. Thanks!

2021-01-26 14:45 UTC, uekerman commented
> Just so that somebody asks this: shouldn't we wait for the paper to be published before using the new figures here?

Should not change the copyright. Once we publish we might need to transfer the copyright. Maybe then we need to delete them here, but normally nobody cares about that.

2021-01-27 12:28 UTC, DavidSCN commented
Related to precice/su2-adapter#22

2021-01-27 12:45 UTC, MakisH commented on perpendicular-flap/README.md
> +
Let's postpone this then. It looks like there is now a discussion for this here: https://github.com/precice/tutorials/issues/150
I opened an issue regarding the documentation: https://github.com/precice/precice.github.io/issues/17

2021-01-27 13:10 UTC, MakisH reviewed
The structure looks good, but I had trouble running some combinations, which I don't want to look deeper to right now. Could you also check?

- :heavy_check_mark: fluid-openfoam + solid-deal.ii
- :x: fluid-openfoam + calculix
- :x: fluid-su2 + solid.deal.ii

The clean script I will fix / improve in the context of #133. Currently it seems to only clean the fluid-openfoam case.

2021-01-27 13:13 UTC, DavidSCN commented
> The structure looks good, but I had trouble running some combinations, which I don't want to look deeper to right now. Could you also check?
> 
>     * heavy_check_mark fluid-openfoam + solid-deal.ii
> 
>     * x fluid-openfoam + calculix

Calculix is an open TODO as shown in the checkbox above.

> 
>     * x fluid-su2 + solid.deal.ii

Have you pulle the develop version from today for SU2?

> 
> I probably don't have the correct versions of all the adapters at the moment.
> 
> The clean script I will fix / improve in the context of #133. Currently it seems to only clean the fluid-openfoam case.

In general appreciated. For me, it cleans up all cases.

2021-01-27 16:46 UTC, MakisH commented
> Have you pulled the develop version from today for SU2?

I pulled again and su2-deal.II works. Nice! We just got a case we did not have before! :D

I will review once again when all the todos are done (i.e. CalculiX).

2021-02-05 08:19 UTC, DavidSCN commented
In theory ready to merge. We have some quantitative differences in the watchpoint of ccx due to a low polynomial degree/mesh resolution, there are apparently some locking effects. We could (1) merge and live with it, (2) refine ccx or (3) make dealII and fenics coarser.
However, that's independent of any review. So, any reviewer who wants is welcome (also to test),

2021-02-05 13:05 UTC, uekerman commented
> We have some quantitative differences in the watchpoint of ccx due to a low polynomial degree/mesh resolution, there are apparently some locking effects. We could (1) merge and live with it, (2) refine ccx or (3) make dealII and fenics coarser.

We should refine the CCX mesh, could in theory also happen after this PR.

2021-02-08 08:52 UTC, IshaanDesai commented
The CalculiX mesh is now refined. Comparison results of tip displacement are as follows: 
![tip-displacement-with-OpenFOAM](https://user-images.githubusercontent.com/44898158/107196626-27c31d80-69f3-11eb-8920-79915be5b3f2.png)
![tip-displacement-with-SU2](https://user-images.githubusercontent.com/44898158/107196637-2b56a480-69f3-11eb-8fea-194432b1a109.png)

Relative l2 error between data plotted in both plots is `~ 0.2`. The error is high, any opinions on what can be done?

2021-02-13 17:15 UTC, uekerman commented
Our best guess currently is that there is sth wrong in with the FEniCS solid solver. @BenjaminRodenberg wanted to have a look at that. I will merge this nevertheless already. We can also fix things on the `restructure` branch. Otherwise, changes drift too far apart. We will anyway test everything again before merging to develop.

The only thing I still want to invest is the strangely high number of coupling iterations needed for the Nutils case.

2021-02-13 18:00 UTC, uekerman commented
Nutils-dealii converges very well for me. @DavidSCN Do you still get the bad convergence?

[precice-Solid-iterations.log](https://github.com/precice/tutorials/files/5976198/precice-Solid-iterations.log)

And I get sufficiently good agreement between Nutils-dealii and OpenFOAM-dealii. My tip displacement does however not match the one from  @IshaanDesai above. Some changes in between or still some inconsistency?

![flap_comparison](https://user-images.githubusercontent.com/2901384/107857237-86dac500-6e2d-11eb-8493-4185db5c015b.png)

2021-02-13 18:20 UTC, DavidSCN commented
> And I get sufficiently good agreement between Nutils-dealii and OpenFOAM-dealii. My tip displacement does however not match the one from @IshaanDesai above. Some changes in between or still some inconsistency?

Your solution looks indeed wrong and @IshaanDesai results should be the reference here. Do you use the develop branch of deal.II and this PR branch for your test?

2021-02-13 20:06 UTC, DavidSCN commented
The nutils case looks for me something like this in terms of iterations:
[precice-Solid-iterations.log](https://github.com/precice/tutorials/files/5976404/precice-Solid-iterations.log)

2021-02-14 15:08 UTC, IshaanDesai commented
> My tip displacement does however not match the one from @IshaanDesai above. Some changes in between or still some inconsistency?

@uekerman the results you posted look suspiciously similar to the old results before the physical parameters were tuned as part of this restructuring. I am highly confident that several oscillations of the flap are seen as per the new tutorials.

2021-02-14 15:31 UTC, uekerman commented
I used an old version of the OpenFOAM and deal.II adapter. I now get the same results. Trying to reproduce the Nutils problem now.

2021-02-14 17:55 UTC, uekerman commented
Nutils-dealii is looking good now. 

![flap_comparison](https://user-images.githubusercontent.com/2901384/107884447-7b52d100-6ef5-11eb-8f8a-6e5d88141158.png)
[precice-Solid-iterations.log](https://github.com/precice/tutorials/files/5978174/precice-Solid-iterations.log)


I tweaked a few things to get better convergence. I guess in the end the difference between Nutils and OpenFOAM is the less robust trapezoidal rule that Nutils uses.

@DavidSCN merge now or do you still want to tweak the SU2 case here?

2021-02-14 18:13 UTC, DavidSCN commented
> Nutils-dealii is looking good now.

Awesome. Let's merge in case you approve this PR.

2021-02-15 11:27 UTC, uekerman approved these changes

2021-02-15 11:28 UTC, merged

2021-02-27 17:33 UTC, alicezanella commented
Hi, 
I'm trying to run this tutorial, but It doesn't seem to work. 
I have precice 2.2.0, SU2 6.0.0 (with adapter) and CalculiX 2.16 (with adapter). 
I simply downloaded the test case, run ./Allrun and checked the logs. This is the error I get in Solid.log:

2021-02-28 10:03 UTC, IshaanDesai commented
Hi @alicezanella, can you please try to run the case with this branch: https://github.com/precice/calculix-adapter/tree/handle2DInterfaces of the CalculiX adapter? As this particular restructuring has not been merged into the `develop` or `master` branch of the tutorials, we have not synced the working with the respective adapter branches till now.

2021-03-04 08:59 UTC, alicezanella commented
Hi @IshaanDesai , 

I successfully run the case. Thank you for your answer!

2021-04-05 16:08 UTC, vryy commented
Hello, I tried to run this example recently, using OpenFoam-Calculix, and encounters an error:

"The interpolation matrix of the RBF mapping from mesh Fluid-Mesh-Faces to mesh Solid is not invertable. This means that the mapping problem is not well-posed. Please check if your coupling meshes are correct. Maybe you need to fix axis-aligned mapping setups by marking perpendicular axes as dead?"

In fact, it run successfully one week ago, but after some system update I recompiled all the packages and see this error. I'm struggling of the reason.

2021-04-05 16:18 UTC, BenjaminRodenberg commented
@vryy Please post this question on https://precice.discourse.group/. My first careful guess is that you are facing a problem similar to the one resolved in https://github.com/precice/tutorials/commit/a166efadfe7dbd3231e14897dcbeecebb90ea97e for a different case.

If you take a look at the commit message you will see exactly the same error you are facing.

2021-04-05 16:28 UTC, vryy commented
@BenjaminRodenberg I reposted the question on discourse