Simplify partitioned-heat-conduction case
precice/tutorials pull request #148
Opened 2021-01-20 13:21 UTC by BenjaminRodenberg

closes #137 

I removed everything that is not relevant for the simple case. Current specification:

* Dirichlet is always left, Neumann is always right
* Coupling Boundary is always straight line parallel to y axis
* No time dependent heat flux and rhs
* `mpirun` is still supported
* no subcycling. Timestep of both FEniCS solvers is hard-coded to be equal to time window size from `precice-config.xml`.

# Open Todos

- [ ] @IshaanDesai @uekerman Is anything missing or too much in the specification above?
- [ ] Need to adapt the structure to #125 
- [ ] Make sure that solver can be reused with other compatible cases, as well. (Nutils)

2021-01-20 13:23 UTC, BenjaminRodenberg commented
@uekerman I assume that `flow-over-heated-plate` is independent from this PR? The FEniCS solver used in `flow-over-heated-plate` is very similar, but has some differences and cannot easily be reused.

2021-01-20 14:51 UTC, uekerman commented
> @uekerman I assume that `flow-over-heated-plate` is independent from this PR? The FEniCS solver used in `flow-over-heated-plate` is very similar, but has some differences and cannot easily be reused.

yes, `flow-over-heated-plate` is completely independent of this one.

2021-01-20 15:05 UTC, uekerman commented
Specification looks good so far. I guess a real review only makes sense once we have the compatibility with Nutils.
A comment already now: for that we will need a scalar flux and a nearest-neighbor mapping.

2021-01-27 18:25 UTC, BenjaminRodenberg commented
> Specification looks good so far. I guess a real review only makes sense once we have the compatibility with Nutils.
> A comment already now: for that we will need a scalar flux and a nearest-neighbor mapping.

To make sure I understand: We want this case for FEniCS and for nutils. Meaning, according to the new structure we get:

* `partitioned-heat-conduction/`
    * `solid-fenics/...`
        * `heat.py`
    * `solid-nutils/...`
        * `heat.py`
    * `precice-config.xml`
    * `...`

This means, that we need a new tutorial (according to the old structure), `precice/tutorials/tree/master/HT/partitioned-heat/nutils-nutils`, first. Does this already exist somewhere? The closest one I can find is [`flow-over-plate/buoyantPimpleFoam-nutils`](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils/Nutils).

I think the cleanest approach would be to first create another PR from `develop`, where I collect all the necessary parts from `partitioned-heat/fenics-fenics` and `flow-over-plate/buoyantPimpleFoam-nutils` to develop a new case `partitioned-heat/nutils-nutils`. Afterwards I can use the resulting case, add it in this PR and move everything according to the new structure.

2021-02-03 10:00 UTC, uekerman commented
> This means, that we need a new tutorial (according to the old structure), precice/tutorials/tree/master/HT/partitioned-heat/nutils-nutils, first. Does this already exist somewhere?

Yes. Sources are provided in the issue: https://github.com/precice/tutorials/issues/137

> To make sure I understand: We want this case for FEniCS and for nutils. Meaning, according to the new structure we get:

The in  https://github.com/precice/tutorials/issues/137 suggested structure is

```
- dirichlet-fenics
  - heat.py
- neumann-fenics
  - heat.py
- dirichlet-nutils
  - heat.py
- neumann-nutils
  - heat.py 
- precice-config.xml
- clean.sh
- README.md
```

Yes, the drawback of this scheme is that it leads to quite some code duplication. Maybe it is simple to understand though.

Alternatively:

```
- fenics
  - heat.py
- nutils
  - heat.py
- precice-config.xml 
```
together with some command line argument to decide whether the left Dirichlet or the right Neumann sub domain should be computed.

2021-02-03 12:26 UTC, BenjaminRodenberg commented
> > This means, that we need a new tutorial (according to the old structure), precice/tutorials/tree/master/HT/partitioned-heat/nutils-nutils, first. Does this already exist somewhere?
> 
> Yes. Sources are provided in the issue: #137

I added the sources to this PR. Currently just copy-paste without any testing or updates of the code.

> > To make sure I understand: We want this case for FEniCS and for nutils. Meaning, according to the new structure we get:
> 
> The in #137 suggested structure is
> 
> ```
> - dirichlet-fenics
>   - heat.py
> - neumann-fenics
>   - heat.py
> - dirichlet-nutils
>   - heat.py
> - neumann-nutils
>   - heat.py 
> - precice-config.xml
> - clean.sh
> - README.md
> ```
> 
> Yes, the drawback of this scheme is that it leads to quite some code duplication. Maybe it is simple to understand though.

That's probably a good reason not to use this structure here.

> Alternatively:
> 
> ```
> - fenics
>   - heat.py
> - nutils
>   - heat.py
> - precice-config.xml 
> ```
> 
> together with some command line argument to decide whether the left Dirichlet or the right Neumann sub domain should be computed.

I like this idea. Added to this PR :+1:

2021-02-03 14:56 UTC, BenjaminRodenberg commented
I took care of updating the nutils case as far as I can get. I currently see one problem:

Nutils uses two meshes and FEniCS only one. This does not allow us to use the same configuration for both cases. @uekerman any idea what we can do here?

2021-02-03 16:15 UTC, uekerman commented
> Nutils uses two meshes and FEniCS only one. This does not allow us to use the same configuration for both cases. @uekerman any idea what we can do here?

We could read and write at the GPs only, that should be simple

2021-02-03 22:07 UTC, BenjaminRodenberg commented
The last problem with this PR that I see is that the exact solution cannot be recovered when using nutils. Remaining features are fine.

2021-02-05 15:10 UTC, BenjaminRodenberg commented
I decided to postpone fixing the nutils case to #152 and #153. This PR is from my point of view ready to merge. We can continue working on #153 at a later point in time from my point of view and I don't want with merging the features that are already working until the nutils case is fixed, since I'm a bit stuck here currently and it is hard to estimate how long fixing this will take.

2021-02-05 15:14 UTC, BenjaminRodenberg commented
Notes for review:

* Are the specifications from above fulfilled?
* Are there still any features or files we don't need for the respective cases?
* Is the documentation clear (enough)?

2021-02-07 21:42 UTC, IshaanDesai approved these changes
Looks good :+1: The separation of *simple* and *complex* geometry cases makes the FEniCS code much more readable :)

2021-02-07 21:42 UTC, IshaanDesai commented on partitioned-heat-conduction/README.md
> +* :construction: This case is still under construction. See https://github.com/precice/tutorials/issues/152. :construction: `nutils`, requires you to install [Nutils]
Would a link to Nutils documentation or any other code reference be helpful here?

2021-02-08 14:59 UTC, BenjaminRodenberg commented
@uekerman another hint for the review: Currently we don't provide `fenics/run.sh`, since we need command line input to decide whether we run the Dirichlet or Neumann solver. I see two options here:

1. provide a `fenics/run.sh` that accepts command line input
2. provide a `dirichlet-fenics/run.sh` and `neumann-fenics/run.sh`. Put all actual code only into `dirichlet-fenics`. `neumann-fenics` only exists for following the general structure and providing a `run.sh` script.

Any opinion?

2021-02-12 15:41 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
> +* :construction: This case is still under construction. See https://github.com/precice/tutorials/issues/152. :construction: `nutils`, requires you to install [Nutils]
Done. https://github.com/precice/tutorials/commit/35dc013342209c62cc53831410e620f4a7cf4063

2021-02-19 09:45 UTC, uekerman requested changes
Overall structure looks good. Minor conventions things and README stuff below.

2021-02-19 09:45 UTC, uekerman commented on partitioned-heat-conduction-complex/precice-config.xml
> +    <mesh name="DirichletNodes">
```suggestion
    <mesh name="Dirichlet-Mesh">
```
to follow the convention. Similar below.

2021-02-19 09:45 UTC, uekerman commented on partitioned-heat-conduction-complex/precice-config.xml
> +      <time-window-size value=".1" valid-digits="8"/>
```suggestion
      <time-window-size value=".1" />
```

2021-02-19 09:45 UTC, uekerman commented on partitioned-heat-conduction-complex/precice-config.xml
> +      <mapping:nearest-projection direction="read" from="NeumannNodes" to="DirichletNodes" constraint="consistent" timing="initial"/>
```suggestion
      <mapping:nearest-projection direction="read" from="NeumannNodes" to="DirichletNodes" constraint="consistent" />
```

2021-02-19 09:45 UTC, uekerman commented on partitioned-heat-conduction-complex/precice-config.xml
> +      <mapping:nearest-projection direction="read" from="DirichletNodes" to="NeumannNodes" constraint="consistent" timing="initial"/>
```suggestion
      <mapping:nearest-projection direction="read" from="DirichletNodes" to="NeumannNodes" constraint="consistent" />
```

2021-02-19 09:45 UTC, uekerman commented on partitioned-heat-conduction/README.md
> -{% include important.html content="We have not yet ported the documentation of the preCICE tutorials from the preCICE wiki to here. Please go to the [preCICE wiki](https://github.com/precice/precice/
We still need this. Otherwise the website will already show wrong information. Also please add this to the complex case.

2021-02-19 09:45 UTC, uekerman commented on partitioned-heat-conduction/README.md
>  summary:
TODO

2021-02-19 09:45 UTC, uekerman commented on partitioned-heat-conduction/README.md
> +In this tutorial we solve a partitioned heat equation. For information on the non-partitioned case, please refer to [1, p.37ff]. The corresponding FEniCS code can be found on [github:fenics-tutorial]
Needs probably a bit more information. We have not yet mentioned FEniCS before.

2021-02-19 09:45 UTC, uekerman commented on partitioned-heat-conduction/README.md
> +* :construction: This case is still under construction. See https://github.com/precice/tutorials/issues/152. :construction: `nutils`, requires you to install [Nutils](http://www.nutils.org/en/latest/
The "construction" is not necessary. Everything is still under construction :smile: 
The case already runs and gives qualitatively good results, right?

2021-02-19 09:45 UTC, uekerman commented on partitioned-heat-conduction/README.md
> +
Nutils missing.

2021-02-19 09:46 UTC, uekerman commented
> Currently we don't provide `fenics/run.sh`, since we need command line input to decide whether we run the Dirichlet or Neumann solver. I see two options here:
> 
>     1. provide a `fenics/run.sh` that accepts command line input
> 
>     2. provide a `dirichlet-fenics/run.sh` and `neumann-fenics/run.sh`. Put all actual code only into `dirichlet-fenics`. `neumann-fenics` only exists for following the general structure and providing a `run.sh` script.
> 
> 
> Any opinion?

I guess we are also fine without a run script here for the moment. If we add some later then option 1.

2021-02-19 10:33 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-complex/precice-config.xml
> +    <mesh name="DirichletNodes">
Ok. I will commit this change and clean up everything accordingly.

2021-02-19 10:35 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
> +* :construction: This case is still under construction. See https://github.com/precice/tutorials/issues/152. :construction: `nutils`, requires you to install [Nutils](http://www.nutils.org/en/latest/
The nutils case does not give good result yet. See #152. Therefore I would like to merge this one and mark the nutils case as "under construction".

2021-02-19 10:37 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
> +
I would prefer solving this in #152, as well.

2021-02-19 10:41 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
> -{% include important.html content="We have not yet ported the documentation of the preCICE tutorials from the preCICE wiki to here. Please go to the [preCICE wiki](https://github.com/precice/precice/
Resolved in e1d1411

2021-02-19 10:42 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
>  summary:
What exactly do you mean?

2021-02-19 11:23 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
> +In this tutorial we solve a partitioned heat equation. For information on the non-partitioned case, please refer to [1, p.37ff]. The corresponding FEniCS code can be found on [github:fenics-tutorial]
I provided more details on the case in 75e68af. I don't think that we have to explain what FEniCS is here. Or what do you mean?

2021-02-19 12:54 UTC, uekerman commented on partitioned-heat-conduction/README.md
>  summary:
To write a summary

2021-02-19 12:56 UTC, uekerman commented on partitioned-heat-conduction/README.md
> +In this tutorial we solve a partitioned heat equation. For information on the non-partitioned case, please refer to [1, p.37ff]. The corresponding FEniCS code can be found on [github:fenics-tutorial]
Right now, "FEniCS" falls a bit from the sky. The setup should actually be independent of the solver.

2021-02-19 12:57 UTC, uekerman commented on partitioned-heat-conduction/README.md
> +* :construction: This case is still under construction. See https://github.com/precice/tutorials/issues/152. :construction: `nutils`, requires you to install [Nutils](http://www.nutils.org/en/latest/
What does "not good" exactly mean? :grin:

2021-02-19 12:59 UTC, uekerman commented on partitioned-heat-conduction/README.md
> +
OK, but then let's maybe remove that this PR solves #137 
Otherwise, I get too confused :smile:

2021-02-19 17:00 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
>  summary:
Ok. I was totally focused on the diff. This makes sense :sweat_smile:

2021-02-19 17:04 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
>  summary:
Done. bf765be1be7216f28d8ccabe7d04036dae8627eb

2021-02-19 17:10 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
> +
I removed the `closes #137` to make this PR less confusing. Will work on the rest in #152

2021-02-19 17:10 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
> +* :construction: This case is still under construction. See https://github.com/precice/tutorials/issues/152. :construction: `nutils`, requires you to install [Nutils](http://www.nutils.org/en/latest/
See below: I removed the `closes #137` to make this PR less confusing. Will work on the rest in #152

2021-02-19 23:25 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/README.md
> +In this tutorial we solve a partitioned heat equation. For information on the non-partitioned case, please refer to [1, p.37ff]. The corresponding FEniCS code can be found on [github:fenics-tutorial]
I did some reordering in 9614c02. I think this makes it a bit better.

2021-03-05 16:17 UTC, uekerman approved these changes
Looks good. Did not run it again, but did not see any obvious problems.

2021-03-05 16:17 UTC, merged