Port trivial cases
precice/tutorials pull request #151
Opened 2021-01-28 11:53 UTC by DavidSCN

Closes #134 

Important TODOs left: 
 - [ ] test code_aster case (I have no installation)
 - [ ] add more information in the README
 
Although various cases were previously bad documented and I don't want to write the documentation for all of these cases.

2021-01-29 13:42 UTC, uekerman commented
> Although various cases were previously bad documented and I don't want to write the documentation for all of these cases.

Could you please split up the TODO above into one per case and let us know in which status each README is. We could then try to distribute the work there.

2021-02-11 12:52 UTC, DavidSCN commented
@MakisH may I ask you to test the code_aster tutorial? I think it will currently not work since there are specific requirements for the exchange directory (potentially incompatible with other solvers which we currently don't have).

2021-02-11 13:17 UTC, MakisH commented
I also don't have code_aster installed at the moment to test it, but I should eventually include it in the VM. Have you tested it in the meantime? I guess having someone else to also go through the docs would be useful: https://github.com/precice/code_aster-adapter/wiki/Flow-over-plate-Code_Aster-Tutorial

The main things that are special are:
- that the user needs to set an absolute path as an exchange directory (we already specify this in the docs)
- that the case is steady-state.

I don't think I will have time to look into code_aster until after the workshop.

2021-02-11 14:42 UTC, DavidSCN commented
> I also don't have code_aster installed at the moment to test it, but I should eventually include it in the VM. Have you tested it in the meantime? I guess having someone else to also go through the docs would be useful: https://github.com/precice/code_aster-adapter/wiki/Flow-over-plate-Code_Aster-Tutorial

I have already ported the docs to the new website.

2021-02-15 11:57 UTC, uekerman requested changes
Some suggestion on "multiple flaps". Similarly, the preCICE config of "partitioned elastic beam" and "flow-over-heated-plate" needs to be ported. The latter, in particular, needs to be changed to 2D.

2021-02-15 11:57 UTC, uekerman commented on multiple-perpendicular-flaps/precice-config.xml
> +    <mesh name="Solid1_mesh">
```suggestion
    <mesh name="Solid1-Mesh">
```
and similar occurences below.

2021-02-15 11:57 UTC, uekerman commented on multiple-perpendicular-flaps/precice-config.xml
> +      <export:vtk directory="precice-output" />
```suggestion
```
or do we need those?

2021-02-15 11:57 UTC, uekerman commented on multiple-perpendicular-flaps/precice-config.xml
> +      <export:vtk directory="precice-output" />
```suggestion
```
or do we need those?

2021-02-15 11:57 UTC, uekerman commented on multiple-perpendicular-flaps/precice-config.xml
> +      <watch-point mesh="Solid2_mesh" name="flap_tip" coordinate="0.95;1" />
```suggestion
      <watch-point mesh="Solid2-Mesh" name="Flap-Tip" coordinate="0.95;1" />
```

2021-02-15 11:57 UTC, uekerman commented on multiple-perpendicular-flaps/precice-config.xml
> +      <export:vtk directory="precice-output" />
```suggestion
```
or do we need those?

2021-02-15 11:57 UTC, uekerman commented on multiple-perpendicular-flaps/precice-config.xml
> +      <exchange data="Displacement2" mesh="Solid2_mesh" from="Solid2" to="Fluid" initialize="0" />
```suggestion
      <exchange data="Displacement1" mesh="Solid1_mesh" from="Solid1" to="Fluid" />
      <exchange data="Displacement2" mesh="Solid2_mesh" from="Solid2" to="Fluid" />
```

2021-02-15 11:59 UTC, uekerman commented
> I also don't have code_aster installed at the moment to test it, but I should eventually include it in the VM. Have you tested it in the meantime? I guess having someone else to also go through the docs would be useful: https://github.com/precice/code_aster-adapter/wiki/Flow-over-plate-Code_Aster-Tutorial

I guess what @MakisH meant is to try them out :grin:

2021-02-16 08:57 UTC, DavidSCN commented on multiple-perpendicular-flaps/precice-config.xml
> +      <export:vtk directory="precice-output" />
They are explicitly mentioned in the README. Let's keep them here.

2021-02-19 09:21 UTC, uekerman commented on multiple-perpendicular-flaps/precice-config.xml
> +      <export:vtk directory="precice-output" />
I removed them there as well :smile: 
In my opinion, preCICE vtk is for debugging, not to show the solid results. The interface displ you already get from OpenFOAM and for more information (stress distribution etc) you need the full solid results. This interface output, you really only need if you don't trust what preCICE is doing, so debugging, which should not be on by default :smirk:

2021-02-19 09:30 UTC, uekerman commented
Let's ignore the Code_Aster case here and do it after merging: #155.

2021-02-19 13:33 UTC, uekerman approved these changes

2021-02-19 13:33 UTC, merged