Restructure flow over plate
precice/tutorials pull request #154
Opened 2021-02-14 20:50 UTC by DavidSCN

Closes #136 

Open TODOs:
- [ ] Remove the duplicated meshes (CC/GP) for Nutils and (maybe) remove 3rd dimension @uekerman 
- [ ] CalculiX crashes. Might be related to precice/calculix-adapter#49. Maybe @IshaanDesai knows more about it.
- [ ] Update the README

2021-02-15 06:49 UTC, IshaanDesai commented
Could you please try the CalculiX combination with the branch of the CalculiX-Adapter in this PR: https://github.com/precice/calculix-adapter/pull/50? If CalculiX still crashes then the error message would be helpful in determining the problem.

2021-02-15 07:18 UTC, DavidSCN commented
Already done. CalculiX crashes here https://github.com/precice/calculix-adapter/blob/63af15333c8d5f3ba85fdec28ec35042cb2691e2/nonlingeo_precice.c#L1307 since the simulationData(?) is uninitialized.

2021-03-02 09:14 UTC, DavidSCN commented
Ready to merge!

2021-03-05 19:30 UTC, BenjaminRodenberg requested changes
I successfully ran FEniCS-OpenFOAM, Nutils-OpenFOAM and OpenFOAM-OpenFOAM.

Minor documentation issues.

I think you should also add some more files to the `.gitignore`, since I currently get quite a lot of untracked files due to output:

```
$ ~/tutorials/flow-over-heated-plate$ git status .
HEAD detached at DavidSCN/restructure-flow-over-plate
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   precice-config.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	buoyantPimpleFoam-fenics/
	fluid-openfoam/0.2/
	fluid-openfoam/0.4/
	fluid-openfoam/0.6/
	fluid-openfoam/0.8/
	fluid-openfoam/0/
	fluid-openfoam/1/
	fluid-openfoam/VTK/
	fluid-openfoam/constant/polyMesh/
	fluid-openfoam/precice-Fluid-events-summary.log
	fluid-openfoam/precice-Fluid-events.json
	fluid-openfoam/precice-Fluid-iterations.log
	solid-fenics/Solid/
	solid-fenics/precice-Solid-convergence.log
	solid-fenics/precice-Solid-events-summary.log
	solid-fenics/precice-Solid-events.json
	solid-fenics/precice-Solid-iterations.log
	solid-nutils/Solid_0.vtk
	solid-nutils/Solid_100.vtk
	solid-nutils/Solid_20.vtk
	solid-nutils/Solid_40.vtk
	solid-nutils/Solid_60.vtk
	solid-nutils/Solid_80.vtk
	solid-nutils/precice-Solid-convergence.log
	solid-nutils/precice-Solid-events-summary.log
	solid-nutils/precice-Solid-events.json
	solid-nutils/precice-Solid-iterations.log
	solid-openfoam/0.2/
	solid-openfoam/0.4/
	solid-openfoam/0.6/
	solid-openfoam/0.8/
	solid-openfoam/0/
	solid-openfoam/1/
	solid-openfoam/constant/polyMesh/
	solid-openfoam/precice-Solid-convergence.log
	solid-openfoam/precice-Solid-events-summary.log
	solid-openfoam/precice-Solid-events.json
	solid-openfoam/precice-Solid-iterations.log
```

2021-03-05 19:30 UTC, BenjaminRodenberg commented on flow-over-heated-plate/solid-fenics/run.sh
> +python3 heat.py
Is there a specific reason to call this `heat.py`? I know that I historically picked the name, since the script solved the heat equation. But, if you want to make it consistent with Nutils, `solid.py` might also make sense.

2021-03-05 19:30 UTC, BenjaminRodenberg commented on flow-over-heated-plate/precice-config.xml
> +</precice-configuration>
Not possible to run in parallel with this mapping configuration. You can basically copy the approach from https://github.com/precice/tutorials/blob/5f4031fc7e45807dca787a525569b39a1909d2a3/HT/partitioned-heat/fenics-fenics/precice-config.xml#L24-L38 to be able to run the case in parallel (e.g. `solid-fenics$ python3 mpirun -np 2 heat.py`).

```suggestion
<?xml version="1.0"?>
<precice-configuration>
  <log>
    <sink
      filter="%Severity% > debug and %Rank% = 0"
      format="---[precice] %ColorizedSeverity% %Message%"
      enabled="true" />
  </log>

  <solver-interface dimensions="2">
    <data:scalar name="Temperature" />
    <data:scalar name="Heat-Flux" />

    <mesh name="Fluid-Mesh">
      <use-data name="Temperature" />
      <use-data name="Heat-Flux" />
    </mesh>

    <mesh name="Solid-Mesh">
      <use-data name="Temperature" />
      <use-data name="Heat-Flux" />
    </mesh>

    <participant name="Fluid">
      <use-mesh name="Fluid-Mesh" provide="yes" />
      <use-mesh name="Solid-Mesh" from="Solid" />
      <mapping:nearest-neighbor
        direction="read"
        from="Solid-Mesh"
        to="Fluid-Mesh"
        constraint="consistent" />
      <read-data name="Heat-Flux" mesh="Fluid-Mesh" />
      <write-data name="Temperature" mesh="Fluid-Mesh" />
    </participant>

    <participant name="Solid">
      <use-mesh name="Fluid-Mesh" from="Fluid" />
      <use-mesh name="Solid-Mesh" provide="yes" />
      <mapping:nearest-neighbor
        direction="read"
        from="Fluid-Mesh"
        to="Solid-Mesh"
        constraint="consistent" />
      <read-data name="Temperature" mesh="Solid-Mesh" />
      <write-data name="Heat-Flux" mesh="Solid-Mesh" />
    </participant>

    <m2n:sockets from="Fluid" to="Solid" exchange-directory=".." />

    <coupling-scheme:serial-implicit>
      <time-window-size value="0.01" />
      <max-time value="1" />
      <max-iterations value="30" />
      <participants first="Fluid" second="Solid" />
      <exchange data="Temperature" mesh="Fluid-Mesh" from="Fluid" to="Solid" />
      <exchange data="Heat-Flux" mesh="Solid-Mesh" from="Solid" to="Fluid" />
      <relative-convergence-measure limit="1.0e-5" data="Temperature" mesh="Fluid-Mesh" />
      <acceleration:aitken>
        <data mesh="Solid-Mesh" name="Heat-Flux" />
        <initial-relaxation value="0.5" />
      </acceleration:aitken>
    </coupling-scheme:serial-implicit>
  </solver-interface>
</precice-configuration>
```

2021-03-08 08:25 UTC, DavidSCN commented on flow-over-heated-plate/solid-fenics/run.sh
> +python3 heat.py
I just copied the already existing name. I changed it.

2021-03-08 08:53 UTC, DavidSCN commented
Thanks!

> I think you should also add some more files to the .gitignore, since I currently get quite a lot of untracked files due to output:

I understand. This is more a developer problem and not a user problem. I usually use the clean scripts to get rid of these outputs, but this might not always be what you want. However, I would vote for a global `gitignore` file since we have similar problems in all tutorials cases and I don't like the duplication. Reminds me of https://github.com/precice/tutorials/issues/133 and couldbe part of the workpackage there.

2021-03-09 13:29 UTC, BenjaminRodenberg commented on flow-over-heated-plate/README.md
> +The test case is two-dimensional and a serial-implicit coupling with Aitken underrelaxation is used for the coupling.
I just realized that we should provide some more details here. The following parameters are needed for the physical setup:

![Screenshot from 2021-03-09 14-20-20](https://user-images.githubusercontent.com/5740604/110477608-a8089b80-80e3-11eb-821f-3ae21e14f264.png)

The picture you provide is fine with respect to the geometry. The physical parameters (conductivity, diffusivity, ...) are missing.

2021-03-10 08:03 UTC, DavidSCN commented on flow-over-heated-plate/README.md
> +The test case is two-dimensional and a serial-implicit coupling with Aitken underrelaxation is used for the coupling.
@BenjaminRodenberg May I ask you to directly exchange the respective figure? Do wen want to keep the captions as in your figure above?

2021-03-10 09:30 UTC, BenjaminRodenberg commented on flow-over-heated-plate/README.md
> +The test case is two-dimensional and a serial-implicit coupling with Aitken underrelaxation is used for the coupling.
I added the material properties in the text. I think the figure we are currently using is good for this purpose. I think we should not use my figure here. I also notices that the measurements are different. You figure has `L=3.5`, mine has `L=6.0`. Was this changed?

2021-03-10 09:37 UTC, DavidSCN commented on flow-over-heated-plate/README.md
> +The test case is two-dimensional and a serial-implicit coupling with Aitken underrelaxation is used for the coupling.
Alright. 
I essentially ported the figure from our wiki, meaning that I have not created it. I just looked into the OpenFOAM fluid case and I still measure `L=3.5`. No changes have been made here from my side.

2021-03-10 09:48 UTC, BenjaminRodenberg commented on flow-over-heated-plate/README.md
> +The test case is two-dimensional and a serial-implicit coupling with Aitken underrelaxation is used for the coupling.
I think I know where the wrong data in the table comes from: Classical copy-paste error from https://github.com/precice/tutorials/pull/146#issuecomment-767064825.

2021-03-10 15:09 UTC, DavidSCN commented
@BenjaminRodenberg I checked now the parameters of your figure again. The farfield velocity should be 0.1 instead of 0.01 and (maybe) the gravity needs a minus sign. I would also remove the z coordinate: you don't have it in the figure and it hasn't any relevance for this case. The heat transfer coefficient k is only defined in the solid participant/ I cannot find it in the Fluid preciceDict, is this correct?

Do you want to comment on the `.gitignore' discussion?

2021-03-10 15:59 UTC, BenjaminRodenberg commented on flow-over-heated-plate/README.md
> +The test case is two-dimensional and a serial-implicit coupling with Aitken underrelaxation is used for the coupling.
Answer to https://github.com/precice/tutorials/pull/154#issuecomment-795575139:

> @BenjaminRodenberg I checked now the parameters of your figure again. The farfield velocity should be 0.1 instead of 0.01

Good find! I will fix this in the figure. Already fixed it in the `README.md` in e8e0db0.

> and (maybe) the gravity needs a minus sign.

I think this should be clear from the context.

> I would also remove the z coordinate: you don't have it in the figure and it hasn't any relevance for this case.

I would rather document it than not. Remember: We had quite some discussion on a similar case in #108 and you have to provide something for OpenFOAM. I'm also not sure that it really does not matter whether you pick 0.4 or 400 as thickness. Did we ever test this?

> The heat transfer coefficient k is only defined in the solid participant/ I cannot find it in the Fluid preciceDict, is this correct?

Correct, but one can compute it from the Prandtl number (see https://en.wikipedia.org/wiki/Prandtl_number) and I think it is helpful to provide `k_F`, since this makes the following relationship clear: equal conductivity on both sides mean C1 continuous contour lines.

It also makes sense to have a overlap-free set of parameters. Therefore, let's remove the Prandtl number from this figure. One can easily compute it from the given parameters, if needed.

Here is the updated figure:

![Screenshot from 2021-03-10 16-58-49](https://user-images.githubusercontent.com/5740604/110658410-f55b3a80-81c1-11eb-800e-9cec99f1f432.png)

From my point of view, we can conclude on this state, if you are fine with this.

2021-03-10 16:00 UTC, BenjaminRodenberg commented
> Do you want to comment on the `.gitignore` discussion?

A global `.gitignore` is also fine :+1:

2021-03-10 16:03 UTC, DavidSCN commented on flow-over-heated-plate/README.md
> +The test case is two-dimensional and a serial-implicit coupling with Aitken underrelaxation is used for the coupling.
Yes, thanks, very nice :ok_hand:

2021-03-10 16:10 UTC, BenjaminRodenberg approved these changes
Looks good to me :+1:

2021-03-10 16:12 UTC, merged