[WIP] Update deal.II scripts
precice/tutorials pull request #166
Opened 2021-03-18 15:17 UTC by DavidSCN

Related to precice/dealii-adapter#50 and precice/dealii-adapter#51.

@uekerman Now you have an example for the new version. I hope this helps in order to review the changes. In the dealii-adapter, please review first precice/dealii-adapter#51 and then precice/dealii-adapter#50.

2021-03-19 15:40 UTC, uekerman requested changes
This review includes https://github.com/precice/dealii-adapter/pull/50 and https://github.com/precice/dealii-adapter/pull/51

I did not check the code details, but the user side is nice. Much easier to handle now :+1:
I was able to run linear and non-linear.
Only a few things we could document better in the parameters file.
(why is there a `parameters.prm` in the adapter repo?)

And the README of the adapter needs to be updated.

2021-03-19 15:40 UTC, uekerman commented on perpendicular-flap/solid-dealii/run.sh
> +./elasticity parameters.prm
currently `dealii-precice`, needs probably an update in the adapter

2021-03-19 15:40 UTC, uekerman commented on perpendicular-flap/solid-dealii/parameters.prm
> +  # Structural model to be used: linear or neo-Hookean
```suggestion
  # Structural model to be used: linear or neo-Hooke
```
At least that's what the adapter wants right now.

2021-03-19 15:40 UTC, uekerman commented on perpendicular-flap/solid-dealii/parameters.prm
>    set Max iteration multiplier  = 1
This option is hard to understand. Needs more documentation I guess. This is only needed if CG is chosen below, right? We could add such restrictions in the comment: "ignored for Direct" or similar.

2021-03-19 15:40 UTC, uekerman commented on perpendicular-flap/solid-dealii/parameters.prm
> +  set Max iterations Newton-Raphson = 10
ignored if "Model = linear" or similar.

2021-03-19 15:40 UTC, uekerman commented on perpendicular-flap/solid-dealii/parameters.prm
What does "scaled by residual norm" mean exactly? Is this a relative residual?
Why relative here and absolute for the non-linear iteration?

2021-03-19 15:40 UTC, uekerman commented on perpendicular-flap/solid-dealii/parameters.prm
>  end
```suggestion
  # Absolute displacement error tolerance for non-linear iteration (ignored if Model == linear)
  set Tolerance displacement        = 1.0e-6

  # Absolute force residual tolerance for non-linear iteration (ignored if Model == linear)
  set Tolerance force               = 1.0e-9
end
```

2021-03-21 12:55 UTC, DavidSCN commented on perpendicular-flap/solid-dealii/parameters.prm
It's an absolute residual, the non-linear solver below uses relative residuals.

2021-03-21 12:55 UTC, DavidSCN commented on perpendicular-flap/solid-dealii/parameters.prm
>  end
These residuals are relative, I added a comment.

2021-03-21 12:58 UTC, DavidSCN commented
> why is there a parameters.prm in the adapter repo?

It's needed to run a self created case.

>  And the README of the adapter needs to be updated.

Done.

2021-03-21 16:56 UTC, uekerman commented
> > why is there a parameters.prm in the adapter repo?
> 
> It's needed to run a self created case.

You could also point to the tutorials, right? In the end, it's just some code duplication, so another place to update when things change. Or what do you mean by self created case? You will always need another participant and a `precice-config.xml`, right?

2021-03-21 16:59 UTC, uekerman commented on multiple-perpendicular-flaps/solid-right-dealii/parameters.prm
> +  # In 2-d, this value is best set at 2. In 3-d, a value of 1 work fine.
```suggestion
  # In 2D, this value is best set at 2. In 3D, a value of 1 works fine.
```

2021-03-21 16:59 UTC, uekerman commented on multiple-perpendicular-flaps/solid-right-dealii/parameters.prm
> +  # Absolute CG solver residual (multiplied by residual norm, ignored if Model == linear)
```suggestion
  # Absolute CG solver residual (multiplied by residual norm, ignored if Solver type == Direct)
```
right?

2021-03-22 07:22 UTC, DavidSCN commented on multiple-perpendicular-flaps/solid-right-dealii/parameters.prm
> +  # Absolute CG solver residual (multiplied by residual norm, ignored if Model == linear)
No, the linear system is solved more accurate when approaching the solution of the nonlinear system. I hard coded it to 1e-10 for the linear model. Does it make sense for you?

2021-03-22 07:24 UTC, DavidSCN commented
> > > why is there a parameters.prm in the adapter repo?
> > 
> > 
> > It's needed to run a self created case.
> 
> You could also point to the tutorials, right? In the end, it's just some code duplication, so another place to update when things change. Or what do you mean by self created case? You will always need another participant and a `precice-config.xml`, right?

_hm_ The way I think of it is more a parameter file reference, similar to our xml reference. The cases in the tutorials are special configurations for a certain example. In fact, I could remove half of the parameters, where the nonlinear solver is not supposed to be used.

2021-03-23 13:30 UTC, uekerman approved these changes

2021-03-23 14:35 UTC, merged