Adding a change log
precice/tutorials pull request #225
Opened 2021-07-14 10:56 UTC by IshaanDesai

Adding a CHANGELOG to the tutorials repository.

2021-07-15 07:48 UTC, MakisH approved these changes

2021-07-15 07:50 UTC, MakisH commented
Looks good: it looks like you followed the format used in preCICE and you transferred the release notes (have not checked in detail).

Just remember to contribute the changelog entries as independent files, to avoid merge conflicts.

2021-07-15 07:51 UTC, IshaanDesai commented
> Just remember to contribute the changelog entries as independent files, to avoid merge conflicts.

I dont really understand what you are saying here, can you please explain more :sweat_smile:

2021-07-15 08:01 UTC, DavidSCN commented
Have a look at the preCICE changelogs: https://github.com/precice/precice/tree/develop/docs/changelog

The `CHANGELOG` file is usually only updated for new version release. The changelog entries are collected in separate files in order to avoid merge conflicts.

2021-07-15 08:29 UTC, uekerman requested changes

2021-07-15 08:29 UTC, uekerman commented on CHANGELOG.md
> +- Syncing the post-processing functionality of the elastic-tube-1d and the respective documentation. (#209)
Style-wise, changelog entries should always start with a verb in past tense. (added, fixed, improved, ...)
The links are not cklickable, right? In the OpenFOAM adapter changelog such a format is used: [#173](https://github.com/precice/openfoam-adapter/pull/173)

I guess you checked this list against the commit history since the release, right?

2021-07-15 08:29 UTC, uekerman commented on CHANGELOG.md
> +## 202104.1.1
```suggestion
## 202104.2.0
```
?

2021-07-15 08:29 UTC, uekerman commented on CHANGELOG.md
> +- **A validated Turek-Hron FSI3:** Validated with OpenFOAM and non-linear deal.II.
Maybe add a statement here that we started the changelog only after 202104.1.0. And that for that version we show instead a summary of the release highlights.

2021-07-15 09:09 UTC, MakisH commented on CHANGELOG.md
> +## 202104.1.1
These are the already released versions, 202104.1.1 is the latest one: https://github.com/precice/tutorials/releases

2021-07-15 09:12 UTC, MakisH commented on CHANGELOG.md
> +- Syncing the post-processing functionality of the elastic-tube-1d and the respective documentation. (#209)
Good point about the language. These are currently the past release notes, so I thought it is good enough for now (though these are not too many points to adapt). If we consider the 2104.1.0 as the first release, then the changelog can also start refering to changes (i.e. verbs) in later versions.

If we are looking for a standard, in the OpenFOAM adapter we are using the keep-a-changelog format: https://github.com/precice/openfoam-adapter/blob/develop/CHANGELOG.md

2021-07-15 10:56 UTC, IshaanDesai commented
> Have a look at the preCICE changelogs: https://github.com/precice/precice/tree/develop/docs/changelog
> 
> The `CHANGELOG` file is usually only updated for new version release. The changelog entries are collected in separate files in order to avoid merge conflicts.

Okay, so this would only be valid for changes done from the last release till now correct? And how do we decide the numbers in the names of the files? Would the *merge conflicts* happen because multiple feature developments would consecutively edit the CHANGELOG? In that case does it not work if every feature developer just pulls, resolves the conflict and pushes to the CHANGELOG?

2021-07-15 10:58 UTC, IshaanDesai commented on CHANGELOG.md
> +- Syncing the post-processing functionality of the elastic-tube-1d and the respective documentation. (#209)
I changed the file to follow the `keep-a-changelog` format.

2021-07-15 11:22 UTC, DavidSCN commented
> > Have a look at the preCICE changelogs: https://github.com/precice/precice/tree/develop/docs/changelog
> > The `CHANGELOG` file is usually only updated for new version release. The changelog entries are collected in separate files in order to avoid merge conflicts.
> 
> Okay, so this would only be valid for changes done from the last release till now correct? And how do we decide the numbers in the names of the files? Would the _merge conflicts_ happen because multiple feature developments would consecutively edit the CHANGELOG? In that case does it not work if every feature developer just pulls, resolves the conflict and pushes to the CHANGELOG?

The numbers in the file names correspond to the PR number of the repo. To your second questions: yes that's right and yes that would be done as an alternative.

2021-07-16 10:21 UTC, fsimonis commented
> In that case does it not work if every feature developer just pulls, resolves the conflict and pushes to the CHANGELOG?

Yes, but this results in a merge conflict for each change since the PR started. Most importantly, it is so annoying that devs become angry. And angry devs are not got at resolving merge conflicts without accidentally deleting old entries.

The steps are easy:
* define a dir that doesn't break the jekyll import script.
* Use a script to create the changelong [example](https://github.com/precice/precice/blob/develop/tools/releasing/bumpversion.sh)
* Use a script to generate new entries using gh-cli [example](https://github.com/precice/precice/blob/develop/tools/building/createChangelog)

2021-07-16 15:32 UTC, uekerman approved these changes
Some c&p problems I guess. Otherwise good to go from my side.
I am not sure about the markdown lint things.

Do we want to have the `changelog-entries` under `docs`?

2021-07-16 15:32 UTC, uekerman commented on CHANGELOG.md
> +The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
We don't follow semantic versioning exactly, do we?
https://github.com/precice/tutorials/releases

2021-07-16 15:32 UTC, uekerman commented on CHANGELOG.md
> +Read more details in the issue [#52: Releases and versioning](https://github.com/precice/openfoam-adapter/issues/52).
```suggestion
```

2021-07-16 15:38 UTC, IshaanDesai commented
> Do we want to have the `changelog-entries` under `docs`?

I now have the entries at the base directory

2021-07-16 15:43 UTC, MakisH requested changes

2021-07-16 15:43 UTC, MakisH commented on .markdownlint.json
> +    "MD002": false,
~~Why ignoring the [MD002](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md002---first-heading-should-be-a-top-level-heading)? This is a good rule and I don't see any violation here.~~

I see that the problem is the changelog entries. Better ignore the directory in the workflow: https://github.com/precice/openfoam-adapter/blob/develop/.github/workflows/check-markdown.yml#L14

2021-07-16 15:43 UTC, MakisH commented on CHANGELOG.md
> +# preCICE tutorials change log
Let's stick to the "changelog" writing everywhere, [it is getting more popular lately](https://books.google.com/ngrams/graph?content=changelog%2C+change+log&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Cchangelog%3B%2Cc0%3B.t1%3B%2Cchange%20log%3B%2Cc0) and we use this in other repositories. :-)

2021-07-16 15:43 UTC, MakisH commented on CHANGELOG.md
> +- Added a change log for this project as a file named `CHANGELOG.md`.
This only came later (well, coming up now).

2021-07-16 15:43 UTC, MakisH commented on CHANGELOG.md
> +
We can still say here that this was the first tagged version (with a large restructuring) and link to the release notes, as there is more information there.

I am not sure if this list is enough, but the link would definitely help. It is not so important for the first one, I think, anyway.

2021-07-21 09:24 UTC, IshaanDesai commented
The failing workflows are not relevant to the addition of the CHANGELOG and hence need to be investigated independently.

2021-07-21 11:24 UTC, MakisH approved these changes
I noticed 2-3 small things. Please consider them and then feel free to merge!

2021-07-21 11:24 UTC, MakisH commented on .github/workflows/check-markdown.yml
> +          config-file: '.markdown-link-check-config.json'
This is now a duplicate test. Better remove it, we have the stand-alone (and thus clearer) `check-links.yml` instead.
```suggestion
```

2021-07-21 11:24 UTC, MakisH commented on CHANGELOG.md
> +## [v202104.1.0] 2021-05-02
The dates look wrong: the earlier version has a later date. Maybe they should be swaped?

2021-07-21 11:24 UTC, MakisH commented on changelog-entries/219.md
> +- Added new volume coupled diffusion tutorial with FEniCS [#219](https://github.com/precice/tutorials/pull/219)
Just FYI: this seems to be unrelated. But if this is coming from another branch, then it is fine.

2021-07-21 15:42 UTC, IshaanDesai commented on changelog-entries/219.md
> +- Added new volume coupled diffusion tutorial with FEniCS [#219](https://github.com/precice/tutorials/pull/219)
This is indeed a change coming from another PR but as the whole change-log system is implemented here, it has been added via this PR.

2021-07-21 15:43 UTC, merged