Channel transport with OpenFOAM
precice/tutorials pull request #315
Opened 2022-12-05 11:09 UTC by tirgendetwas

Channel transport tutorial using OpenFOAM for the fluid participant (and Nutils for the transport participant).

2023-01-10 09:05 UTC, uekerman commented
Good to have this new case!
Is there a motivation for adding it as a separate case and not "simply" extending https://precice.org/tutorials-channel-transport.html that I don't see?

2023-01-10 09:06 UTC, MakisH commented
> Good to have this new case! Is there a motivation for adding it as a separate case and not "simply" extending https://precice.org/tutorials-channel-transport.html that I don't see?

There is no particular motivation. This is still a draft and @tirgendetwas is planning to move the case there.

2023-01-23 12:46 UTC, MakisH approved these changes
I ran the case and it looks good. The structure is correct and the results look at least qualitatively right (I have not compared to the fluid-nutils).

The only thing missing is an entry in the tutorial's `README.md`.

2023-01-23 12:46 UTC, MakisH commented on channel-transport/fluid-openfoam/system/decomposeParDict
> +numberOfSubdomains 2;
The parallel version does not work due to the selected preCICE mapping:

```
---[precice] ERROR:  For a parallel participant, only the mapping combinations read-consistent and write-conservative are allowed
```

Irrelevant to this PR, but we may want to consider that we have not yet tested the volume coupling in parallel.

2023-02-12 20:10 UTC, tirgendetwas commented on channel-transport/fluid-openfoam/system/preciceDict
> +    patches           (obstacle);
Actually, no ^^

2023-02-12 20:32 UTC, tirgendetwas commented on channel-transport/fluid-openfoam/system/decomposeParDict
> +numberOfSubdomains 2;
Updated and tested with serial-explicit and parallel-explicit coupling

2023-04-04 10:57 UTC, MakisH commented on channel-transport/README.md
> +* OpenFOAM (pimpleFoam): tested with OpenFOAM v2112. For more information, have a look at the [OpenFOAM adapter documentation](https://precice.org/adapter-openfoam-overview.html).
Is the version important? We should always try to check with the latest version anyway.

```suggestion
* OpenFOAM (pimpleFoam): For more information, have a look at the [OpenFOAM adapter documentation](https://precice.org/adapter-openfoam-overview.html).
```

Seems to be running with OpenFOAM v2212 anyway, using the current `volume-coupling` branch.

2023-04-04 10:57 UTC, MakisH commented on channel-transport/precice-config.xml
>      </participant>
Why do we need to change the `precice-config.xml` to add the OpenFOAM case?
Why do we need to move the mapping to the `Transport` participant and exchange the `Fluid-Mesh`?

Note that, in any case, we will need to update to preCICE v3 before merging.

2023-04-04 10:57 UTC, MakisH commented on channel-transport/fluid-openfoam/system/decomposeParDict
> +// TODO test and find correct number
I checked (with `./run.sh -parallel`) and the results look reasonable (did not compare values). Four subdomains are also reasonable for a tutorial, and cutting both horizontally and vertically helps us identify issues.

2023-05-01 20:00 UTC, tirgendetwas commented on channel-transport/README.md
> +* OpenFOAM (pimpleFoam): tested with OpenFOAM v2112. For more information, have a look at the [OpenFOAM adapter documentation](https://precice.org/adapter-openfoam-overview.html).
I added the version in order to document what version this has been tested with. I guess since it's the newest version I can leave it out, although it might be helpful in the future when newer OpenFOAM versions come out?

2023-05-01 20:02 UTC, tirgendetwas commented on channel-transport/precice-config.xml
>      </participant>
The mapping was moved so that parallel participants can work (following [this](https://precice.org/configuration-mapping.html#restrictions-for-parallel-participants) explanation)

2023-05-02 12:48 UTC, MakisH commented on channel-transport/README.md
> +* OpenFOAM (pimpleFoam): tested with OpenFOAM v2112. For more information, have a look at the [OpenFOAM adapter documentation](https://precice.org/adapter-openfoam-overview.html).
This would be good to document in the IDP report.
It would definitely be nice for the user to know it, but we avoid documenting the version in the tutorials. Reasons include:

1. We typically check that everything keeps running with the latest version supported the adapter, and add notes in the respective tutorial case if not.
2. We anyway don't do thorough validation of all tutorial cases, so as long as it runs and gives reasonable results, this is enough. Of course, we would document every dependency in detail in a publication, especially when we perform some validation.
3. It is considerable effort to update the version compatibility of every case regularly, and cases tend to look outdated, while they are not. Users may even assume the cases don't work with the latest version (or any version they have), and immediately try to install a different one. The compatibility should be dictated by this page: https://precice.org/adapter-openfoam-support.html

Note that we used to document the versions, but we don't do this anymore. If you find any such tutorial, please directly edit to remove the version, or let me know.

2023-05-02 12:50 UTC, MakisH commented on channel-transport/precice-config.xml
>      </participant>
Very good point, thanks! Then, this is relevant and we should keep it.
It only became apparent here, since our Nutils example does not run in parallel.

2023-07-18 13:34 UTC, MakisH commented on channel-transport/precice-config.xml
> +      <mapping:nearest-neighbor
Note for the future reader: I think we need this change, since this case does not have non-conforming meshes. With preCICE v2.5, the initialization takes quite a while with RBF.

@BenjaminRodenberg @davidscn is there any reason to keep the RBF mapping in the channel transport tutorial?

2023-07-21 15:05 UTC, uekerman commented on channel-transport/precice-config.xml
> +      <mapping:nearest-neighbor
Meshes are not non-confirming, but non-matching, no? At least for the Nutils case. `nearest-neighbor` could lead to bad accuracy. Maybe the support radius needs tweaking.

2023-07-21 15:15 UTC, MakisH commented on channel-transport/precice-config.xml
> +      <mapping:nearest-neighbor
I would then suggest to at least run both cases and compare the results.

2023-08-11 07:46 UTC, MakisH requested changes

2023-08-11 07:46 UTC, MakisH commented on channel-transport/transport-nutils/transport.py
>          dt = min(dt, precice_dt)
I think you need to read data at `dt`, not at `precice_dt`. This is the actual time step size your solver is performing.

With time interpolation now enabled by default, you can read values at any requested time. preCICE will interpolate between coupling time windows and give you a value that corresponds to this dt.

2023-08-15 16:54 UTC, MakisH commented on channel-transport/precice-config.xml
> +      <mapping:nearest-neighbor
I ran both the Nutils-Nutils and the OpenFOAM-Nutils combinations, both with RBF and NN.
I did not notice any issues with the initialization time. The slowest step by far was the receiving Nutils participant's simulation, in both mapping cases.

The results I got look the same, but somehow I cannot open the (binary) Nutils VTK results with fieldcompare, at least not with the latest release from PIP.

I suggest reverting back to the RBF mapping, just in case. If runtime becomes an issue, we can adapt.

2023-08-15 17:07 UTC, MakisH approved these changes

2023-08-15 17:07 UTC, merged