Adding FEniCSx solver to partitioned-heat-equation tutorial
precice/tutorials pull request #317
Opened 2022-12-21 11:59 UTC by PhilipHildebrand

This PR is to add a FEniCSx solver that is currently being developed at [https://github.com/precice/fenicsx-adapter](https://github.com/precice/fenicsx-adapter) to the partitioned-heat-equation tutorial. We opted for a minimal working release, so parallel runs and vector-valued functions are not yet supported.

2022-12-22 20:03 UTC, BenjaminRodenberg requested changes
Mostly minor cleanup work (commented out code and todos) and style. Please also make sure to update the `README.md` file of the tutorial case.

2022-12-22 20:03 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/fenicsx/my_enums.py
> +    RECTANGLE = 4  # domain excluding circular part of complex interface case
```suggestion
```
This is not supported, is it?

2022-12-22 20:03 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/fenicsx/problem_setup.py
> +#             return False
?

2022-12-22 20:03 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/fenicsx/problem_setup.py
> +midpoint = (0.5, 0.5, 0)
```suggestion
```
Not supported

2022-12-22 20:03 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/fenicsx/problem_setup.py
> +#             return False
?

2022-12-22 20:03 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/fenicsx/problem_setup.py
> +Problem setup for partitioned-heat-conduction/fenicsx-fenicsx tutorial
```suggestion
Problem setup for partitioned-heat-conduction/fenicsx tutorial
```

2022-12-22 20:12 UTC, BenjaminRodenberg commented
The CI pipeline runs into a problem: https://github.com/precice/fenicsx-adapter/actions/runs/3760782969/jobs/6391868298#step:7:46

Can you reproduce this locally? We can also try to fix this together in our meeting tomorrow.

2023-01-05 12:58 UTC, BenjaminRodenberg commented
> The CI pipeline runs into a problem: https://github.com/precice/fenicsx-adapter/actions/runs/3761247482/jobs/6392790304#step:8:46
> 
> Can you reproduce this locally? We can also try to fix this together in our meeting tomorrow.

This was a problem introduced by some changes I introduced in https://github.com/PhilipHildebrand/fenicsx-adapter/commit/038aa4f9146771be96b018ca5ada86d4bb4bd00c and reverted in https://github.com/precice/fenicsx-adapter/pull/15/commits/8c777c47343a080bae7cff9d1f06e4b483d10842. This should be fine.

2023-01-19 13:26 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/errorcomputation.py
> +    return error_total
See https://github.com/precice/tutorials/pull/317#discussion_r1081254240

2023-01-19 13:27 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +            error = compute_errors(u_n, u_ref, total_error_tol=error_tol)
See https://github.com/precice/tutorials/pull/317#discussion_r1081254240.

2023-01-19 13:27 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +            print('output u^%d and u_ref^%d' % (n, n))
See https://github.com/precice/tutorials/pull/317#discussion_r1081254240.

2023-01-19 13:31 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +'''
Removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181. The [issue](https://github.com/precice/fenicsx-adapter/issues/22) has been added to the fenicsx-adapter repo.

2023-01-19 13:33 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +# f_function.interpolate(f.eval)
Removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:33 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +        return np.full(x.shape[1], self.beta - 2 - 2 * self.alpha)
The members have been removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:34 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +            return np.full(x.shape[1], 2 * x[0])
Removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:34 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +        return np.full(x.shape[1], 1 + x[0] * x[0] + self.alpha * x[1] * x[1] + self.beta * self.t)
Removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:34 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +    '''
Removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:34 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +    '''
Removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:35 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +        # , petsc_options={"ksp_type": "preonly", "pc_type": "lu"})  # TODO is it possible to do that only once (before th coupling-loop)?
Removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:36 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +W = V_g.sub(0).collapse()[0]
Removing it caused an error, so probably yes.

2023-01-19 13:37 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +with XDMFFile(MPI.COMM_WORLD, f"./out/{precice.get_participant_name()}.xdmf", "w") as xdmf:
Changed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:38 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/my_enums.py
> +    RECTANGLE = 4  # domain excluding circular part of complex interface case
No, so it was removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:38 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/problem_setup.py
> +#             return False
Removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:39 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/problem_setup.py
> +midpoint = (0.5, 0.5, 0)
Removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:39 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/problem_setup.py
> +#             return False
Removed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:40 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/problem_setup.py
> +Problem setup for partitioned-heat-conduction/fenicsx-fenicsx tutorial
Changed in https://github.com/precice/tutorials/commit/03e59e73add47150b1e39da6f8a3e40d52fb9181.

2023-01-19 13:40 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +The original source code can be found on https://github.com/hplgit/fenics-tutorial/blob/master/pub/python/vol1/ft03_heat.py.
Changed in https://github.com/precice/tutorials/commit/c636ab6b92db53f2642c408fbf8f142915c4c2f3.

2023-01-20 14:15 UTC, IshaanDesai commented on partitioned-heat-conduction/fenicsx/heat.py
> +ref_out.write_mesh(mesh)
```suggestion
xdmf = XDMFFile(MPI.COMM_WORLD, f"./output/{precice.get_participant_name()}.xdmf", "w")
xdmf.write_mesh(mesh)
ref_out = XDMFFile(MPI.COMM_WORLD, f"./output/ref{precice.get_participant_name()}.xdmf", "w")
ref_out.write_mesh(mesh)
```
Because the cleaning tool looks for the `output` folder.

2023-01-20 14:33 UTC, IshaanDesai reviewed
Looka good :+1: we are almost there.~~ Currently FEniCSx outputs `xdmf` and `h5` files. Do you know how does one view them? Can we output VTK or VTU files? That would be the appropriate output file format if we look at other tutorials.~~

2023-01-20 16:28 UTC, IshaanDesai approved these changes

2023-01-20 16:39 UTC, PhilipHildebrand commented
> Looka good +1 we are almost there. ~Currently FEniCSx outputs `xdmf` and `h5` files. Do you know how does one view them? Can we output VTK or VTU files? That would be the appropriate output file format if we look at other tutorials.~

The XDMF files can be opened with Paraview. From what I can tell, the h5 files are a byproduct of creating the XDMF files and are pretty much irrelevant. I've tried to create VTK files, but they don't show the temperature curve at t=0 for some reason and I don't know why.

2023-01-20 18:55 UTC, PhilipHildebrand commented on partitioned-heat-conduction/fenicsx/heat.py
> +ref_out.write_mesh(mesh)
Changed in https://github.com/precice/tutorials/pull/317/commits/e0a3f4c425f98ce25f00a52b868a83b19aca038a.

2023-01-22 20:43 UTC, IshaanDesai commented
XDMF files can indeed be viewed in ParaView, provided the correct filer is selected. Lets keep this file format now, as it seems that FEniCSx also recommends it. @PhilipHildebrand can you resolve the conflict in the README so that we can merge this PR?

2023-01-23 09:58 UTC, merged