Add FMU version to oscillator example
precice/tutorials pull request #322
Opened 2023-02-05 16:35 UTC by LeonardWilleke

A second version of the oscillator simulation case was implemented using FMU models. 

The python version was changed in one major way: The data that is exchanged between the two participants is no longer the force of the middle spring, but the displacement of the respective masses. This was easier to implement with the FMU models. As both versions share the same precice-config XML, this has to be consistent.

2023-02-17 16:43 UTC, LeonardWilleke commented
The above described change to the python solver was backrolled. Both solvers now use force-force exchange. Additionally, source code and build instructions for the FMU model were added.

2023-03-21 17:04 UTC, LeonardWilleke commented
This case also works with Quasi-Newton acceleration for both solvers (Python, FMI and the combination of both), as long as parallel-implicit coupling is used. For serial-implicit coupling, the simulation fails for both solvers.

2023-03-27 14:13 UTC, uekerman requested changes
Looks good already :+1:

I was able to run the case and had a big-picture look at everything. I did not yet look at `runner.py` in detail since this is probably the wrong place. Or should I already give feedback here? Mid-term goal would be to move `runner.py` to a separate place, right? Should we merge now already or wait till this moving has been done? In the latter case, the documentation needs updating.

I had a look at the configuration though. We still need some tweaking there (see below)

It seems a bit odd to move the fmu source files into a subfolder `cmake`. It this an FMU standard way of doing things? More natural names could be `Oscillator` or `fmu`. In a `cmake` subfolder I would expect CMake files (like here: https://github.com/precice/precice/tree/develop/cmake)

Currently, this tutorial runs with preCICE v2. Apparently the `oscillator` tutorial was not yet updated (correct? @BenjaminRodenberg). Maybe it is indeed simpler to do this later, but let's maybe open an issue on this.

Requires a changelog entry.

2023-03-27 14:13 UTC, uekerman commented on oscillator/fmi/cmake/README.md
> +Then run `make` or your preferred build tool to create the FMU. The model will be in the parent folder.
What do you mean by parent folder here? The current location of `Oscillator.fmu`? This would be too non-standard in my opinion. I would instead add an explicit copy step here. 
Or an install step that copies `Oscillator` to the parent directory via `-DCMAKE_INSTALL_PREFIX="../../"`

2023-03-27 19:17 UTC, BenjaminRodenberg commented
> Currently, this tutorial runs with preCICE v2. Apparently the `oscillator` tutorial was not yet updated (correct? @BenjaminRodenberg). Maybe it is indeed simpler to do this later, but let's maybe open an issue on this.

Yes. [oscillator.py](https://github.com/precice/tutorials/blob/0482e5b4d3e1604dd031d2b113a2aaa63733c9a8/oscillator/python/oscillator.py) still uses the v2 API. I quickly created a PR with the necessary changes to update: https://github.com/precice/tutorials/pull/332

2023-03-28 12:34 UTC, LeonardWilleke commented on oscillator/python/oscillator.py
> +write_data = u0 * np.ones(num_vertices)
This was a typo from my side, it's corrected

2023-03-31 16:21 UTC, LeonardWilleke commented
> I did not yet look at `runner.py` in detail since this is probably the wrong place. Or should I already give feedback here? Mid-term goal would be to move `runner.py` to a separate place, right? Should we merge now already or wait till this moving has been done? In the latter case, the documentation needs updating.

Correct, I'm currently in the process of moving `runner.py` to a separate place. Don't give feedback on this version. I would also wait with the merge until `runner.py` is separated.

2023-03-31 16:29 UTC, LeonardWilleke commented on oscillator/fmi/calculate-error.py
`calculate-error.py` calculates the error between the numeric and the analytic solution. When `run.sh` is used to run the `fmi` solver, `calculate-error.py` is called and the error is printed after the simulation.
`calculate-error.py` is specific to the `fmi` solver because it has to read both the setting and output file to get the parameters. 
The `python` solver calculates the error during the simulation already and prints it after finishing. The parameters are available within the python file but not as a separate file.

2023-03-31 16:33 UTC, LeonardWilleke commented on oscillator/fmi/MassLeft/precice-settings.json
> +    }
I put them into `fmi-settings`. We could think about moving all entries into one setting file, as `precice-settings` now has only very few entries.

2023-04-16 10:10 UTC, uekerman commented on oscillator/fmi/calculate-error.py
:+1: Please briefly document in the README

2023-04-16 10:34 UTC, uekerman requested changes
Looks good, a few more minor remarks.

Biggest issue is that now `develop` of this tutorial was already ported to preCICE v3. I would suggest the following:
- After fixing the remaining issues here, you branch away from here to `create-fmu-oscillator-v2` in your fork.
- We then first release a v2-compatiable version of the runner v0.1. In the README of this version we link to this v2 branch.
- Both these versions (runner and tutorial) go on DaRUS
- Then (after handing in your thesis), we rebase and update here to v3. And then merge after another review.

2023-04-16 10:34 UTC, uekerman commented on oscillator/python/oscillator.py
Let's remove such cosmetic changes from this PR. Otherwise, it gets too complicated to overview.

2023-04-16 10:34 UTC, uekerman commented on oscillator/fmi/fmu/README.md
> +mv ./Oscillator.fmu ../..
```suggestion
cp ./Oscillator.fmu ../..
```

A bit more standard IMO.

2023-04-16 10:34 UTC, uekerman commented on oscillator/fmi/fmu/LICENSE.txt
I would suggest to do the same trick here as in the runner repo:
- Remove you changes from this file. All your changes are licensed under the main license of the tutorials repo.
- Move this license into a `thirdparty` folder and explain in situation in the `fmu/README.md`.

2023-04-16 10:34 UTC, uekerman commented on oscillator/README.md
>  This tutorial is only available in Python. You need to have preCICE and the Python bindings installed on your system.
I would simply replace this sentence with another intro statement ... there are two different implementations ...

2023-05-19 07:37 UTC, uekerman commented
Before merging, we should also still investigate where the difference in results between FMU and Python participants comes from.

2024-01-25 10:25 UTC, LeonardWilleke commented
I prepared a version which runs with preCICE v3 on a separate [branch](https://github.com/LeonardWilleke/precice-tutorials/tree/create-fmu-oscillator-v3)
There, I renamed the enum class `Participant` to `Solver` to avoid confusion with the preCICE instance through the interface class `Participant`.

2024-02-07 09:20 UTC, uekerman commented
> I prepared a version which runs with preCICE v3 on a separate [branch](https://github.com/LeonardWilleke/precice-tutorials/tree/create-fmu-oscillator-v3)

Could you please open a PR for that one? I guess, we then close this PR, right?

2024-02-21 15:47 UTC, uekerman commented
Closing in favor of #465

2024-02-21 15:47 UTC, closed without merging