Partitioned heat conduction with Schwarz-type domain decomposition
precice/tutorials pull request #381
Opened 2023-10-06 07:38 UTC by BenjaminRodenberg

Adds a tutorial illustrating how Schwarz-type domain decomposition could be implemented with preCICE.

General question similar to #30: How can we publish these kind of academic and advanced tutorials in a proper way?

2023-10-11 09:04 UTC, uekerman reviewed
Could we add a picture showing the overlapping domain? I think this could be very helpful to quickly grasp the difference of this tutorial to others.

> How can we publish these kind of academic and advanced tutorials in a proper way?

This discussion will be part of the preECO project. Let's not preempt a decision here. For the moment, what you did looks good.

I did not run the case.

2023-10-11 09:04 UTC, uekerman commented on partitioned-heat-conduction-schwarz/README.md
> +* `heat.py right` flag will run the right participant.
Could you briefly mention the error computation script here and what to expect?

2023-10-11 15:07 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-schwarz/README.md
> +* `heat.py right` flag will run the right participant.
I added a few lines. It's the same like for the Dirichlet-Neumann case: If we do everything right, we are able to approximate the analytical solution up to machine precision (or coupling tolerance).

2024-02-02 15:10 UTC, uekerman approved these changes
Name and README look good enough for me. I did not run the case.

2024-02-02 15:10 UTC, uekerman commented on partitioned-heat-conduction-overlap/README.md
> +keywords: FEniCS, Nutils, Heat conduction
```suggestion
keywords: FEniCS, heat conduction, overlap
```

2024-02-02 15:10 UTC, uekerman commented on partitioned-heat-conduction-overlap/fenics/heat.py
> +# \end{align*}
needs updating

2024-02-02 15:10 UTC, uekerman commented on partitioned-heat-conduction-overlap/precice-config.xml
> +    <data:scalar name="TemperatureRight" />
```suggestion
    <data:scalar name="Temperature-Left" />
    <data:scalar name="Temperature-Right" />
```
would be slightly more consistent

2024-02-02 15:10 UTC, uekerman commented on partitioned-heat-conduction-overlap/images/tutorials-partitioned-heat-conduction-overlap-setup.png
A bit odd to call an overlap region "Gamma", but OK.

2024-02-02 16:46 UTC, MakisH requested changes
I have not tried to run this tutorial, but it anyway needs porting to preCICE v3.

I would also prefer that it already applies the tutorial structure that we have essentially discussed and converged on, which is documented in https://precice.org/community-contribute-to-precice.html

Other than that, it looks clean and clear. I particularly like that you added the TikZ sources for the figure.

2024-02-02 16:46 UTC, MakisH commented on partitioned-heat-conduction-overlap/fenics/heat.py
> +    if precice.is_action_required(precice.action_write_iteration_checkpoint()):
Is this using the FEniCS adapter for preCICE v3?

2024-02-02 16:46 UTC, MakisH commented on partitioned-heat-conduction-overlap/fenics/precice-adapter-config-L.json
> +      "read_data_name": "TemperatureRight"
This is classical Dirichlet-Neumann, right? Strange to call both exchanged fields `Temperature*`. A gradient is needed somewhere.

2024-02-02 16:46 UTC, MakisH commented on partitioned-heat-conduction-overlap/images/tutorials-partitioned-heat-conduction-overlap-setup.tex
Nice that you added the source file of the figure here!

2024-02-02 16:46 UTC, MakisH commented on partitioned-heat-conduction-overlap/precice-config.xml
> +  <solver-interface dimensions="2">
Needs to be ported to preCICE v3

2024-02-02 16:46 UTC, MakisH commented on partitioned-heat-conduction-overlap/fenics/heat.py
We have already discussed this in other occasions, but this is another example of a tutorial that has a directory structure based on the solver and not on the participant.

An easy split here would be:

- `fenics-solver`:
   - `heat.py`
   - `errorcomputation.py`
- `left-fenics`:
   - `precice-adapter-config-left.json`
   - `run.sh` (without options)
   - `clean.sh`   
- `right-fenics`:
   - `precice-adapter-config-right.json`
   - `run.sh` (without options)
   - `clean.sh`

2024-02-04 17:48 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-overlap/precice-config.xml
> +    <data:scalar name="TemperatureRight" />
Done. 91d552d9af2170a5175309e465eaf6f7ced9ea2b

2024-02-04 18:15 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-overlap/images/tutorials-partitioned-heat-conduction-overlap-setup.png
The overlap region is the shaded region and called $\Omega_\mathcal{L} \cap \Omega_\mathcal{R}$. $\Gamma_\mathcal{L}$ and $\Gamma_\mathcal{R}$ are only the boundaries where we set the Dirichlet BCs. But I moved the labels a bit to make things clearer.

2024-02-04 18:17 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-overlap/fenics/heat.py
> +    if precice.is_action_required(precice.action_write_iteration_checkpoint()):
No. I think this has just been lying around too long.

2024-02-04 18:35 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-overlap/fenics/precice-adapter-config-L.json
> +      "read_data_name": "TemperatureRight"
No. It is Schwarz. Here, you have an overlap region and exchange Dirichlet BCs. See https://en.wikipedia.org/wiki/Schwarz_alternating_method

2024-02-04 18:44 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-overlap/precice-config.xml
> +  <solver-interface dimensions="2">
Done :+1:

2024-02-04 18:44 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-overlap/fenics/heat.py
Done :+1:

2024-02-04 18:44 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-overlap/fenics/heat.py
> +    if precice.is_action_required(precice.action_write_iteration_checkpoint()):
Done with update.

2024-02-04 18:50 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-overlap/fenics/heat.py
> +# \end{align*}
Done.

2024-02-05 07:58 UTC, MakisH commented on partitioned-heat-conduction-overlap/fenics/precice-adapter-config-L.json
> +      "read_data_name": "TemperatureRight"
Hmmm.... I was probably (mentally) absent during the respective NumPro lecture... :see_no_evil:

2024-02-05 08:18 UTC, MakisH approved these changes
The new structure is nice! :+1:
I ran the code, no VTK files are produced (as expected, I supposed).
I then executed the `solver-fenics/errorcomputation.py` and got no output, which confused me but means that the assertion worked.

2024-02-05 08:18 UTC, MakisH commented on partitioned-heat-conduction-overlap/README.md
> +Like for the case `partitioned-heat-conduction` (using Dirichlet-Neumann coupling), we can also expect for the overlapping domain decomposition applied here to recover the analytical solution. `error
```suggestion
Like for the case `partitioned-heat-conduction` (using Dirichlet-Neumann coupling), we can also expect for the overlapping domain decomposition applied here to recover the analytical solution. The script `solver-fenics/errorcomputation.py` checks this explicitly, by comparing the numerical to the analytical solution and raising an error, if the approximation error is not within a given tolerance.
```

2024-02-05 08:18 UTC, MakisH commented on partitioned-heat-conduction-overlap/solver-fenics/errorcomputation.py
> +    assert (error_total < total_error_tol)
Would it make sense to still print a message on success?
I ran this script, semi-following the documentation, but I was not sure what the absence of output meant.

2024-02-05 08:23 UTC, MakisH commented on partitioned-heat-conduction-overlap/README.md
> +
The clarification you have in the oscillator-overlap tutorial would also be helpful here:

```suggestion

Note that this case applies an overlapping Schwarz-type coupling method and not (like most other tutorials in this repository) a Dirichlet-Neumann coupling. This results in a symmetric setup of the solvers.

```

You can even extend this explaining how you name the participants and that they both exchange temperature.

2024-02-05 22:08 UTC, BenjaminRodenberg commented on partitioned-heat-conduction-overlap/solver-fenics/errorcomputation.py
> +    assert (error_total < total_error_tol)
Not sure. I think it is ok the way it is (we also have it this way for the other heat conduction flavors).

2024-02-05 22:28 UTC, BenjaminRodenberg commented
> I ran the code, no VTK files are produced (as expected, I supposed).

I don't completely understand this. I get VTK output...?

![Screenshot from 2024-02-05 23-27-53](https://github.com/precice/tutorials/assets/5740604/a6fef5fc-1bfc-4cd3-9b11-8bbf154217d2)

2024-02-05 22:29 UTC, merged

2024-02-06 09:11 UTC, MakisH commented on partitioned-heat-conduction-overlap/solver-fenics/errorcomputation.py
> +    assert (error_total < total_error_tol)
I am a user.
I got confused.
The _"we also have it this way for the other heat conduction flavors"_ does not mean that I wouldn't get confused in those as well... :see_no_evil:

2024-02-06 09:14 UTC, MakisH commented
> > I ran the code, no VTK files are produced (as expected, I supposed).
> 
> I don't completely understand this. I get VTK output...?

I guess I overlooked the `output/` folder, used to having the Nutils output in the same directory. But this is not our Nutils tutorials.