Add solid fake for perpendicular flap tutorial
precice/tutorials pull request #541
Opened 2024-06-17 19:03 UTC by NiklasVin

I added a solid fake implemented in Python to the perpendicular flap tutorial, similar to the already existing fluid-fake.

2024-06-24 08:50 UTC, MakisH commented
Is this ready for review?
Don't forget to add it into the README of the tutorial. I can generate some of the plots when reviewing.

I will fix the markdownlint, it is failing also elsewhere.

2024-06-27 06:39 UTC, MakisH commented
@NiklasVin please rebase/merge from develop, the markdownlint issue is now fixed.

2024-06-28 22:49 UTC, NiklasVin commented
> Is this ready for review? Don't forget to add it into the README of the tutorial. I can generate some of the plots when reviewing.
> 
> I will fix the markdownlint, it is failing also elsewhere.

Yes, now this should be ready for review.

2024-07-02 07:27 UTC, MakisH commented
@NiklasVin can you please enable edits by maintainers? It's a checkbox on the right.

2024-07-02 07:48 UTC, MakisH commented on perpendicular-flap/solid-fake/fake.py
> +import precice
Please add a `requirements.txt` and a `run.sh`, same as in the `fluid-fake`.
See also #548 for an update.

2024-07-02 07:49 UTC, MakisH commented on perpendicular-flap/solid-fake/fake.py
> +vertex_ids = interface.set_mesh_vertices(mesh_name, vertices_mid)
Trying to run the `solid-fake`, either with `fluid-fake` or with `fluid-openfoam`, I got the following error (preCICE 3.1.2):

```
---[precice] ERROR:  The interpolation matrix of the RBF mapping from mesh "Solid-Mesh" to mesh "Fluid-Mesh" is not invertable. This means that the mapping problem is not well-posed. Please check if your coupling meshes are correct (e.g. no vertices are duplicated) or reconfigure your basis-function (e.g. reduce the support-radius).
```

2024-08-15 13:01 UTC, NiklasVin commented on perpendicular-flap/solid-fake/fake.py
> +vertex_ids = interface.set_mesh_vertices(mesh_name, vertices_mid)
This problem should be fixed now

2024-08-16 09:43 UTC, BenjaminRodenberg requested changes
I checked the case with `fluid-openfoam`. Generally runs and VTK output looks good. Only a minor point is left.

2024-08-16 09:43 UTC, BenjaminRodenberg commented on perpendicular-flap/solid-fake/fake.py
> +        return 0.5 * t
```suggestion
def displacement_param(t):
    # this parameter exists to define a time-dependent displacement of the flap's tip
    max_d = 0.5
    if t > 1:
        return max_d
    else:
        return max_d * t
```
To avoid code duplication.

You could also do `min(max_d, max_d*t)` but I personally prefer the `if...else`-way of writing things.

2024-08-16 09:43 UTC, BenjaminRodenberg commented on perpendicular-flap/solid-fake/fake.py
> +interface.initialize()
Can you add a few lines above to provide initial data? Compare [here](https://github.com/precice/tutorials/blob/0df4f0085a3aca71f42e7806dc3d762eab54624c/perpendicular-flap/fluid-fake/fake.py#L34-L38). It's not required by the `precice-config.xml` of this case but if we initialize data this makes the script more flexible and I assume you also still remember all the pain we had with `fluid-fake` and missing initial data :smirk:

2024-08-16 09:49 UTC, BenjaminRodenberg commented on perpendicular-flap/solid-fake/fake.py
> +    x_displ = np.minimum(((np.sin(3 * np.pi * t + np.arcsin(-0.95)) + 0.95) / 8) * y / flap_tip_y, 0.5 * y / flap_tip_y)
```suggestion
    # first, get displacement independent of x, only dependent on y and t
    # initially, flap's displacement is 0
    max_x_displacement = 0.5
    x_displ = np.minimum(((np.sin(3 * np.pi * t + np.arcsin(-0.95)) + 0.95) / 8) * y / flap_tip_y, max_x_displacement * y / flap_tip_y)
```

I would generally try to avoid raw numbers and rather use descriptive names. This often allows you to completely save some comments.

What does the `0.95`, the `3 * np.pi` and the `/8` do? Generally, I think if the formula you are using here works we can keep it. But a brief comment about the general rationale behind the `arcsin` and `sin` would be helpful.

2024-08-16 09:50 UTC, BenjaminRodenberg commented on perpendicular-flap/solid-fake/fake.py
> +    displ = np.zeros((len(x), 2))
```suggestion
    dimensions = 2
    displ = np.zeros((len(x), dimensions))
```
Again: Makes it more explicit that this only works in 2D.

2024-08-16 09:51 UTC, BenjaminRodenberg commented on perpendicular-flap/solid-fake/fake.py
> +vertices[n:, 0] = x_right
```suggestion
# define n vertices for left / upstream side of flap
vertices[:n, 1] = np.linspace(y_bottom, y_top, n)
vertices[:n, 0] = x_left
# define n vertices for right / downstream side of flap
vertices[n:, 1] = np.linspace(y_bottom, y_top, n)
vertices[n:, 0] = x_right
```

2024-08-16 09:52 UTC, BenjaminRodenberg commented on perpendicular-flap/solid-fake/fake.py
> +        return 0.5 * t
I think this was somehow cached. Cannot find this piece of code anymore and is not relevant.

2024-08-19 11:09 UTC, NiklasVin commented on perpendicular-flap/solid-fake/fake.py
> +    x_displ = np.minimum(((np.sin(3 * np.pi * t + np.arcsin(-0.95)) + 0.95) / 8) * y / flap_tip_y, 0.5 * y / flap_tip_y)
I added some comments that hopefully clarify the idea behind the formula

2024-08-19 12:30 UTC, BenjaminRodenberg approved these changes
Thank for the changes! Looks good now. Let's get this merged :tada:

2024-08-19 12:31 UTC, merged