pySDC & FEniCS solver for partitioned-heat-equation
precice/tutorials pull request #557
Opened 2024-08-22 09:29 UTC by TobiasEppacher

- Addition of a solver program for the `partitioned-heat-equation' tutorial, based on pySDC

2024-08-22 12:38 UTC, BenjaminRodenberg requested changes
Hi @TobiasEppacher! Thanks for opening this PR. Can you please run `autopep8` on your code? Currently the CI is failing due to some formatting issues. Simply install `autopep8` and use the arguments given [here](https://github.com/precice/tutorials/blob/293c25b9595c4f7a055a228517664166d806c272/.pre-commit-config.yaml#L18).

I did not test the functionality yet but generally it already looks good. The way how you are implementing pySDC into the solver really looks good and is not invasive at all. With some refactoring we can make this even clearer.

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/dirichlet-pySDC-fenics/precice-adapter-config.json
Is this JSON file identical to the one provided in `dirichlet-fenics`?

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/dirichlet-pySDC-fenics/clean.sh
Is this `clean.sh` file identical to the one provided in `dirichlet-fenics`?

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/dirichlet-pySDC-fenics/run.sh
> +python3 ../solver-fenics/heat_pySDC.py Dirichlet
The only difference to the `run.sh` file in `dirichlet-fenics` is that you use `../solver-fenics/heat_pySDC.py` instead of `../solver-fenics/heat.py`. Correct?

I think we could actually live without `dirichlet-pySDC-fenics` and put everything into `dirichlet-fenics`. Maybe you could add an optional argument to the `run.sh` file such that `./run.sh` runs the "normal" case and `./run.sh sdc` would use `heat_pySDC.py` instead of `heat.py`.

@MakisH Does this approach fit into our framework?

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +precice_time_window_size = 0.1
This is something that we should get from the precice config. Please use the following:
```suggestion
precice_time_window_size = precice.get_max_time_step_size()
```
Note: At the beginning of the window the max step size equals the window size.

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +pySDC_dt = precice_time_window_size/precice_waveform_deg
Why do you need the degree? There is no API function to get the degree from preCICE.

I think it should be the other way around: Your time stepping scheme has certain requirements and then the user should be able to configure preCICE in a way that fulfills the requirements.

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +##################################################################
I'm not a big fan of this "section"-style. Is it possible to put this into a function with an descriptive name? This also makes it clearer which configuration parameters come from the outside and which ones are local.

Example:

```
def create_pysdc_controller(dt, ...):
    ...
    # REVIEW COMMENT: These are some local parameters that we can hide from the outside context
    # initialize sweeper parameters
    sweeper_params = dict()
    sweeper_params['quad_type'] = 'LOBATTO'
    sweeper_params['num_nodes'] = 4
    ...
    return controller

... # usual stuff before coupling loop

contoller = create_pysdc_controller(pySDC_dt, ...)

... # enter coupling loop
```

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +P = controller.MS[0].levels[0].prob
```suggestion
```
Is this actually needed?

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +    P.set_t_start(t)
Ok. Here `P` is used. I would actually consider writing the following instead:

```suggestion
    controller.MS[0].levels[0].prob.set_t_start(t)
```

Yes. This is a bit more lengthy but it saves you one indirection and clarifies the connection to the controller.

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +    u_np1 = uend.values
You could consider putting these lines into a function `u_np1 = do_time_step(controller, u_n, t, dt)`. This is the only point where you interact with pySDC? Really nice that the interface is so clean.

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +    uend, stats = controller.run(u_n, t0=t, Tend=t + float(dt))
```suggestion
    uend, _ = controller.run(u_n, t0=t, Tend=t + float(dt))
```
It's convention in python to replace unused variables with a `_`. You do not use `stats`, do you?

Even better would be `uend = controller.run(...)` but I guess the function always returns two values. In this case ignoring the `stats` and only keeping the `uend` is cleaner.

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +u_D_sp = 1 + x_sp * x_sp + alpha * y_sp * y_sp + beta * (t_sp ** temporal_deg)
This, for example, is one difference to `heat.py`, but integrating this feature into `heat.py` is not difficult. Again: We could add an option parameter `heat.py --polynomial-degree=123` that defaults to `1`.

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +    def __init__(self, mesh, function_space, forcing_term_expr, solution_expr, coupling_boundary, remaining_boundary, coupling_expr, precice_ref, participant_name):
Can you add a docstring here and explain the arguments? See https://peps.python.org/pep-0257/#multi-line-docstrings.

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +        """
I've never seen a docstring starting with `r"""` before. Is this the documentation style in pySDC? Is the latex code rendered on the website or similar?

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +        self.t_start = t_start
Hmm... not sure if you should actually use a function here. Why not simply call `controller.t_start = new_t_start` instead of this function in `heat_pySDC.py`? Currently, this function does not really add a lot of additional value (no additional logic, security checks, documentation...).

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +        return me
```suggestion
        return self.dtype_u(interpolate(self.solution_expr, self.V), val=self.V)
```
Would be shorter. Or any reasons for doing it differently?

PS: If this is convention in pySDC. Ok, since you are also doing it similarly in `apply_mass_matrix`

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +        return None
```suggestion
```
I think you don't need this.

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +            self.couplingBC.apply(T, b.values.vector())
From the perspective of coupling this is probably the most interesting part. Would be helpful to point to your thesis here or somewhere in the documentation. I guess you are explaining these few lines of code in detail in your thesis?

2024-08-22 12:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +import dolfin as df
```suggestion
import fenics
```
Generally, I would suggest to avoid wildcard imports. See https://stackoverflow.com/questions/3615125/should-wildcard-import-be-avoided.

Do you really need to import `dolfin`? Usually all the relevant functions from `dolfin` are also in `fenics` (which is to my understanding the high-level wrapper).

What I usually do:
```
from fenics import function_that_I_use, another_function_that_I_use, ...
```
Then you also do not have to bother with all the `fenics.some_fenics_function_I_use_but_did_not_import(...)` below and just call `some_fenics_function_I_imported(...)`

2024-08-24 09:14 UTC, TobiasEppacher commented on partitioned-heat-conduction/dirichlet-pySDC-fenics/clean.sh
Yes, it is identical

2024-08-24 09:14 UTC, TobiasEppacher commented on partitioned-heat-conduction/dirichlet-pySDC-fenics/precice-adapter-config.json
Also this one is identical

2024-08-28 08:11 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +description['step_params'] = step_params
I'm wondering a bit about how you are creating this dictionary. 

Instead of
 
```python
my_a = dict()
my_a['b'] = 42

description = dict()
description['a'] = my_a
```

I would suggest

```python
description = {
    'a': {
        'b':42
         }
}
```

This makes reading much easier, since you are going from top ('description') to bottom ('42') and not from in a zig-zag-fashion bottom  to top (first 'a', then 'b', then 'description').

For spacing and line breaks I would suggest to look for formatting suggestions. Some examples are here: https://stackoverflow.com/questions/44689546/how-to-print-out-a-dictionary-nicely-in-python

2024-08-28 14:09 UTC, TobiasEppacher commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +description['step_params'] = step_params
Changed in new commit

2024-08-28 14:09 UTC, TobiasEppacher commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +import dolfin as df
Fixed

2024-08-28 14:10 UTC, TobiasEppacher commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +pySDC_dt = precice_time_window_size/precice_waveform_deg
This was a remnant of the testing for my thesis. I removed it in the latest commit.

2024-08-28 14:14 UTC, TobiasEppacher commented on partitioned-heat-conduction/dirichlet-pySDC-fenics/run.sh
> +python3 ../solver-fenics/heat_pySDC.py Dirichlet
I tried to unify the run-scripts for the default first-order FEniCS and my pySDC implementation. It would now work using an argument to the bash script which also includes Niklas Vinnitchenkos high-order FEniCS solver (`highorder' or `sdc', everything else or no argument executes the first-order FEniCS solver)

2024-08-29 18:26 UTC, BenjaminRodenberg requested changes
I think you can simplify the code.

2024-08-29 18:26 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +    participant_name=precice.get_participant_name(),
```suggestion
```
I think you do not need this: You are handing over `precice`. So you can also just call `precice.get_participant_name()` inside `setup_problem`. Same argumentation also holds for `__init__`

2024-08-29 18:26 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +        participant_name,
```suggestion
```

2024-08-29 18:26 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +    :param participant_name: name of the participant
```suggestion
```

2024-08-29 18:26 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +            'participant_name': participant_name
```suggestion
            'participant_name': precice.get_participant_name()
```
But maybe you do not even need this?

2024-08-29 18:26 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +                 remaining_boundary, coupling_expr, precice_ref, participant_name):
```suggestion
                 remaining_boundary, coupling_expr, precice_ref):
```

2024-08-29 18:26 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +            participant_name: Name of the participant (Dirichlet or Neumann)
```suggestion
```

2024-08-29 18:26 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +        self.participant_name = participant_name
```suggestion
        self.participant_name = self.precice.get_participant_name()
```
Or completely remove `self.participant_name` and just call `self.precice.get_participant_name()`? The operation is not costly and it also helps you to avoid bugs if you avoid storing redundant data.

2024-08-29 18:26 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +        if self.participant_name == 'Dirichlet':
See above

2024-08-29 18:26 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +        if self.participant_name == 'Dirichlet':
See above

2024-08-29 18:29 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +    domain_mesh=domain_mesh,
I believe you can also simplify your code here: The `mesh` is accessible via the `FunctionSpace` using `FunctionSpace.mesh()`.

2024-08-29 18:46 UTC, BenjaminRodenberg requested changes
I just spotted another simplification of the code. Sorry for the messy review...

2024-08-29 18:46 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +    coupling_expression=coupling_expression,
I think providing a list of `DirichletBC`s here would allow you to simplify your code quite a bit. Additionally, we could also do something along the following lines in the future:

If Dirichlet problem
```
setup_problem(
    ...
    dirichlet_bcs = [a vector of DirichletBC]
    neumann_bcs = [a vector of Expressions+SubDomains]
    ...
)
```
Both arguments would be optional. Additionally, pySDC should not have to worry whether a `DirichletBC` comes from a `coupling_expression` or not.

If you ignore the Neumann part:
```
setup_problem(
    ...
    dirichlet_bcs = [DirichletBC(V, coupling_expression, coupling_boundary),DirichletBC(V, u_D, remaining_boundary)]
    ...
)
```

2024-08-29 18:46 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +        self.remainingBC = DirichletBC(self.V, solution_expr, remaining_boundary)
See my other comment. I think we could completely skip this part.
```suggestion
```

2024-08-29 18:46 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +                read_data)    # Update the coupling expression
This part is a bit tricky. So we definitely need a handle to the `coupling_expression`

2024-08-29 18:46 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +        self.remainingBC.apply(T, b.values.vector())
```suggestion
```
Could be removed. See below.

2024-08-29 18:46 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +            self.couplingBC.apply(T, b.values.vector())  # Apply the coupling boundary condition
Assuming `self.dirichlet_bcs` is a list of all `DirichletBC`s. I don't think we need to differentiate between coupling and non-coupling BCs.

```suggestion
    for bc in self.dirichlet_bcs:
        bc.apply(T, b.values.vector())  # Apply all Dirichlet boundary conditions
```

2024-08-30 07:38 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/dirichlet-fenics/run.sh
> +fi
@MakisH any comments here? I think it is generally a good idea to make the higher-order time-stepping schemes more accessible. The simple `./run.sh` still behaves as before.

2024-08-30 09:05 UTC, MakisH commented on partitioned-heat-conduction/dirichlet-fenics/run.sh
> +fi
Having a default option + more options is totally fine, since there is a default that one can run without reading the details. :+1:

I have not tested this, but if shellcheck passes and you have tested all options, I don't see anything else to check.

2024-08-30 09:07 UTC, MakisH commented on partitioned-heat-conduction/dirichlet-pySDC-fenics/run.sh
> +python3 ../solver-fenics/heat_pySDC.py Dirichlet
See https://github.com/precice/tutorials/pull/557#discussion_r1738261556, I think the approach with the default+more options is nice.

2024-08-30 09:23 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/dirichlet-fenics/run.sh
> +fi
Still have to do the testing, but that's on my list for today. Then let's resolve this and keep it here.

2024-08-30 13:56 UTC, TobiasEppacher commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +    coupling_expression=coupling_expression,
The idea is good, but it won't reduce the complexity, as the expressions for the DirichletBCs have to be updated within the problem class if they are time-dependent. This is already the case with `self.solution_expr.t = t` before the application of the `DirichletBC` for the remaining boundary.
Similarly we would need to pass the `Expression` objects for any other DirichletBC into the problem class anyways to update them.

2024-08-30 14:23 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +    coupling_expression=coupling_expression,
True. Let's keep this refactoring out of this PR and wrap up.

2024-08-30 14:31 UTC, BenjaminRodenberg approved these changes
Minor renaming. Rest looks good and will take care of merging after some final tests.

2024-08-30 14:31 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/dirichlet-fenics/run.sh
> +            echo "      *        : For every other input run the simulation with default FEniCS implementation"
```suggestion
            echo "      irk : Run simulation with higher-order implicit Runge-Kutta schemes FEniCS implementation"
            echo "      sdc : Run simulation with pySDC+FEniCS implementation"
            echo "      *   : For every other input run the simulation with default FEniCS implementation"
```
`irk` instead of `highorder` because `sdc` is actually also high order. The `irk` in irksome (which was a template for Niklas' work) actually stands for Implicit Runge Kutta.

2024-08-30 14:31 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/dirichlet-fenics/run.sh
> +            echo "Running simulation with higher order FEniCS implementation"
```suggestion
        irk)
            echo "Running simulation with higher-order implicit Runge-Kutta schemes FEniCS implementation"
```

2024-08-30 14:37 UTC, MakisH commented on partitioned-heat-conduction/solver-fenics/requirements.txt
```
Running simulation with pySDC+FEniCS implementation
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/home/gc/repos/precice/tutorials/partitioned-heat-conduction/dirichlet-fenics/../solver-fenics/heat_pySDC.py", line 44, in <module>
    from pySDC.implementations.sweeper_classes.imex_1st_order_mass import imex_1st_order_mass
ModuleNotFoundError: No module named 'pySDC'
```

2024-08-30 16:33 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/requirements.txt
I got pySDC installed and the script working. Installation is, unfortunately, no fun since we cannot use the pySDC from pip but need to use the develop version from github. Additionally the develop version on github has some breaking changes. But the latest release `5.5.0` is still ok.

The pip pySDC package is still useful to install the dependencies.

The whole installation process is far from ideal but since the sdc time stepping is experimental and quite a niche feature I think we can live with this.

I will document this installation procedure that finally worked out for me and then I think we can merge.

2024-08-30 16:46 UTC, MakisH commented on partitioned-heat-conduction/solver-fenics/requirements.txt
What if we just `pip install git+https://github.com/...@tag`?

2024-08-30 17:04 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/requirements.txt
Good idea. Will try this next week. I came up with a different solution: [d6a950f](https://github.com/precice/tutorials/pull/557/commits/d6a950f96733f0e908c149946942d384334fb0fc)

2024-08-30 17:08 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/requirements.txt
`pip install git+https://github.com/Parallel-in-Time/pySDC@5.5.0` could actually lead us somewhere but I have to go now and try this next week. Thanks for the hint!

2024-09-02 08:55 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/requirements.txt
With `pip install git+...` the case works nicely in a `.venv`.

2024-09-02 08:59 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/dirichlet-fenics/run.sh
> +            pip install pySDC~=5.4
I will take care of compatibility with `pySDC@develop/5.5.0` directly on develop. I would like to merge this PR first to make sure it's compatible with Tobias' work (he was using 5.4.something).

Only minor changes are required:

```diff
diff --git a/partitioned-heat-conduction/dirichlet-fenics/run.sh b/partitioned-heat-conduction/dirichlet-fenics/run.sh
index b75e8c84..1f7bcb9c 100755
--- a/partitioned-heat-conduction/dirichlet-fenics/run.sh
+++ b/partitioned-heat-conduction/dirichlet-fenics/run.sh
@@ -28,8 +28,8 @@ else
             ;;
         sdc)
             # install pySDC + its dependencies only if needed
-            pip install git+https://github.com/Parallel-in-Time/pySDC@5.4.3
-            pip install pySDC~=5.4
+            pip install git+https://github.com/Parallel-in-Time/pySDC@5.5.0
+            pip install pySDC~=5.5
             echo "Running simulation with pySDC+FEniCS implementation"
             python3 ../solver-fenics/heat_pySDC.py Dirichlet
             ;;
diff --git a/partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py b/partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
index ab952c20..7adb896e 100644
--- a/partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
+++ b/partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
@@ -10,11 +10,11 @@ from fenics import TrialFunction, TestFunction, dx, assemble, inner, nabla_grad,
 from my_enums import ProblemType
 
 
-from pySDC.core.Problem import ptype
+from pySDC.core.problem import Problem
 from pySDC.implementations.datatype_classes.fenics_mesh import fenics_mesh, rhs_fenics_mesh
 
 
-class fenics_heat_2d(ptype):
+class fenics_heat_2d(Problem):
     dtype_u = fenics_mesh
     dtype_f = rhs_fenics_mesh
```

2024-09-02 09:00 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +u_D_sp = 1 + x_sp * x_sp + alpha * y_sp * y_sp + beta * (t_sp ** temporal_deg)
I will take care of this after merging.

2024-09-02 09:03 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC.py
> +    uend, stats = controller.run(u_n, t0=t, Tend=t + float(dt))
Fixed. e889225ca17bee24f04072239004552831f7068d.

2024-09-02 10:03 UTC, BenjaminRodenberg commented on partitioned-heat-conduction/solver-fenics/heat_pySDC_problem_class.py
> +            self.couplingBC.apply(T, b.values.vector())
Tobias mentions this in his thesis. But we cannot link to his thesis yet. So this is to some degree a hen-and-egg problem. Let's take care of this in #560.

2024-09-02 11:14 UTC, MakisH approved these changes
The current state works for me (`./run.sh sdc` installs everything in a venv and completes). However, if I run it again, it seems like PIP downloads the same extra packages again.

![sdc](https://github.com/user-attachments/assets/39151767-f0c1-43f5-a73b-1e655594ca60)

2024-09-02 11:39 UTC, BenjaminRodenberg commented
> However, if I run it again, it seems like PIP downloads the same extra packages again.

Maybe due to the `git` install? But let's keep it as it is and we can come back to this if it becomes problematic. SDC is quite niche and if we have some stable-but-not-perfect way to run things it's good enough. Will merge now. Thanks @TobiasEppacher for the very nice contribution! Of course, also thanks @MakisH for the valuable input!

2024-09-02 11:40 UTC, merged