`oscillator-overlap`: Make consistent with `oscillator`
precice/tutorials pull request #597
Opened 2024-11-21 18:00 UTC by BenjaminRodenberg

Updates `oscillator-overlap` to use time stepping schemes and typing like in `oscillator`

Checklist:

- [ ] I added a summary of any user-facing changes (compared to the last release) in the `changelog-entries/<PRnumber>.md`.
- [ ] I will remember to squash-and-merge, providing a useful summary of the changes of this PR.

2024-11-21 18:56 UTC, BenjaminRodenberg commented on oscillator-overlap/solver-python/oscillator.py
> -write_data = connecting_spring.k * u0 * np.ones(num_vertices)
This is actually a bug: In `oscillator` we exchange forces. Writing displacement * spring stiffness is correct. Compare https://github.com/precice/tutorials/blob/dea77cbfdbc3d5bdc0df1e745bbc3c3c5ed2b2d4/oscillator/solver-python/oscillator.py#L77. In this case, i.e. `oscillator-overlap` we have to write displacements. The multiplication with `connecting_spring.k` is incorrect.

2024-11-26 16:01 UTC, uekerman approved these changes
Makes sense to me. I did not look into the details and did not run the case.

2024-11-26 16:01 UTC, uekerman commented on changelog-entries/597.md
> +- Offer Runge-Kutta 4 scheme and black-box time-stepping with RadauIIA scheme in oscillator-overlap case. Demonstrates use of time interpolation and dense output.
```suggestion
- Added Runge-Kutta 4 scheme and black-box time-stepping with RadauIIA scheme as options to oscillator-overlap case. This demonstrates use of time interpolation and dense output.
```

2024-11-27 09:46 UTC, NiklasVin requested changes

2024-11-27 09:46 UTC, NiklasVin commented on oscillator-overlap/solver-python/oscillator.py
> +from timeSteppers import TimeStepper, TimeSteppingSchemes, GeneralizedAlpha, RungeKutta4, RadauIIA
The `timeSteppers` module is missing.

2024-11-27 09:46 UTC, NiklasVin commented on oscillator-overlap/solver-python/oscillator.py
> +parser.add_argument(
This comment is more of a general usability concern of this feature : Assuming the user wants to use a different time stepping scheme but wants to use the `run.sh` files only, then, as far as I can see, the time stepping scheme cannot be changed.

2024-11-27 09:59 UTC, BenjaminRodenberg commented on oscillator-overlap/solver-python/oscillator.py
> +from timeSteppers import TimeStepper, TimeSteppingSchemes, GeneralizedAlpha, RungeKutta4, RadauIIA
Fixed. Thanks for checking!

2024-11-27 10:01 UTC, BenjaminRodenberg commented on oscillator-overlap/solver-python/oscillator.py
> +parser.add_argument(
True. However, in `tutorials/oscillator` we also do not offer the option to select a different time stepping scheme using the `run.sh` script. Therefore, I would keep it as it is and not add a new feature here.

2024-11-27 10:04 UTC, NiklasVin approved these changes
Now everything works 👍

2024-11-27 10:04 UTC, merged