Partitioned heat conduction (G+Smo participant)
precice/tutorials pull request #604
Opened 2024-12-04 15:14 UTC by Crazy-Rich-Meghan

Summary: Partitioned heat conduction G+Smo (IsoGeometric Analysis) participant
**NOTE**: G+Smo adapter is a submodule of the G+Smo library, to run the tutorial you need to configure G+Smo main library. 
- [x] Updated README.md file, which contains instructions on how to configure G+Smo library with preCICE adapter.
- [x] Added gismo-executable folder to contain the symbolic link for the G+Smo executable.

This PR is marked as a draft because the documentation for the G+Smo adapter requires updates.

2024-12-10 17:05 UTC, uekerman commented
Let's first iterate on #603 and then here, OK?

2025-07-17 14:12 UTC, MakisH commented
@Crazy-Rich-Meghan do you plan to continue this development? It seems to currently be in draft state. We are happy to help get it in a good state!

2025-09-10 22:40 UTC, Crazy-Rich-Meghan commented
Hi everyone,

Sorry for the delay! I have updated the partitioned heat conduction example from our side, this version supports the direct mesh access feature. To run the benchmark you need to do the following:
    1. Clone G+Smo 
    2.  `cmake .. -DCMAKE_BUILD_TYPE=Release -DGISMO_OPTIONAL="gsPreCICE"`
    3. `cmake --build build --target partitioned-heat-conduction -j`
    4.  Install this example systemwide `make install partitioned-heat-conduction`
    5. Go to the `neumann-gismo` folder run the Neumann participant with the run script.
    6. Go to the `dirichlet-gismo` folder run the Dirichlet participant with the run script.

Let me know if you get stuck somewhere!

2025-10-07 15:06 UTC, MakisH commented
Hi @Crazy-Rich-Meghan,

thanks for the updates! I am now trying to build on my system, based on the stable branch (Commit [ef4c754785cf4949d3a89b916eed807b74b97a9b](https://github.com/gismo/gismo/commit/ef4c754785cf4949d3a89b916eed807b74b97a9b), October 2).

I do get a building error, though (`g++ (Ubuntu 12.3.0-1ubuntu1~22.04.2) 12.3.0`):

```
[ 97%] Building CXX object optional/gsPreCICE/examples/CMakeFiles/partitioned-heat-conduction.dir/partitioned-heat-conduction.cpp.o
/home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp: In function ‘int main(int, char**)’:
/home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:110:17: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
  110 |     for (; domIt->good(); domIt->next(), k++ )
      |                 ^~
/home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:110:32: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
  110 |     for (; domIt->good(); domIt->next(), k++ )
      |                                ^~
/home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:120:15: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
  120 |     for (domIt->reset(); domIt->good(); domIt->next(), k++ )
      |               ^~
/home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:120:31: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
  120 |     for (domIt->reset(); domIt->good(); domIt->next(), k++ )
      |                               ^~
/home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:120:46: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
  120 |     for (domIt->reset(); domIt->good(); domIt->next(), k++ )
      |                                              ^~
/home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:124:29: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
  124 |         QuRule->mapTo( domIt->lowerCorner(), domIt->upperCorner(),
      |                             ^~
/home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:124:51: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
  124 |         QuRule->mapTo( domIt->lowerCorner(), domIt->upperCorner(),
      |                                                   ^~
gmake[3]: *** [optional/gsPreCICE/examples/CMakeFiles/partitioned-heat-conduction.dir/build.make:76: optional/gsPreCICE/examples/CMakeFiles/partitioned-heat-conduction.dir/partitioned-heat-conduction.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:1940: optional/gsPreCICE/examples/CMakeFiles/partitioned-heat-conduction.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:1947: optional/gsPreCICE/examples/CMakeFiles/partitioned-heat-conduction.dir/rule] Error 2
gmake: *** [Makefile:907: partitioned-heat-conduction] Error 2
```

By the way, I edited your instructions above to add a number next to the `-j` flag. Without a number, it will use as many threads as parallelizable build targets, which might fill the memory completely and make a system crash.

2025-10-07 15:18 UTC, MakisH commented on partitioned-heat-conduction/dirichlet-gismo/clean.sh
> +fi
These should be handled by `clean_precice_logs()`, called by `clean_gismo()` (see https://github.com/precice/tutorials/blob/develop/tools/cleaning-tools.sh)

2025-10-07 15:18 UTC, MakisH commented on partitioned-heat-conduction/dirichlet-gismo/clean.sh
> +done
This is a bit too intrusive (especially for the `.txt` files). Better do a fine-grained extension of `clean_gismo()`.

Same in the `neumann-gismo` directory.

2025-10-07 15:18 UTC, MakisH commented on partitioned-heat-conduction/README.md
> +* G+Smo. Inatsll [G+Smo](https://github.com/gismo/gismo).
```suggestion
* G+Smo. Install [G+Smo](https://github.com/gismo/gismo).
```

But we need a bit more details, or better link to the adapter documentation:


```suggestion
* G+Smo. Install the [G+Smo adapter](https://precice.org/adapter-gismo.html).
```

2025-10-07 15:18 UTC, MakisH commented on partitioned-heat-conduction/README.md
> +```
Could we move most of this content to the adapter documentation, and refer to that?

The path `./gismo_executable/gismo_executable` is assumed by the `run.sh`, so it should probably be documented here. But we should better call that directory `solver-gismo`.

2025-10-07 15:18 UTC, MakisH commented on partitioned-heat-conduction/README.md
> +For G+Smo, please use the file `solution.pvd` in both dirichlet-gismo and neumann-gismo directories.
```suggestion
For G+Smo, please use the generated `solution.pvd` files in the dirichlet-gismo and neumann-gismo directories. 
```

(I thought this was a file in this PR for a moment)

2025-10-07 15:18 UTC, MakisH commented on partitioned-heat-conduction/images/tutorial-partitioned-heat-conduction-gismo.gif
Not yet referred to from the `README.md`. In principle, both FEniCS and G+Smo should give the same solution. If not, we should add the picture in the `README.md` together with a comment.

2025-10-17 09:03 UTC, Crazy-Rich-Meghan commented
> Hi @Crazy-Rich-Meghan,
> 
> 
> 
> thanks for the updates! I am now trying to build on my system, based on the stable branch (Commit [ef4c754785cf4949d3a89b916eed807b74b97a9b](https://github.com/gismo/gismo/commit/ef4c754785cf4949d3a89b916eed807b74b97a9b), October 2).
> 
> 
> 
> I do get a building error, though (`g++ (Ubuntu 12.3.0-1ubuntu1~22.04.2) 12.3.0`):
> 
> 
> 
> ```
> 
> [ 97%] Building CXX object optional/gsPreCICE/examples/CMakeFiles/partitioned-heat-conduction.dir/partitioned-heat-conduction.cpp.o
> 
> /home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp: In function ‘int main(int, char**)’:
> 
> /home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:110:17: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
> 
>   110 |     for (; domIt->good(); domIt->next(), k++ )
> 
>       |                 ^~
> 
> /home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:110:32: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
> 
>   110 |     for (; domIt->good(); domIt->next(), k++ )
> 
>       |                                ^~
> 
> /home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:120:15: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
> 
>   120 |     for (domIt->reset(); domIt->good(); domIt->next(), k++ )
> 
>       |               ^~
> 
> /home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:120:31: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
> 
>   120 |     for (domIt->reset(); domIt->good(); domIt->next(), k++ )
> 
>       |                               ^~
> 
> /home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:120:46: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
> 
>   120 |     for (domIt->reset(); domIt->good(); domIt->next(), k++ )
> 
>       |                                              ^~
> 
> /home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:124:29: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
> 
>   124 |         QuRule->mapTo( domIt->lowerCorner(), domIt->upperCorner(),
> 
>       |                             ^~
> 
> /home/gc/repos/misc/gismo/optional/gsPreCICE/examples/partitioned-heat-conduction.cpp:124:51: error: base operand of ‘->’ has non-pointer type ‘gismo::gsBasis<double>::domainIter’ {aka ‘gismo::gsDomainIteratorWrapper<double>’}
> 
>   124 |         QuRule->mapTo( domIt->lowerCorner(), domIt->upperCorner(),
> 
>       |                                                   ^~
> 
> gmake[3]: *** [optional/gsPreCICE/examples/CMakeFiles/partitioned-heat-conduction.dir/build.make:76: optional/gsPreCICE/examples/CMakeFiles/partitioned-heat-conduction.dir/partitioned-heat-conduction.cpp.o] Error 1
> 
> gmake[2]: *** [CMakeFiles/Makefile2:1940: optional/gsPreCICE/examples/CMakeFiles/partitioned-heat-conduction.dir/all] Error 2
> 
> gmake[1]: *** [CMakeFiles/Makefile2:1947: optional/gsPreCICE/examples/CMakeFiles/partitioned-heat-conduction.dir/rule] Error 2
> 
> gmake: *** [Makefile:907: partitioned-heat-conduction] Error 2
> 
> ```
> 
> 
> 
> By the way, I edited your instructions above to add a number next to the `-j` flag. Without a number, it will use as many threads as parallelizable build targets, which might fill the memory completely and make a system crash.

Hi @Makis, have you pulled the main Gismo? We couldn't replicate the issue (on both MacOS and Ubuntu).

2026-01-09 17:10 UTC, MakisH reviewed
@Crazy-Rich-Meghan I have not forgotten about this PR, and I see there are still some easy points to close. I added a log file with my building issue.

2026-01-09 17:10 UTC, MakisH commented on partitioned-heat-conduction/README.md
> +cmake .. -DGISMO_OPTIONAL="<other submodules>;gsPreCICE"
Do we need other modules for this tutorial? If not, let's remove. If yes, document.

But as I wrote in another comment, this looks like something to move to the adapter documentation.

2026-01-09 17:10 UTC, MakisH commented on partitioned-heat-conduction/README.md
> +make partitioned-heat-conduction -j <number of threads to use>
This is still failing for me with:

```
commit 62078b48516c4a80869c56caab83c393f13640e8 (HEAD -> stable, origin/stable, origin/HEAD)
Merge: cac651c3 f2565ee4
Author: Hugo Verhelst <38376601+hverhelst@users.noreply.github.com>
Date:   Wed Dec 17 15:31:48 2025 +0100

    Merge pull request #778 from gismo/gsCahnHilliardAssembler
    
    Adding a black-box assembler for the Cahn-Hilliard equation & Color output
```

Here is the full log: [gismo-building-issue.log](https://github.com/user-attachments/files/24532037/gismo-building-issue.log)

2026-01-20 09:24 UTC, Crazy-Rich-Meghan commented
Hi @MakisH,

The `domIt->good()` issue has been fixed in gsPreCICE (commit e557b51). Please update your gsPreCICE to the latest version:

```bash
rm -rf optional/gsPreCICE
cmake .. -DGISMO_OPTIONAL="gsPreCICE"
```

2026-01-20 11:51 UTC, MakisH commented on partitioned-heat-conduction/README.md
> +mkdir build
```suggestion
cd gismo
mkdir build
cd build
```

2026-01-20 12:47 UTC, MakisH commented on partitioned-heat-conduction/README.md
> +make partitioned-heat-conduction -j <number of threads to use>
This worked with gsPreCICE commit e557b51.

2026-01-20 12:50 UTC, MakisH commented
Thanks, @Crazy-Rich-Meghan, this worked! The `perpendicular-flap-vertex-gismo` does not build for me anymore, but I will have another look.

If you have no objections, I will (later) push a few changes directly to this branch, to make the tutorial more consistent with https://precice.org/tutorials-perpendicular-flap-stress.html

2026-01-21 19:36 UTC, Crazy-Rich-Meghan commented
Hi @MakisH,

Thanks for the review! I've addressed your comments:

- Updated `clean.sh` scripts to use the standard `clean_gismo()` function
- Simplified the README.md, linking to the adapter documentation
- Updated executable paths in `run.sh` scripts
- Removed the redundant gismo.gif (same result as FEniCS)

Please let me know if there's anything else that needs to be changed.

2026-05-03 17:43 UTC, MakisH commented
@Crazy-Rich-Meghan I am trying to run this case again, but it is failing immediately with:

```
Patches: 1, degree: 2
Active options:
Options (12):
* DirichletStrategy    (int) = 11       Method for enforcement of Dirichlet BCs [11..14]
* DirichletValues      (int) = 101      Method for computation of Dirichlet DoF values [100..103]
* SameElement         (bool) = 1        Activates optimization if all quadrature points are located in the same element
* bdA                 (real) = 2        Estimated nonzeros per column of the matrix: bdA*deg + bdB
* bdB                  (int) = 1        Estimated nonzeros per column of the matrix: bdA*deg + bdB
* bdO                 (real) = 0.333    Overhead of sparse mem. allocation: (1+bdO)(bdA*deg + bdB) [0..1]
* flipSide            (bool) = 0        Flip side of interface where integration is performed.
* movingInterface     (bool) = 0        Used in interface assembly when interface is not stationary.
* overInt             (bool) = 0        Apply over-integration on boundary elements or not?
* quA                 (real) = 1        Number of quadrature points: quA*deg + quB; For patchRule: Regularity of the target space
* quB                  (int) = 1        Number of quadrature points: quA*deg + quB; For patchRule: Degree of the target space
* quRule               (int) = 1        Quadrature rule used (1) Gauss-Legendre; (2) Gauss-Lobatto; (3) Patch-Rule

Assert `index >= 0 && index < size()` 
/home/gc/repos/misc/gismo/external/gsEigen/src/Core/DenseCoeffsBase.h, line 163 (operator[])
terminate called after throwing an instance of 'std::logic_error'
  what():  GISMO_ASSERT
./run.sh: line 7: 90127 Aborted                 (core dumped) ./gismo-executable -c ../precice-config.xml --plot -s 0
```

I am using a clean build of the latest `dev` branch (but an earlier commit was also failing) - commit https://github.com/gismo/gismo/commit/a43e43468a3fd56c3a11c37c90256c7277ad4fd2

I have configured it with the modules `gsElasticity;gsKLShell;gsPreCICE;gsStructuralAnalysis`.

Does the same state of G+Smo work for you?

2026-05-08 11:29 UTC, MakisH commented
@Crazy-Rich-Meghan it would be great to be able to include this in the upcoming distribution release. I think it is very close to merging; I only want to make sure that I can run it, for which I need some help.

2026-05-13 11:50 UTC, MakisH requested changes
I tried again in an Ubuntu 24.04 container and the `partitioned-heat-conduction-direct` case works (note to self: container ID `dfc17ae89aca`, name `affectionate_sinoussi`).

However, the `partitioned-heat-conduction` still seems to be calling the direct mesh access API. @Crazy-Rich-Meghan am I missing some option? Am I building the wrong solver?

2026-05-13 11:50 UTC, MakisH commented on partitioned-heat-conduction/README.md
> +./run.sh
While I can run the `partitioned-heat-conduction-direct` case, this case gives me a configuration error early on. Do I need a different configuration or solver executable?

```
root@dfc17ae89aca:/mnt/host/tutorials/partitioned-heat-conduction/neumann-gismo# ./run.sh 
Started on: Wed, 13 May 2026 13:35:46 +0200
Patches: 1, degree: 2
Active options:
Options (12):
* DirichletStrategy    (int) = 11       Method for enforcement of Dirichlet BCs [11..14]
* DirichletValues      (int) = 101      Method for computation of Dirichlet DoF values [100..103]
* SameElement         (bool) = 1        Activates optimization if all quadrature points are located in the same element
* bdA                 (real) = 2        Estimated nonzeros per column of the matrix: bdA*deg + bdB
* bdB                  (int) = 1        Estimated nonzeros per column of the matrix: bdA*deg + bdB
* bdO                 (real) = 0.333    Overhead of sparse mem. allocation: (1+bdO)(bdA*deg + bdB) [0..1]
* flipSide            (bool) = 0        Flip side of interface where integration is performed.
* movingInterface     (bool) = 0        Used in interface assembly when interface is not stationary.
* overInt             (bool) = 0        Apply over-integration on boundary elements or not?
* quA                 (real) = 1        Number of quadrature points: quA*deg + quB; For patchRule: Regularity of the target space
* quB                  (int) = 1        Number of quadrature points: quA*deg + quB; For patchRule: Degree of the target space
* quRule               (int) = 1        Quadrature rule used (1) Gauss-Legendre; (2) Gauss-Lobatto; (3) Patch-Rule

---[precice]  This is preCICE version 3.4.1
---[precice]  Revision info: no-info [git failed to run]
---[precice]  Build type: Release (without debug log)
---[precice]  Working directory "/mnt/host/tutorials/partitioned-heat-conduction/neumann-gismo"
---[precice]  Configuring preCICE with configuration "../precice-config.xml"
---[precice]  I am participant "Neumann"
GISMO_DEBUG: gsPreCICE.h:178, "setMeshVertices": 
setMeshVertices
---[precice] ERROR:  This participant attempteded to set an access region (via "setMeshAccessRegion") on mesh "Dirichlet-Mesh", but mesh "Dirichlet-Mesh" is either not a received mesh or its api access was not enabled in the configuration. setMeshAccessRegion(...) is only valid for (<receive-mesh name="Dirichlet-Mesh" ... api-access="true"/>).
terminate called after throwing an instance of 'precice::Error'
  what():  This participant attempteded to set an access region (via "setMeshAccessRegion") on mesh "Dirichlet-Mesh", but mesh "Dirichlet-Mesh" is either not a received mesh or its api access was not enabled in the configuration. setMeshAccessRegion(...) is only valid for (<receive-mesh name="Dirichlet-Mesh" ... api-access="true"/>).
```

2026-05-13 15:14 UTC, Crazy-Rich-Meghan commented
Hi @MakisH, changed:

- gismo/gsPreCICE#26 (merged): the example now auto-detects from the
  config whether to use direct mesh access. Same binary handles both
  tutorials.
- This PR: renamed `direct-access` -> `api-access` in the direct config,
  and documented the `gsPreCICE` submodule dependency in the README.

2026-05-13 16:42 UTC, MakisH approved these changes
Everything works as expected now. Thanks a lot for the (many) updates, @Crazy-Rich-Meghan!

2026-05-13 16:43 UTC, merged

2026-07-11 11:40 UTC, makis commented
El vie, 8 may 2026 13:30, Gerasimos Chourdakis ***@***.***>
escribió:

> *MakisH* left a comment (precice/tutorials#604)
> <https://github.com/precice/tutorials/pull/604#issuecomment-4406057601>
>
> @Crazy-Rich-Meghan <https://github.com/Crazy-Rich-Meghan> it would be
> great to be able to include this in the upcoming distribution release. I
> think it is very close to merging; I only want to make sure that I can run
> it, for which I need some help.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/precice/tutorials/pull/604#issuecomment-4406057601>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAY6FITLQVCLO5GALK2GAL4ZXALRAVCNFSM6AAAAABTAM2T5SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHM2DIMBWGA2TONRQGE>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>