Add SU2-FEniCS Perpendicular Flap FSI Tutorial
precice/tutorials pull request #91
Opened 2020-07-07 12:38 UTC by IshaanDesai

For the perpendicular flap FSI tutorial we have the combinations:
`OpenFOAM-FEniCS`
`OpenFOAM-CalculiX`
`SU2-CalculiX` 
To complete all combinations and show the true black-box use of preCICE and the official adapters, this PR adds the `SU2-FEniCS` tutorial case.

2020-08-28 14:17 UTC, IshaanDesai commented
This mesh used for Fluid participant (SU2) is constructed in GMSH and has the structure:
![SU2_mesh](https://user-images.githubusercontent.com/44898158/91578042-e9a4d680-e949-11ea-80d0-d60055ea5939.png)

2020-09-01 15:20 UTC, IshaanDesai commented
The folder [initial-run](https://github.com/precice/tutorials/tree/14a5ad8adefe28c23bb5f8f40df1bf861a401f3e/FSI/flap_perp/SU2-FEniCS/initial_run) gives the setup used to run a SU2 simulation with the flap as a rigid body. The resulting flow profile is used as a reference to run the coupled FSI case.

2020-09-07 11:49 UTC, MakisH commented on FSI/flap_perp/SU2-FEniCS/FEniCS.log
> +---[precice] [0m This is preCICE version 2.0.2
This file should probably not be here.

2020-09-07 12:02 UTC, MakisH commented on FSI/flap_perp/SU2-FEniCS/Output/plotDisplacement.sh
> +plot "point1.watchpoint.txt" using 1:5 smooth cumulative title ""
This name has changed in recent preCICE versions:
```suggestion
plot "precice-Calculix-watchpoint-point1.log using 1:5 smooth cumulative title ""
```
we need to update it elsewhere as well. See changes proposed in https://github.com/precice/tutorials/pull/100.

2020-09-07 12:03 UTC, MakisH commented on FSI/flap_perp/SU2-FEniCS/Su2.log
> +
This file should probably not be here.

2020-09-07 12:04 UTC, MakisH commented on FSI/flap_perp/SU2-FEniCS/plotDisplacement.sh
> +#! /bin/bash
Why do we have this file two times? I guess we should only keep this one (with the updates mentioned in the one under `Output/`).

2020-09-07 12:06 UTC, MakisH requested changes
Thank you very much for adding this! :+1:

There have been quite some changes (about to merge) in the run scripts and configuration, see https://github.com/precice/tutorials/pull/100. Please wait for this to be merged and then port the same changes here.

It would be good to also remove a few log files that slipped through.

2020-09-09 09:14 UTC, IshaanDesai commented
Thanks for the feedback @MakisH ! Will look out for #100 before merging this one. I am still working on this PR because currently the simulation diverges

2020-09-09 10:45 UTC, MakisH commented
@IshaanDesai the SU2-CalculiX also diverges (at least under some systems), so this is not necessarily FEniCS-specific.

2020-10-02 05:57 UTC, IshaanDesai commented
While tuning the SU2-FEniCS case and analysing results, it was found that the su2-adapter works with DisplacementDeltas and the fenics-adapters works with Displacements. To get a working tutorial, the fenics-adapter would need to be modified to handle DisplacementDeltas

2020-10-02 10:25 UTC, MakisH commented
There is also a related issue on adding Displacements to SU2: https://github.com/precice/su2-adapter/issues/17

2020-10-02 12:15 UTC, IshaanDesai commented
Thanks @MakisH for pointing that out! After discussions with @uekerman and @BenjaminRueth it is decided to currently resolve this tutorial via handling `DisplacementDeltas` in the `fenics-adapter`

2020-10-07 07:31 UTC, IshaanDesai commented
After further discussions it was concluded that handling the absolute Displacement values or delta Displacement values is something that a FEniCS user can do in the FEniCS case file. Due to the unique way in which FEniCS is set up and the adapter is constructed it was not found unworthy to implement the handling of `DisplacementDeltas` in the adapter.

2020-10-07 07:32 UTC, IshaanDesai commented
Tip displacement plot:
![tipDispl_SU2_FEniCS](https://user-images.githubusercontent.com/44898158/95300802-f806dc00-087f-11eb-9add-febaccfc09e8.png)
The non-smooth behaviour is because the structure solver in FEniCS is a linear solver.

2020-10-10 18:05 UTC, BenjaminRueth reviewed
I was not able to run the tutorial, since FEniCS suddenly stopped working on my system and I could not run the tutorial. The only thing I can contribute for now is a minor error in documentation that I spotted. I now first have to fix my FEniCS installation.

2020-10-11 13:10 UTC, BenjaminRueth reviewed
After building FEniCS from source I finally got it working again.

Running the tutorial worked for me well using `./runSolid` and `./runFluid`. I was also able to visualize the results.

After 500 timesteps the Solid solver crashed with the following error:

```
---[precice]  it 1 of 50 | dt# 501 of 600 | t 5 | dt 0.01 | max dt 0.01 | ongoing yes | dt complete yes | write-iteration-checkpoint | 

Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
Couldn't map 'f_1182' to a float, returning ufl object without evaluation.
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  RecursionError: maximum recursion depth exceeded while calling a Python object

At:
  /home/benjamin/.local/lib/python3.6/site-packages/ufl/core/operator.py(61): <genexpr>

[benjamin-ThinkPad-X1-Yoga-2nd:11711] *** Process received signal ***
[benjamin-ThinkPad-X1-Yoga-2nd:11711] Signal: Aborted (6)
[benjamin-ThinkPad-X1-Yoga-2nd:11711] Signal code:  (-6)
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3efd0)[0x7f0c3a75cfd0]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f0c3a75cf47]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f0c3a75e8b1]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c957)[0x7f0c3594e957]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92ae6)[0x7f0c35954ae6]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92b21)[0x7f0c35954b21]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d54)[0x7f0c35954d54]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [ 7] /home/benjamin/.local/lib/python3.6/site-packages/dolfin/cpp.cpython-36m-x86_64-linux-gnu.so(+0x292fa8)[0x7f0c38da6fa8]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [ 8] python3(_PyCFunction_FastCallDict+0x35c)[0x566ddc]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [ 9] python3[0x50a783]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [10] python3(_PyEval_EvalFrameDefault+0x444)[0x50c1f4]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [11] python3(_PyFunction_FastCallDict+0xf5)[0x509015]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [12] python3[0x594b01]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [13] python3(PyObject_Call+0x3e)[0x59fe1e]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [14] python3[0x4b1eea]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [15] python3[0x488370]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [16] python3[0x59cb00]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [17] python3(_PyEval_EvalFrameDefault+0x28bc)[0x50e66c]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [18] python3[0x507f24]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [19] python3(PyEval_EvalCode+0x23)[0x50b053]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [20] python3[0x634dd2]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [21] python3(PyRun_FileExFlags+0x97)[0x634e87]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [22] python3(PyRun_SimpleFileExFlags+0x17f)[0x63863f]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [23] python3(Py_Main+0x591)[0x6391e1]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [24] python3(main+0xe0)[0x4b0dc0]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [25] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f0c3a73fb97]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] [26] python3(_start+0x2a)[0x5b26fa]
[benjamin-ThinkPad-X1-Yoga-2nd:11711] *** End of error message ***
```
Any idea what this means? Note: The error might also be caused by my broken system. I see the same error (also after 500 timesteps) for the OpenFOAM-FEniCS tutorial.

I cannot say much about the SU2 part of the new tutorial. The FEniCS part looks good to me.

One minor thing I find distracting is the message 

```
Found a double-boundary point at (-0.05, 0.0).
Found a double-boundary point at (0.05, 0.0).
```

that occasionally pops up. But I think we should discuss this issue elsewhere :arrow_right:  https://github.com/precice/fenics-adapter/issues/90

2020-10-15 07:48 UTC, uekerman requested changes
Thanks for adding this :+1:
Some remarks and small tweaks:

* I get the same crash as @BenjaminRueth. 

* To be consistent to how we organize tutorials currently, the case should better go into `flap_perp_2D`. Soonish we want to re-organize such things anyway (#28), but for now.

* Could you please [format](https://github.com/precice/precice/blob/develop/tools/formatting/config-formatter) the preCICE config and remove all commented out parts there.

* We should carry the case to a valid regime of the linear structural model. So, smaller displacements. For example by increasing the E module.

2020-10-15 11:15 UTC, IshaanDesai commented
Increasing the modulus of elasticity (E) for the structure from 4E5 to 1E6 leads to a smoother tip displacement plot:
![tipDispl_plot](https://user-images.githubusercontent.com/44898158/96116224-697e0480-0ee8-11eb-8f3f-b87c8369cc6d.png)

2020-10-15 21:28 UTC, MakisH commented
> The 2D mesh used for Fluid participant (SU2) is constructed in GMSH and has the structure:
> 
> ![Screenshot from 2020-09-01 16-23-10](https://user-images.githubusercontent.com/44898158/91863581-91364780-ec6f-11ea-8e80-36273faae05e.png)

Could you please describe here how you generated this mesh? Could be useful in the future.

2020-10-15 22:06 UTC, MakisH approved these changes
Excellent! All the configuration files look good, see a few minor comments. :+1:

I cannot run the case at all at the moment (system-specific issue with mpi4py), but since it works for you, go ahead.

Remember to integrate this case into the wiki.

I quickly skimmed through the FEniCS solver code, but I cannot see where the recursion could be originating from. The stack trace also does not help much. Maybe this is originating from the Python bindings?

The SU2-CalculiX case is also unreliable right now, so a convergence issue would not be necessarily a FEniCS issue.

2020-10-16 08:47 UTC, MakisH commented
It would be good to also add this case afterwards to our system tests. We can wait for https://github.com/precice/tutorials/issues/109, or we can simply test only a few seconds.

2020-10-16 13:54 UTC, uekerman approved these changes

2020-10-16 16:42 UTC, BenjaminRueth approved these changes

2020-11-06 21:16 UTC, BenjaminRueth requested changes

2020-11-06 21:16 UTC, BenjaminRueth commented on FSI/flap_perp_2D/SU2-FEniCS/Solid/perp-flap.py
> +        t += dt
```suggestion
        t += float(dt)
```
See https://github.com/precice/tutorials/pull/115

2020-12-19 16:47 UTC, merged