OpenFOAM CalculiX XY (issue#34)
precice/tutorials pull request #92
Opened 2020-07-07 16:24 UTC by Alphaoo1

A flap tutorial case for OpenFOAM-CalculiX, in the XY direction as needed in #34.
The meshes are created using Salome.

If some files are deleted during `./Allclean`, Readme.md contains instructions to recreate those files.
preCICE version 2.0.2
OpenFOAM v7
CalculiX v2.15

Fixes #34.

2020-07-08 06:56 UTC, MakisH commented
Thank you very very much, @Alphaoo!

I think it would be a good idea to actually change the files of the current tutorial, since this is a better default. For people that have already built their cases based on the current orientation, this PR would be a clear indication of what they could change. Moreover, it would make reviewing easier, as we could see the changes only. If anybody still wants to use the previous case, it is always available on GitHub.

@uekerman I vote for replacing the current case instead of adding a new one. What do you think?

@Eder-K this will also then need an update in the reference results of the system tests.

2020-07-08 07:25 UTC, uekerman commented
> @uekerman I vote for replacing the current case instead of adding a new one. What do you think?

Yes, replacing is better than a new one. Is this only for `flap_perp/OpenFOAM-CalculiX`? What about the other cases 3D-3D and 3D-2D cases? Isn't this a larger problem?

2020-07-08 09:44 UTC, MakisH commented
Yes, this affects also the other cases and we should gradually port them as well. For deal.II it will be easy, for SU2 we would need help (maybe a nice first contribution for anyone interested in https://github.com/precice/su2-adapter/issues/16).

2020-09-04 09:31 UTC, Alphaoo1 commented
I have added the [OpenFOAM+CalculiX CHT](https://precice.discourse.group/t/precice-mesh-id-1-error-openfoam-calculix-cht/313/7) case, which have some issues from CalculiX side.
I took the general setup of the flap case from the FSI.

I have adapted the CHT part similar to the heat-exchanger case.

I am currently working on making a flow over the heat plate case similar to [OF+Nutils](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils). I will push as soon as I am done, working towards Issue #103 .

2020-09-07 11:46 UTC, MakisH commented
> I have added the [OpenFOAM+CalculiX CHT](https://precice.discourse.group/t/precice-mesh-id-1-error-openfoam-calculix-cht/313/7) case, which have some issues from CalculiX side.
> I took the general setup of the flap case from the FSI.
> 
> I have adapted the CHT part similar to the heat-exchanger case.
> 
> I am currently working on making a flow over the heat plate case similar to [OF+Nutils](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils). I will push as soon as I am done, working towards Issue #103 .

Thank you very much for contributing, @Alphaoo1! Could you please split this PR to a different one for each tutorial? This would make the review much easier. Otherwise, this may stay an open PR for too long.

2020-09-07 11:48 UTC, Alphaoo1 commented
>Could you please split this PR to a different one for each tutorial? This would make the review much easier. Otherwise, this may stay an open PR for too long.

@MakisH Yes. No Problem.

2020-09-24 13:24 UTC, MakisH commented
@Alphaoo1 could you please also remove all the result files? You can keep a screenshot in the README to help users understand what this is about, but currently this PR has way too many files to start reviewing it. You can have a look at the [files changed tab](https://github.com/precice/tutorials/pull/92/files), where I would like to be able to browse the code and add comments.

Thank you for keeping this up to date all this time! :smiley:

2020-09-24 13:55 UTC, Alphaoo1 commented
@MakisH I have tried to clean up all the things I could think of.

You might find that there are copies of `PolyMesh`, it is because when we do clean case OpenFOAM clears everything, along with the `PolyMesh` directory. 

Let me know if I need to do something else. :smile:

2020-09-24 20:56 UTC, MakisH requested changes
Congratulations of your first preCICE PR review! :partying_face: 

Thank you very much for all the work, please look through my comments and try to apply all the suggestions, if possible, to make this case consistent with the rest of the preCICE tutorials.

See also a separate detailed comment in the discussion, but in this review my main points are:
- Change the approach from Salome-based mesh generation to OpenFOAM/CalculiX-native rotation at preprocessing time.
- Remove some non-relevant changes.
- Move the interFoam-based tutorial to a different PR, preferably after applying the results from our discussion here.

2020-09-24 20:56 UTC, MakisH commented on CHT/flow-over-plate/buoyantPimpleFoam-nutils/OpenFOAM/Extrusion_1.stl
> +solid
I guess we can remove all the new files in `CHT/flow-over-plate/buoyantPimpleFoam-nutils/`.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Allrun
> +#         cgx -bg pre_flap.fbd > prepare_flap.log 2>&1
This has now been removed in #95. Please merge.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Allclean
> +    cd ..
See detailed comment in the conversation: let's not copy an already created mesh, but add the steps to rotate the created mesh into the run scripts.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Allclean
> +# 	rm -fv *.msh
Why keeping these files? Similarly to the OpenFOAM files, let's add the rotation commands to the run scripts.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Allrun
> +#     blockMesh -case ${Participant1} > ${Participant1}_blockMesh.log 2>&1
We want to keep the mesh generation with blockMesh. After this line, we also need to rotate the mesh.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Allrun_parallel
> -./Allrun -parallel
Why deleting this file?

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Fluid/constant/polyMesh/boundary
> +/*--------------------------------*- C++ -*----------------------------------*\
After we add the rotation into the run scripts, we need to remove all the `polyMesh` directories.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Fluid/constant/transportProperties
> +rho             rho [1 -3 0 0 0 0 0] 1e-0;
How is this change related to the rotation? Let's remove this change.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/README.md
> +## flap_perp_Salome_XY
Why changing the title?

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/README.md
> +- In this case, all the geometries and meshes are created with Salome
Instead of using Salome, we can probably achieve the same using:
- [rotateMesh](https://www.openfoam.com/documentation/guides/latest/man/rotateMesh.html) for OpenFOAM
- hopefully some similar tool for CalculiX (or manually, as it is rather small)

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/README.md
> +- Use following commands
What for? I guess that we need to discuss again about the README after we settle on the approach.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Solid/flap.inp
> +Nall, 3, 3, 0
Why this change?

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Solid/flap.inp
> +Nall, 5, 5, 0
Why this change?

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Solid/flap.inp
> +
These whitespace changes are probably done automatic by the editor. We should have some way of automatically formatting these files, but since this is quite tricky, it would be nice if you could avoid these. I can also try to cleanup these at the end.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/precice-config.xml
> +        <max-time value="1"/>
Nice addition, but not related to the rotation, so let's leave it like this or discuss it in a separate PR.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/runFluid
> +# blockMesh -case Fluid
Similarly to `Allrun`: let's keep this.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/runSolid
> +# cd -
Similarly to `Allrun`: let's keep this.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX_interFoam/Allclean
> +#!/bin/sh
Please move the ` FSI/flap_perp/OpenFOAM-CalculiX_interFoam/` into a separate PR.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX_interFoam/Fluid/system/fvSchemes.txt
> +/*--------------------------------*- C++ -*----------------------------------*\
Is this a temporary backup file?

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX_interFoam/Fluid/system/fvSolution.txt
> +/*--------------------------------*- C++ -*----------------------------------*\
Similarly: temporary backup file?

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX_interFoam/README.md
> +# Tutorial for an FSI simulation of an elastic flap perpendicular to a channel flow
This README probably needs to be updated to correspond to the interFoam case.

2020-09-24 20:56 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX_interFoam/precice-config.xml
> +    </coupling-scheme:serial-implicit>-->
This file needs some clean-up. We should choose a config that is robust but also uses default values wherever possible.

2020-09-24 20:57 UTC, MakisH commented
Thank you, @Alphaoo1! I additionally removed all the `OpenFOAM-CalculiX_interFoam/Solid/*.vtu` files and we are now down to 88 files: that's more manageable. :smile: 

> You might find that there are copies of PolyMesh, it is because when we do clean case OpenFOAM clears everything, along with the PolyMesh directory.

I see that you are essentially taking the already produced mesh and rotating it. This is now an ideal solution, however, because:
1. we need to distribute the mesh, which adds several new files and significantly increases the size of the repository.
2. the user cannot easily modify the (already produced) mesh.

I understand also that this is the easy solution and manually converting the blockMeshDict would be painful. I would then propose the following: let's keep the original blockMeshDict files and add the rotation commands in the run scripts. Then the user should be happy, even though a bit puzzled for the additional step. But this is then future problem.

Before we start looking into details, let's also break this PR to smaller ones, one for each tutorial. With a [quick look](https://github.com/precice/tutorials/pull/92/files), I see changes/additions in the following directories:
- `CHT/flow-over-plate/buoyantPimpleFoam-nutils/`: I assume these are probably residues from a previous run, so we can remove all the new files. We anyway don't need to rotate this case.
- `FSI/flap_perp/OpenFOAM-CalculiX`: These changes stay in this PR.
   - I see also a binary file `FSI/flap_perp/OpenFOAM-CalculiX/Fluid/Fluid_XY.hdf`. What is this? We probably don't need it here. Similarly for `FSI/flap_perp/OpenFOAM-CalculiX/Fluid/Fluid_xy_original.unv `.
   - I see that you renamed the `blockMeshDict` to `blockMeshDict_original`. Let's rename it back to `blockMeshDict` and use it.
- ` FSI/flap_perp/OpenFOAM-CalculiX_interFoam`: This is a different case, let's move it to a separate PR. Many points of the review will also apply there, so let's first get this one merged.

In any case, please make your new PRs to target the `develop` branch of the tutorials. You can also change the target branch of this one, by clicking `edit` next to the title. Preferably merge the latest updates from [develop](https://github.com/precice/tutorials/tree/develop) into your branch first (`git merge develop`). Everything will hopefully be merged automatically, without any conflicts.

2020-09-25 06:26 UTC, Alphaoo1 commented on FSI/flap_perp/OpenFOAM-CalculiX/Allclean
> +    cd ..
> Thank you, @Alphaoo1! I additionally removed all the `OpenFOAM-CalculiX_interFoam/Solid/*.vtu` files and we are now down to 88 files: that's more manageable. 
>
Thank you for your patience @MakisH, I am a bit new to git workflow so not yet up to the standards.

> > You might find that there are copies of PolyMesh, it is because when we do clean case OpenFOAM clears everything, along with the PolyMesh directory.
> 
> I see that you are essentially taking the already produced mesh and rotating it. This is now an ideal solution, however, because:
> 
> 1. we need to distribute the mesh, which adds several new files and significantly increases the size of the repository.
> 2. the user cannot easily modify the (already produced) mesh.
> 

No I am not rotating the already produced mesh.
I use `ideasUnvToFoam Fluid_xy_original.unv` to create the `polyMesh` directory.
I tried rotating the mesh using the commands available in OpenFOAM, it works fine, but the rotation of CalculiX is a bit tricky and it does not exactly match with Fluid mesh. This is why I chose to make a new mesh all together.

> I understand also that this is the easy solution and manually converting the blockMeshDict would be painful. I would then propose the following: let's keep the original blockMeshDict files and add the rotation commands in the run scripts. Then the user should be happy, even though a bit puzzled for the additional step. But this is then future problem.
> 
As I said earlier, it's a bit more complicated to directly rotate mesh and have it aligned with Solid mesh.
I went through the files again, and we only need to keep the `boundary` file from `polyMesh_backup`.
When we do `ideasUnvToFoam Fluid_xy_original.unv`, it creates a `boundary` file with all the boundaries with `type patch`. We have `type wall` for some boundaries, so I chose to copy the polyMesh folder.
I have added this command to `runFluid` if we want to go in this direction.

> Before we start looking into details, let's also break this PR to smaller ones, one for each tutorial. With a [quick look](https://github.com/precice/tutorials/pull/92/files), I see changes/additions in the following directories:
> 
> * `CHT/flow-over-plate/buoyantPimpleFoam-nutils/`: I assume these are probably residues from a previous run, so we can remove all the new files. We anyway don't need to rotate this case.
Yes. Will do

> * `FSI/flap_perp/OpenFOAM-CalculiX`: These changes stay in this PR.
>   
>   * I see also a binary file `FSI/flap_perp/OpenFOAM-CalculiX/Fluid/Fluid_XY.hdf`. What is this? We probably don't need it here. Similarly for `FSI/flap_perp/OpenFOAM-CalculiX/Fluid/Fluid_xy_original.unv `.
>   * I see that you renamed the `blockMeshDict` to `blockMeshDict_original`. Let's rename it back to `blockMeshDict` and use it.
The `.hdf` file is the file for original geometry and mesh created in Salome. `.unv` file is exported from Salome and converted into `polyMesh` using the command I mentioned earlier.

> * ` FSI/flap_perp/OpenFOAM-CalculiX_interFoam`: This is a different case, let's move it to a separate PR. Many points of the review will also apply there, so let's first get this one merged.
> 
Yes, I will create a new PR for the interFoam.

> In any case, please make your new PRs to target the `develop` branch of the tutorials. You can also change the target branch of this one, by clicking `edit` next to the title. Preferably merge the latest updates from [develop](https://github.com/precice/tutorials/tree/develop) into your branch first (`git merge develop`). Everything will hopefully be merged automatically, without any conflicts.

Ok. I will do the changes.
Let me know what do you think about my comments. and I will make changes accordingly.

2020-09-25 06:26 UTC, Alphaoo1 commented on FSI/flap_perp/OpenFOAM-CalculiX/Allclean
> +# 	rm -fv *.msh
>Why keeping these files? 
As we have `pre_flap.fbd` in the original tutorial case, it has commands to export the `.nam` and `.msh` files. But in this case, I had to do it manually. The commands are the same but I haven't yet figured out how to write a script to export all these files.

>Similarly to the OpenFOAM files, let's add the rotation commands to the run scripts.
CalculiX does not rotate around the same point as OpenFOAM, and ultimately we have a bit mismatching meshes.
(one does rotation around the origin and the other does rotation around a corner, but I don't remember now which is which).
It was easier for me to just create new geometry and new mesh in Salome. :sweat_smile: 

But yes, Salome workflow might not be fitting to everyone.

2020-09-25 06:28 UTC, Alphaoo1 commented on FSI/flap_perp/OpenFOAM-CalculiX_interFoam/README.md
> +# Tutorial for an FSI simulation of an elastic flap perpendicular to a channel flow
I will work on this.

2020-09-25 06:29 UTC, Alphaoo1 commented
> Thank you, @Alphaoo1! I additionally removed all the `OpenFOAM-CalculiX_interFoam/Solid/*.vtu` files and we are now down to 88 files: that's more manageable. 
>

Thank you for your patience @MakisH, I am a bit new to git workflow so not yet up to the standards.

> > You might find that there are copies of PolyMesh, it is because when we do clean case OpenFOAM clears everything, along with the PolyMesh directory.
> 
> I see that you are essentially taking the already produced mesh and rotating it. This is now an ideal solution, however, because:
> 
> 1. we need to distribute the mesh, which adds several new files and significantly increases the size of the repository.
> 2. the user cannot easily modify the (already produced) mesh.
> 

No I am not rotating the already produced mesh.
I use `ideasUnvToFoam Fluid_xy_original.unv` to create the `polyMesh` directory.
I tried rotating the mesh using the commands available in OpenFOAM, it works fine, but the rotation of CalculiX is a bit tricky and it does not exactly match with Fluid mesh. This is why I chose to make a new mesh all together.

> I understand also that this is the easy solution and manually converting the blockMeshDict would be painful. I would then propose the following: let's keep the original blockMeshDict files and add the rotation commands in the run scripts. Then the user should be happy, even though a bit puzzled for the additional step. But this is then future problem.
> 

As I said earlier, it's a bit more complicated to directly rotate mesh and have it aligned with Solid mesh.
I went through the files again, and we only need to keep the `boundary` file from `polyMesh_backup`.
When we do `ideasUnvToFoam Fluid_xy_original.unv`, it creates a `boundary` file with all the boundaries with `type patch`. We have `type wall` for some boundaries, so I chose to copy the polyMesh folder.
I have added this command to `runFluid` if we want to go in this direction.

> Before we start looking into details, let's also break this PR to smaller ones, one for each tutorial. With a [quick look](https://github.com/precice/tutorials/pull/92/files), I see changes/additions in the following directories:
> 
> * `CHT/flow-over-plate/buoyantPimpleFoam-nutils/`: I assume these are probably residues from a previous run, so we can remove all the new files. We anyway don't need to rotate this case.

Yes. Will do

> * `FSI/flap_perp/OpenFOAM-CalculiX`: These changes stay in this PR.
>   
>   * I see also a binary file `FSI/flap_perp/OpenFOAM-CalculiX/Fluid/Fluid_XY.hdf`. What is this? We probably don't need it here. Similarly for `FSI/flap_perp/OpenFOAM-CalculiX/Fluid/Fluid_xy_original.unv `.
>   * I see that you renamed the `blockMeshDict` to `blockMeshDict_original`. Let's rename it back to `blockMeshDict` and use it.

The `.hdf` file is the file for original geometry and mesh created in Salome. `.unv` file is exported from Salome and converted into `polyMesh` using the command I mentioned earlier.

> * ` FSI/flap_perp/OpenFOAM-CalculiX_interFoam`: This is a different case, let's move it to a separate PR. Many points of the review will also apply there, so let's first get this one merged.
> 

Yes, I will create a new PR for the interFoam.

> In any case, please make your new PRs to target the `develop` branch of the tutorials. You can also change the target branch of this one, by clicking `edit` next to the title. Preferably merge the latest updates from [develop](https://github.com/precice/tutorials/tree/develop) into your branch first (`git merge develop`). Everything will hopefully be merged automatically, without any conflicts.

Ok. I will do the changes.
Let me know what do you think about my comments. and I will make changes accordingly.

2020-09-25 07:37 UTC, MakisH commented on FSI/flap_perp/OpenFOAM-CalculiX/Allclean
> +# 	rm -fv *.msh
Probably the Salome workflow would be a quite pragmatic approach: many users use it anyway. However, we try to keep the dependencies of the tutorials to a minimum (preCICE already has too many dependencies and components). In any case, this is a tutorial to learn how to use preCICE and its adapters, not how to make a perfect FSI simulation.

What if we just rotate the CalculiX case by hand, e.g. using the Salome output as an example?

2020-09-25 07:49 UTC, MakisH commented
> Thank you for your patience @MakisH, I am a bit new to git workflow so not yet up to the standards.

Welcome to the git workflow! :hugs: I am always very happy to help anybody trying to learn, especially if it results in a contribution here.

Pro tip: you are currently requesting to merge from your master branch. But now with all these changes I proposed you will mess up your current production work. So, better keep different "features" in different branches. For now, better make a branch for your work and keep this PR from master.

> No I am not rotating the already produced mesh.
I use ideasUnvToFoam Fluid_xy_original.unv to create the polyMesh directory.

I had not heard about this tool before. Interesting but maybe not really needed. I will check again in a second round.

> I tried rotating the mesh using the commands available in OpenFOAM, it works fine, but the rotation of CalculiX is a bit tricky and it does not exactly match with Fluid mesh. This is why I chose to make a new mesh all together.

What do you mean "does not exactly match with Fluid mesh"? Unless there is an offset/rotation, this should not be an issue for preCICE.

Ideally, we would like a rotated blockMeshDict and a rotated CalculiX configuration. This should be the cleanest solution and maybe not so difficult in this case, since the geometries are rather simple. I guess we should at least try to remove the Salome dependency and see what we can do afterwards.

2021-04-12 20:27 UTC, MakisH commented
We forgot about this for a while, but it is also fine, as https://github.com/precice/tutorials/pull/146 now rotated the case as part of a larger restructuring project.

2021-04-12 20:27 UTC, closed without merging